/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {17, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* Drone_ode_complete_cost_ext_cost_0_fun:(i0[13],i1[4],i2[0],i3[17])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55;
  casadi_real *w23=w+58, *w24=w+67, *w25=w+76, *w26=w+79, *w27=w+83, *w28=w+87, *w29=w+91;
  const casadi_real *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 25 */
  w02 = 25.;
  /* #40: @24 = @23; (@24[0] = @2) */
  casadi_copy(w23, 9, w24);
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #41: (@24[4] = @2) */
  for (rr=w24+4, cs=(&w02); rr!=w24+5; rr+=1) *rr = *cs++;
  /* #42: @2 = 30 */
  w02 = 30.;
  /* #43: (@24[8] = @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr = *cs++;
  /* #44: @25 = mac(@22,@24,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #45: @2 = mac(@25,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #47: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #48: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #49: @5 = input[1][2] */
  w05 = arg[1] ? arg[1][2] : 0;
  /* #50: @6 = input[1][3] */
  w06 = arg[1] ? arg[1][3] : 0;
  /* #51: @27 = vertcat(@3, @4, @5, @6) */
  rr=w27;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #52: @28 = @27' */
  casadi_copy(w27, 4, w28);
  /* #53: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #54: @3 = 1 */
  w03 = 1.;
  /* #55: (@29[0] = @3) */
  for (rr=w29+0, cs=(&w03); rr!=w29+1; rr+=1) *rr = *cs++;
  /* #56: @3 = 800 */
  w03 = 800.;
  /* #57: (@29[5] = @3) */
  for (rr=w29+5, cs=(&w03); rr!=w29+6; rr+=1) *rr = *cs++;
  /* #58: (@29[10] = @3) */
  for (rr=w29+10, cs=(&w03); rr!=w29+11; rr+=1) *rr = *cs++;
  /* #59: (@29[15] = @3) */
  for (rr=w29+15, cs=(&w03); rr!=w29+16; rr+=1) *rr = *cs++;
  /* #60: @26 = mac(@28,@29,@26) */
  for (i=0, rr=w26; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #61: @3 = mac(@26,@27,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w26+j, ct=w27+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #62: @2 = (@2+@3) */
  w02 += w03;
  /* #63: @9 = (-@9) */
  w09 = (- w09 );
  /* #64: @10 = (-@10) */
  w10 = (- w10 );
  /* #65: @11 = (-@11) */
  w11 = (- w11 );
  /* #66: @26 = vertcat(@8, @9, @10, @11) */
  rr=w26;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #67: @27 = @21[6:10] */
  for (rr=w27, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #68: @8 = ||@27||_F */
  w08 = casadi_norm_2(4, w27);
  /* #69: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #70: {@8, @9, @10, @11} = vertsplit(@26) */
  w08 = w26[0];
  w09 = w26[1];
  w10 = w26[2];
  w11 = w26[3];
  /* #71: @26 = @19[6:10] */
  for (rr=w26, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #72: {@3, @4, @5, @6} = vertsplit(@26) */
  w03 = w26[0];
  w04 = w26[1];
  w05 = w26[2];
  w06 = w26[3];
  /* #73: @7 = (@8*@3) */
  w07  = (w08*w03);
  /* #74: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #75: @7 = (@7-@12) */
  w07 -= w12;
  /* #76: @12 = (@10*@5) */
  w12  = (w10*w05);
  /* #77: @7 = (@7-@12) */
  w07 -= w12;
  /* #78: @12 = (@11*@6) */
  w12  = (w11*w06);
  /* #79: @7 = (@7-@12) */
  w07 -= w12;
  /* #80: @12 = (@7<@0) */
  w12  = (w07<w00);
  /* #81: @13 = (@8*@4) */
  w13  = (w08*w04);
  /* #82: @14 = (@9*@3) */
  w14  = (w09*w03);
  /* #83: @13 = (@13+@14) */
  w13 += w14;
  /* #84: @14 = (@10*@6) */
  w14  = (w10*w06);
  /* #85: @13 = (@13+@14) */
  w13 += w14;
  /* #86: @14 = (@11*@5) */
  w14  = (w11*w05);
  /* #87: @13 = (@13-@14) */
  w13 -= w14;
  /* #88: @14 = (@8*@5) */
  w14  = (w08*w05);
  /* #89: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #90: @14 = (@14-@15) */
  w14 -= w15;
  /* #91: @15 = (@10*@3) */
  w15  = (w10*w03);
  /* #92: @14 = (@14+@15) */
  w14 += w15;
  /* #93: @15 = (@11*@4) */
  w15  = (w11*w04);
  /* #94: @14 = (@14+@15) */
  w14 += w15;
  /* #95: @8 = (@8*@6) */
  w08 *= w06;
  /* #96: @9 = (@9*@5) */
  w09 *= w05;
  /* #97: @8 = (@8+@9) */
  w08 += w09;
  /* #98: @10 = (@10*@4) */
  w10 *= w04;
  /* #99: @8 = (@8-@10) */
  w08 -= w10;
  /* #100: @11 = (@11*@3) */
  w11 *= w03;
  /* #101: @8 = (@8+@11) */
  w08 += w11;
  /* #102: @26 = vertcat(@7, @13, @14, @8) */
  rr=w26;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w08;
  /* #103: @27 = (-@26) */
  for (i=0, rr=w27, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #104: @27 = (@12?@27:0) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #105: @12 = (!@12) */
  w12 = (! w12 );
  /* #106: @26 = (@12?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #107: @27 = (@27+@26) */
  for (i=0, rr=w27, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #108: @25 = @27[1:4] */
  for (rr=w25, cs=w27+1; cs!=w27+4; cs+=1) *rr++ = *cs;
  /* #109: @20 = (2.*@25) */
  for (i=0, rr=w20, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #110: @12 = ||@25||_F */
  w12 = casadi_norm_2(3, w25);
  /* #111: @7 = @27[0] */
  for (rr=(&w07), cs=w27+0; cs!=w27+1; cs+=1) *rr++ = *cs;
  /* #112: @7 = atan2(@12,@7) */
  w07  = atan2(w12,w07);
  /* #113: @20 = (@20*@7) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w07;
  /* #114: @20 = (@20/@12) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w12;
  /* #115: @25 = @20' */
  casadi_copy(w20, 3, w25);
  /* #116: @12 = 12 */
  w12 = 12.;
  /* #117: (@23[0] = @12) */
  for (rr=w23+0, cs=(&w12); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #118: (@23[4] = @12) */
  for (rr=w23+4, cs=(&w12); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #119: (@23[8] = @12) */
  for (rr=w23+8, cs=(&w12); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #120: @1 = mac(@25,@23,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #121: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #122: @2 = (@2+@0) */
  w02 += w00;
  /* #123: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 107;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 107*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
