/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s4[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s5[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s7[11] = 
  {0, 1, 2, 3, 4, 5, 6, 10,
  11, 12, 13};
static const casadi_int casadi_s8[11] = 
  {0, 1, 2, 3, 16, 17, 18, 25,
  26, 27, 28};
static const casadi_int casadi_s9[11] = 
  {0, 4, 8, 12, 16, 19, 22, 25,
  29, 33, 37};
static const casadi_int casadi_s10[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[11] = 
  {4, 5, 6, 7, 19, 20, 21, 29,
  30, 31, 32};
static const casadi_int casadi_s14[11] = 
  {1, 5, 9, 13, 17, 20, 23, 26,
  30, 34, 38};
static const casadi_int casadi_s15[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s17[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s18[11] = 
  {8, 9, 10, 11, 22, 23, 24, 33,
  34, 35, 36};
static const casadi_int casadi_s19[11] = 
  {2, 6, 10, 14, 18, 21, 24, 27,
  31, 35, 39};
static const casadi_int casadi_s20[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s21[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s22[61] = 
  {17, 17, 0, 4, 8, 12, 16, 19,
  22, 25, 25, 25, 25, 29, 33, 37,
  41, 41, 41, 41, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 4, 5, 6, 4,
  5, 6, 4, 5, 6, 10, 11, 12,
  13, 10, 11, 12, 13, 10, 11, 12,
  13, 10, 11, 12, 13};
static const casadi_int casadi_s23[3] = {13, 1, 1};
static const casadi_int casadi_s24[3] = {4, 1, 1};
static const casadi_int casadi_s25[3] = {0, 1, 1};
static const casadi_int casadi_s26[3] = {17, 1, 1};
static const casadi_int casadi_s27[3] = {1, 1, 1};
static const casadi_int casadi_s28[3] = {0, 0, 1};
static const casadi_int casadi_s29[3] = {0, 17, 1};

/* Drone_ode_complete_cost_ext_cost_fun_jac_hess:(i0[13],i1[4],i2[0],i3[17])->(o0,o1[17],o2[17x17,41nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *tt, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42;
  casadi_real *w22=w+55, *w23=w+58, *w24=w+67, *w25=w+76, *w26=w+79, *w27=w+83, *w28=w+87, *w29=w+91, *w30=w+107, *w31=w+111, *w32=w+115, *w33=w+119;
  casadi_real *w34=w+123, *w35=w+126, *w36=w+129, *w37=w+132, *w38=w+135, *w39=w+151, *w40=w+160, *w41=w+163, *w42=w+166, w43, w44, w45;
  casadi_real w46, w47, *w48=w+174, *w49=w+187, w50, w51, w52, w53, w54, w55, *w56=w+202, *w57=w+243;
  casadi_real *w59=w+252, *w60=w+256, w61, w62, *w63=w+262, *w64=w+266, *w65=w+269, *w66=w+272, w67, w68, w69, w70;
  casadi_real *w71=w+279, w72, w73, w74, w75, w76, w77, w78, *w79=w+290, *w80=w+301, *w81=w+304, *w82=w+306;
  casadi_real *w83=w+314;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 25 */
  w02 = 25.;
  /* #40: @24 = @23; (@24[0] = @2) */
  casadi_copy(w23, 9, w24);
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #41: (@24[4] = @2) */
  for (rr=w24+4, cs=(&w02); rr!=w24+5; rr+=1) *rr = *cs++;
  /* #42: @2 = 30 */
  w02 = 30.;
  /* #43: (@24[8] = @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr = *cs++;
  /* #44: @25 = mac(@22,@24,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #45: @2 = mac(@25,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #47: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #48: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #49: @5 = input[1][2] */
  w05 = arg[1] ? arg[1][2] : 0;
  /* #50: @6 = input[1][3] */
  w06 = arg[1] ? arg[1][3] : 0;
  /* #51: @27 = vertcat(@3, @4, @5, @6) */
  rr=w27;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #52: @28 = @27' */
  casadi_copy(w27, 4, w28);
  /* #53: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #54: @3 = 1 */
  w03 = 1.;
  /* #55: (@29[0] = @3) */
  for (rr=w29+0, cs=(&w03); rr!=w29+1; rr+=1) *rr = *cs++;
  /* #56: @3 = 800 */
  w03 = 800.;
  /* #57: (@29[5] = @3) */
  for (rr=w29+5, cs=(&w03); rr!=w29+6; rr+=1) *rr = *cs++;
  /* #58: (@29[10] = @3) */
  for (rr=w29+10, cs=(&w03); rr!=w29+11; rr+=1) *rr = *cs++;
  /* #59: (@29[15] = @3) */
  for (rr=w29+15, cs=(&w03); rr!=w29+16; rr+=1) *rr = *cs++;
  /* #60: @30 = mac(@28,@29,@26) */
  casadi_copy(w26, 4, w30);
  for (i=0, rr=w30; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #61: @3 = mac(@30,@27,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w30+j, ct=w27+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #62: @2 = (@2+@3) */
  w02 += w03;
  /* #63: @9 = (-@9) */
  w09 = (- w09 );
  /* #64: @10 = (-@10) */
  w10 = (- w10 );
  /* #65: @11 = (-@11) */
  w11 = (- w11 );
  /* #66: @27 = vertcat(@8, @9, @10, @11) */
  rr=w27;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #67: @31 = @21[6:10] */
  for (rr=w31, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #68: @8 = ||@31||_F */
  w08 = casadi_norm_2(4, w31);
  /* #69: @27 = (@27/@8) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w08;
  /* #70: {@9, @10, @11, @3} = vertsplit(@27) */
  w09 = w27[0];
  w10 = w27[1];
  w11 = w27[2];
  w03 = w27[3];
  /* #71: @32 = @19[6:10] */
  for (rr=w32, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #72: {@4, @5, @6, @7} = vertsplit(@32) */
  w04 = w32[0];
  w05 = w32[1];
  w06 = w32[2];
  w07 = w32[3];
  /* #73: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #74: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #75: @12 = (@12-@13) */
  w12 -= w13;
  /* #76: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #77: @12 = (@12-@13) */
  w12 -= w13;
  /* #78: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #79: @12 = (@12-@13) */
  w12 -= w13;
  /* #80: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #81: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #82: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #83: @14 = (@14+@15) */
  w14 += w15;
  /* #84: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #85: @14 = (@14+@15) */
  w14 += w15;
  /* #86: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #87: @14 = (@14-@15) */
  w14 -= w15;
  /* #88: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #89: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #90: @15 = (@15-@16) */
  w15 -= w16;
  /* #91: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #92: @15 = (@15+@16) */
  w15 += w16;
  /* #93: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #94: @15 = (@15+@16) */
  w15 += w16;
  /* #95: @9 = (@9*@7) */
  w09 *= w07;
  /* #96: @10 = (@10*@6) */
  w10 *= w06;
  /* #97: @9 = (@9+@10) */
  w09 += w10;
  /* #98: @11 = (@11*@5) */
  w11 *= w05;
  /* #99: @9 = (@9-@11) */
  w09 -= w11;
  /* #100: @3 = (@3*@4) */
  w03 *= w04;
  /* #101: @9 = (@9+@3) */
  w09 += w03;
  /* #102: @32 = vertcat(@12, @14, @15, @9) */
  rr=w32;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #103: @33 = (-@32) */
  for (i=0, rr=w33, cs=w32; i<4; ++i) *rr++ = (- *cs++ );
  /* #104: @33 = (@13?@33:0) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #105: @12 = (!@13) */
  w12 = (! w13 );
  /* #106: @32 = (@12?@32:0) */
  for (i=0, rr=w32, cs=w32; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #107: @33 = (@33+@32) */
  for (i=0, rr=w33, cs=w32; i<4; ++i) (*rr++) += (*cs++);
  /* #108: @20 = @33[1:4] */
  for (rr=w20, cs=w33+1; cs!=w33+4; cs+=1) *rr++ = *cs;
  /* #109: @34 = (2.*@20) */
  for (i=0, rr=w34, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #110: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #111: @15 = @33[0] */
  for (rr=(&w15), cs=w33+0; cs!=w33+1; cs+=1) *rr++ = *cs;
  /* #112: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #113: @35 = (@34*@9) */
  for (i=0, rr=w35, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #114: @35 = (@35/@14) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w14;
  /* #115: @36 = @35' */
  casadi_copy(w35, 3, w36);
  /* #116: @3 = 12 */
  w03 = 12.;
  /* #117: (@23[0] = @3) */
  for (rr=w23+0, cs=(&w03); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #118: (@23[4] = @3) */
  for (rr=w23+4, cs=(&w03); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #119: (@23[8] = @3) */
  for (rr=w23+8, cs=(&w03); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #120: @37 = mac(@36,@23,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #121: @0 = mac(@37,@35,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #122: @2 = (@2+@0) */
  w02 += w00;
  /* #123: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #124: @30 = @30' */
  /* #125: @38 = @29' */
  for (i=0, rr=w38, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #126: @33 = mac(@28,@38,@26) */
  casadi_copy(w26, 4, w33);
  for (i=0, rr=w33; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w38+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #127: @33 = @33' */
  /* #128: @30 = (@30+@33) */
  for (i=0, rr=w30, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #129: {@2, @0, @3, @11} = vertsplit(@30) */
  w02 = w30[0];
  w00 = w30[1];
  w03 = w30[2];
  w11 = w30[3];
  /* #130: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #131: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #132: output[1][2] = @3 */
  if (res[1]) res[1][2] = w03;
  /* #133: output[1][3] = @11 */
  if (res[1]) res[1][3] = w11;
  /* #134: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #135: @27 = (@27/@8) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w08;
  /* #136: @30 = (-@27) */
  for (i=0, rr=w30, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #137: @33 = zeros(4x1) */
  casadi_clear(w33, 4);
  /* #138: @11 = sq(@14) */
  w11 = casadi_sq( w14 );
  /* #139: @3 = sq(@15) */
  w03 = casadi_sq( w15 );
  /* #140: @11 = (@11+@3) */
  w11 += w03;
  /* #141: @3 = (@14/@11) */
  w03  = (w14/w11);
  /* #142: @37 = @37' */
  /* #143: @39 = @23' */
  for (i=0, rr=w39, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #144: @40 = mac(@36,@39,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #145: @40 = @40' */
  /* #146: @37 = (@37+@40) */
  for (i=0, rr=w37, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #147: @40 = (@37/@14) */
  for (i=0, rr=w40, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #148: @0 = dot(@34, @40) */
  w00 = casadi_dot(3, w34, w40);
  /* #149: @2 = (@3*@0) */
  w02  = (w03*w00);
  /* #150: @2 = (-@2) */
  w02 = (- w02 );
  /* #151: @28 = @33; (@28[0] += @2) */
  casadi_copy(w33, 4, w28);
  for (rr=w28+0, cs=(&w02); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #152: @35 = (@35/@14) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w14;
  /* #153: @36 = (-@35) */
  for (i=0, rr=w36, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #154: @2 = dot(@36, @37) */
  w02 = casadi_dot(3, w36, w37);
  /* #155: @10 = (@15/@11) */
  w10  = (w15/w11);
  /* #156: @16 = (@10*@0) */
  w16  = (w10*w00);
  /* #157: @2 = (@2+@16) */
  w02 += w16;
  /* #158: @2 = (@2/@14) */
  w02 /= w14;
  /* #159: @41 = (@2*@20) */
  for (i=0, rr=w41, cs=w20; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #160: @42 = (@9*@40) */
  for (i=0, rr=w42, cs=w40; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #161: @42 = (2.*@42) */
  for (i=0, rr=w42, cs=w42; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #162: @41 = (@41+@42) */
  for (i=0, rr=w41, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #163: (@28[1:4] += @41) */
  for (rr=w28+1, cs=w41; rr!=w28+4; rr+=1) *rr += *cs++;
  /* #164: @32 = (@12?@28:0) */
  for (i=0, rr=w32, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #165: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #166: @28 = (@13?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #167: @32 = (@32+@28) */
  for (i=0, rr=w32, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #168: {@16, @17, @18, @43} = vertsplit(@32) */
  w16 = w32[0];
  w17 = w32[1];
  w18 = w32[2];
  w43 = w32[3];
  /* #169: @44 = (@7*@43) */
  w44  = (w07*w43);
  /* #170: @45 = (@6*@18) */
  w45  = (w06*w18);
  /* #171: @44 = (@44+@45) */
  w44 += w45;
  /* #172: @45 = (@5*@17) */
  w45  = (w05*w17);
  /* #173: @44 = (@44+@45) */
  w44 += w45;
  /* #174: @45 = (@4*@16) */
  w45  = (w04*w16);
  /* #175: @44 = (@44+@45) */
  w44 += w45;
  /* #176: @45 = (@6*@43) */
  w45  = (w06*w43);
  /* #177: @46 = (@7*@18) */
  w46  = (w07*w18);
  /* #178: @45 = (@45-@46) */
  w45 -= w46;
  /* #179: @46 = (@4*@17) */
  w46  = (w04*w17);
  /* #180: @45 = (@45+@46) */
  w45 += w46;
  /* #181: @46 = (@5*@16) */
  w46  = (w05*w16);
  /* #182: @45 = (@45-@46) */
  w45 -= w46;
  /* #183: @46 = (@4*@18) */
  w46  = (w04*w18);
  /* #184: @47 = (@5*@43) */
  w47  = (w05*w43);
  /* #185: @46 = (@46-@47) */
  w46 -= w47;
  /* #186: @47 = (@7*@17) */
  w47  = (w07*w17);
  /* #187: @46 = (@46+@47) */
  w46 += w47;
  /* #188: @47 = (@6*@16) */
  w47  = (w06*w16);
  /* #189: @46 = (@46-@47) */
  w46 -= w47;
  /* #190: @43 = (@4*@43) */
  w43  = (w04*w43);
  /* #191: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #192: @43 = (@43+@18) */
  w43 += w18;
  /* #193: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #194: @43 = (@43-@17) */
  w43 -= w17;
  /* #195: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #196: @43 = (@43-@16) */
  w43 -= w16;
  /* #197: @32 = vertcat(@44, @45, @46, @43) */
  rr=w32;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w43;
  /* #198: @44 = dot(@30, @32) */
  w44 = casadi_dot(4, w30, w32);
  /* #199: @44 = (@44/@8) */
  w44 /= w08;
  /* #200: @28 = (@44*@31) */
  for (i=0, rr=w28, cs=w31; i<4; ++i) (*rr++)  = (w44*(*cs++));
  /* #201: @48 = @21; (@48[6:10] += @28) */
  casadi_copy(w21, 13, w48);
  for (rr=w48+6, cs=w28; rr!=w48+10; rr+=1) *rr += *cs++;
  /* #202: @25 = @25' */
  /* #203: @49 = @24' */
  for (i=0, rr=w49, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #204: @41 = mac(@22,@49,@1) */
  casadi_copy(w01, 3, w41);
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w49+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #205: @41 = @41' */
  /* #206: @25 = (@25+@41) */
  for (i=0, rr=w25, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #207: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #208: (@48[:3] += @25) */
  for (rr=w48+0, cs=w25; rr!=w48+3; rr+=1) *rr += *cs++;
  /* #209: {@45, @46, @43, @16, @17, @18, @47, @50, @51, @52, @53, @54, @55} = vertsplit(@48) */
  w45 = w48[0];
  w46 = w48[1];
  w43 = w48[2];
  w16 = w48[3];
  w17 = w48[4];
  w18 = w48[5];
  w47 = w48[6];
  w50 = w48[7];
  w51 = w48[8];
  w52 = w48[9];
  w53 = w48[10];
  w54 = w48[11];
  w55 = w48[12];
  /* #210: output[1][4] = @45 */
  if (res[1]) res[1][4] = w45;
  /* #211: output[1][5] = @46 */
  if (res[1]) res[1][5] = w46;
  /* #212: output[1][6] = @43 */
  if (res[1]) res[1][6] = w43;
  /* #213: output[1][7] = @16 */
  if (res[1]) res[1][7] = w16;
  /* #214: output[1][8] = @17 */
  if (res[1]) res[1][8] = w17;
  /* #215: output[1][9] = @18 */
  if (res[1]) res[1][9] = w18;
  /* #216: @28 = (@32/@8) */
  for (i=0, rr=w28, cr=w32; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #217: {@18, @17, @16, @43} = vertsplit(@28) */
  w18 = w28[0];
  w17 = w28[1];
  w16 = w28[2];
  w43 = w28[3];
  /* #218: @18 = (@18+@47) */
  w18 += w47;
  /* #219: output[1][10] = @18 */
  if (res[1]) res[1][10] = w18;
  /* #220: @50 = (@50-@17) */
  w50 -= w17;
  /* #221: output[1][11] = @50 */
  if (res[1]) res[1][11] = w50;
  /* #222: @51 = (@51-@16) */
  w51 -= w16;
  /* #223: output[1][12] = @51 */
  if (res[1]) res[1][12] = w51;
  /* #224: @52 = (@52-@43) */
  w52 -= w43;
  /* #225: output[1][13] = @52 */
  if (res[1]) res[1][13] = w52;
  /* #226: output[1][14] = @53 */
  if (res[1]) res[1][14] = w53;
  /* #227: output[1][15] = @54 */
  if (res[1]) res[1][15] = w54;
  /* #228: output[1][16] = @55 */
  if (res[1]) res[1][16] = w55;
  /* #229: @56 = zeros(17x17,41nz) */
  casadi_clear(w56, 41);
  /* #230: @57 = ones(17x1,9nz) */
  casadi_fill(w57, 9, 1.);
  /* #231: {@55, NULL, NULL, NULL, @54, NULL, NULL, NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@57) */
  w55 = w57[0];
  w54 = w57[1];
  w53 = w57[5];
  /* #232: @58 = 00 */
  /* #233: @52 = vertcat(@55, @58, @58, @58) */
  rr=(&w52);
  *rr++ = w55;
  /* #234: @52 = @52' */
  /* #235: @59 = mac(@52,@29,@26) */
  casadi_copy(w26, 4, w59);
  casadi_mtimes((&w52), casadi_s2, w29, casadi_s1, w59, casadi_s0, w, 0);
  /* #236: @59 = @59' */
  /* #237: @60 = mac(@52,@38,@26) */
  casadi_copy(w26, 4, w60);
  casadi_mtimes((&w52), casadi_s2, w38, casadi_s1, w60, casadi_s0, w, 0);
  /* #238: @60 = @60' */
  /* #239: @59 = (@59+@60) */
  for (i=0, rr=w59, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #240: {@52, @55, @43, @51} = vertsplit(@59) */
  w52 = w59[0];
  w55 = w59[1];
  w43 = w59[2];
  w51 = w59[3];
  /* #241: @16 = vertcat(@53, @58, @58, @58) */
  rr=(&w16);
  *rr++ = w53;
  /* #242: @16 = (@16/@8) */
  w16 /= w08;
  /* #243: @59 = dense(@16) */
  casadi_densify((&w16), casadi_s3, w59, 0);
  /* #244: @16 = project(@31) */
  casadi_sparsify(w31, (&w16), casadi_s3, 0);
  /* #245: @53 = sparsity_cast(@53) */
  /* #246: @50 = dot(@16, @53) */
  w50 = casadi_dot(1, (&w16), (&w53));
  /* #247: @50 = (@50/@8) */
  w50 /= w08;
  /* #248: @60 = (@27*@50) */
  for (i=0, rr=w60, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #249: @59 = (@59-@60) */
  for (i=0, rr=w59, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #250: {@16, @17, @18, @47} = vertsplit(@59) */
  w16 = w59[0];
  w17 = w59[1];
  w18 = w59[2];
  w47 = w59[3];
  /* #251: @46 = (@4*@16) */
  w46  = (w04*w16);
  /* #252: @45 = (@5*@17) */
  w45  = (w05*w17);
  /* #253: @46 = (@46-@45) */
  w46 -= w45;
  /* #254: @45 = (@6*@18) */
  w45  = (w06*w18);
  /* #255: @46 = (@46-@45) */
  w46 -= w45;
  /* #256: @45 = (@7*@47) */
  w45  = (w07*w47);
  /* #257: @46 = (@46-@45) */
  w46 -= w45;
  /* #258: @45 = (@5*@16) */
  w45  = (w05*w16);
  /* #259: @61 = (@4*@17) */
  w61  = (w04*w17);
  /* #260: @45 = (@45+@61) */
  w45 += w61;
  /* #261: @61 = (@7*@18) */
  w61  = (w07*w18);
  /* #262: @45 = (@45+@61) */
  w45 += w61;
  /* #263: @61 = (@6*@47) */
  w61  = (w06*w47);
  /* #264: @45 = (@45-@61) */
  w45 -= w61;
  /* #265: @61 = (@6*@16) */
  w61  = (w06*w16);
  /* #266: @62 = (@7*@17) */
  w62  = (w07*w17);
  /* #267: @61 = (@61-@62) */
  w61 -= w62;
  /* #268: @62 = (@4*@18) */
  w62  = (w04*w18);
  /* #269: @61 = (@61+@62) */
  w61 += w62;
  /* #270: @62 = (@5*@47) */
  w62  = (w05*w47);
  /* #271: @61 = (@61+@62) */
  w61 += w62;
  /* #272: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #273: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #274: @16 = (@16+@17) */
  w16 += w17;
  /* #275: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #276: @16 = (@16-@18) */
  w16 -= w18;
  /* #277: @47 = (@4*@47) */
  w47  = (w04*w47);
  /* #278: @16 = (@16+@47) */
  w16 += w47;
  /* #279: @60 = vertcat(@46, @45, @61, @16) */
  rr=w60;
  *rr++ = w46;
  *rr++ = w45;
  *rr++ = w61;
  *rr++ = w16;
  /* #280: @63 = (-@60) */
  for (i=0, rr=w63, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #281: @63 = (@13?@63:0) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #282: @60 = (@12?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #283: @63 = (@63+@60) */
  for (i=0, rr=w63, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #284: @25 = @63[1:4] */
  for (rr=w25, cs=w63+1; cs!=w63+4; cs+=1) *rr++ = *cs;
  /* #285: @46 = dot(@20, @25) */
  w46 = casadi_dot(3, w20, w25);
  /* #286: @46 = (@46/@14) */
  w46 /= w14;
  /* #287: @45 = (@46/@11) */
  w45  = (w46/w11);
  /* #288: @61 = (@3/@11) */
  w61  = (w03/w11);
  /* #289: @16 = (2.*@14) */
  w16 = (2.* w14 );
  /* #290: @47 = (@16*@46) */
  w47  = (w16*w46);
  /* #291: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #292: @18 = @63[0] */
  for (rr=(&w18), cs=w63+0; cs!=w63+1; cs+=1) *rr++ = *cs;
  /* #293: @17 = (@15*@18) */
  w17  = (w15*w18);
  /* #294: @47 = (@47+@17) */
  w47 += w17;
  /* #295: @17 = (@61*@47) */
  w17  = (w61*w47);
  /* #296: @45 = (@45-@17) */
  w45 -= w17;
  /* #297: @45 = (@0*@45) */
  w45  = (w00*w45);
  /* #298: @41 = (2.*@25) */
  for (i=0, rr=w41, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #299: @22 = (@9*@41) */
  for (i=0, rr=w22, cs=w41; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #300: @17 = (@10*@46) */
  w17  = (w10*w46);
  /* #301: @62 = (@3*@18) */
  w62  = (w03*w18);
  /* #302: @17 = (@17-@62) */
  w17 -= w62;
  /* #303: @42 = (@34*@17) */
  for (i=0, rr=w42, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #304: @22 = (@22+@42) */
  for (i=0, rr=w22, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #305: @22 = (@22/@14) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w14;
  /* #306: @42 = (@35*@46) */
  for (i=0, rr=w42, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #307: @22 = (@22-@42) */
  for (i=0, rr=w22, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  /* #308: @42 = @22' */
  casadi_copy(w22, 3, w42);
  /* #309: @64 = mac(@42,@23,@1) */
  casadi_copy(w01, 3, w64);
  for (i=0, rr=w64; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #310: @64 = @64' */
  /* #311: @65 = mac(@42,@39,@1) */
  casadi_copy(w01, 3, w65);
  for (i=0, rr=w65; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #312: @65 = @65' */
  /* #313: @64 = (@64+@65) */
  for (i=0, rr=w64, cs=w65; i<3; ++i) (*rr++) += (*cs++);
  /* #314: @65 = (@64/@14) */
  for (i=0, rr=w65, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #315: @42 = (@40/@14) */
  for (i=0, rr=w42, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #316: @66 = (@42*@46) */
  for (i=0, rr=w66, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #317: @65 = (@65-@66) */
  for (i=0, rr=w65, cs=w66; i<3; ++i) (*rr++) -= (*cs++);
  /* #318: @62 = dot(@34, @65) */
  w62 = casadi_dot(3, w34, w65);
  /* #319: @67 = dot(@41, @40) */
  w67 = casadi_dot(3, w41, w40);
  /* #320: @62 = (@62+@67) */
  w62 += w67;
  /* #321: @67 = (@3*@62) */
  w67  = (w03*w62);
  /* #322: @45 = (@45+@67) */
  w45 += w67;
  /* #323: @45 = (-@45) */
  w45 = (- w45 );
  /* #324: @63 = @33; (@63[0] += @45) */
  casadi_copy(w33, 4, w63);
  for (rr=w63+0, cs=(&w45); rr!=w63+1; rr+=1) *rr += *cs++;
  /* #325: @45 = dot(@36, @64) */
  w45 = casadi_dot(3, w36, w64);
  /* #326: @22 = (@22/@14) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w14;
  /* #327: @64 = (@35/@14) */
  for (i=0, rr=w64, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #328: @41 = (@64*@46) */
  for (i=0, rr=w41, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #329: @22 = (@22-@41) */
  for (i=0, rr=w22, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #330: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #331: @67 = dot(@22, @37) */
  w67 = casadi_dot(3, w22, w37);
  /* #332: @45 = (@45+@67) */
  w45 += w67;
  /* #333: @18 = (@18/@11) */
  w18 /= w11;
  /* #334: @67 = (@10/@11) */
  w67  = (w10/w11);
  /* #335: @47 = (@67*@47) */
  w47  = (w67*w47);
  /* #336: @18 = (@18-@47) */
  w18 -= w47;
  /* #337: @18 = (@0*@18) */
  w18  = (w00*w18);
  /* #338: @62 = (@10*@62) */
  w62  = (w10*w62);
  /* #339: @18 = (@18+@62) */
  w18 += w62;
  /* #340: @45 = (@45+@18) */
  w45 += w18;
  /* #341: @45 = (@45/@14) */
  w45 /= w14;
  /* #342: @18 = (@2/@14) */
  w18  = (w02/w14);
  /* #343: @46 = (@18*@46) */
  w46  = (w18*w46);
  /* #344: @45 = (@45-@46) */
  w45 -= w46;
  /* #345: @22 = (@20*@45) */
  for (i=0, rr=w22, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w45);
  /* #346: @25 = (@2*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #347: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #348: @25 = (@40*@17) */
  for (i=0, rr=w25, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #349: @65 = (@9*@65) */
  for (i=0, rr=w65, cs=w65; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #350: @25 = (@25+@65) */
  for (i=0, rr=w25, cs=w65; i<3; ++i) (*rr++) += (*cs++);
  /* #351: @25 = (2.*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #352: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #353: (@63[1:4] += @22) */
  for (rr=w63+1, cs=w22; rr!=w63+4; rr+=1) *rr += *cs++;
  /* #354: @60 = (@12?@63:0) */
  for (i=0, rr=w60, cs=w63; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #355: @63 = (-@63) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) *rr++ = (- *cs++ );
  /* #356: @63 = (@13?@63:0) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #357: @60 = (@60+@63) */
  for (i=0, rr=w60, cs=w63; i<4; ++i) (*rr++) += (*cs++);
  /* #358: {@17, @45, @46, @62} = vertsplit(@60) */
  w17 = w60[0];
  w45 = w60[1];
  w46 = w60[2];
  w62 = w60[3];
  /* #359: @47 = (@7*@62) */
  w47  = (w07*w62);
  /* #360: @68 = (@6*@46) */
  w68  = (w06*w46);
  /* #361: @47 = (@47+@68) */
  w47 += w68;
  /* #362: @68 = (@5*@45) */
  w68  = (w05*w45);
  /* #363: @47 = (@47+@68) */
  w47 += w68;
  /* #364: @68 = (@4*@17) */
  w68  = (w04*w17);
  /* #365: @47 = (@47+@68) */
  w47 += w68;
  /* #366: @68 = (@6*@62) */
  w68  = (w06*w62);
  /* #367: @69 = (@7*@46) */
  w69  = (w07*w46);
  /* #368: @68 = (@68-@69) */
  w68 -= w69;
  /* #369: @69 = (@4*@45) */
  w69  = (w04*w45);
  /* #370: @68 = (@68+@69) */
  w68 += w69;
  /* #371: @69 = (@5*@17) */
  w69  = (w05*w17);
  /* #372: @68 = (@68-@69) */
  w68 -= w69;
  /* #373: @69 = (@4*@46) */
  w69  = (w04*w46);
  /* #374: @70 = (@5*@62) */
  w70  = (w05*w62);
  /* #375: @69 = (@69-@70) */
  w69 -= w70;
  /* #376: @70 = (@7*@45) */
  w70  = (w07*w45);
  /* #377: @69 = (@69+@70) */
  w69 += w70;
  /* #378: @70 = (@6*@17) */
  w70  = (w06*w17);
  /* #379: @69 = (@69-@70) */
  w69 -= w70;
  /* #380: @62 = (@4*@62) */
  w62  = (w04*w62);
  /* #381: @46 = (@5*@46) */
  w46  = (w05*w46);
  /* #382: @62 = (@62+@46) */
  w62 += w46;
  /* #383: @45 = (@6*@45) */
  w45  = (w06*w45);
  /* #384: @62 = (@62-@45) */
  w62 -= w45;
  /* #385: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #386: @62 = (@62-@17) */
  w62 -= w17;
  /* #387: @60 = vertcat(@47, @68, @69, @62) */
  rr=w60;
  *rr++ = w47;
  *rr++ = w68;
  *rr++ = w69;
  *rr++ = w62;
  /* #388: @47 = dot(@30, @60) */
  w47 = casadi_dot(4, w30, w60);
  /* #389: @59 = (@59/@8) */
  for (i=0, rr=w59; i<4; ++i) (*rr++) /= w08;
  /* #390: @63 = (@27/@8) */
  for (i=0, rr=w63, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #391: @71 = (@63*@50) */
  for (i=0, rr=w71, cr=w63; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #392: @59 = (@59-@71) */
  for (i=0, rr=w59, cs=w71; i<4; ++i) (*rr++) -= (*cs++);
  /* #393: @59 = (-@59) */
  for (i=0, rr=w59, cs=w59; i<4; ++i) *rr++ = (- *cs++ );
  /* #394: @68 = dot(@59, @32) */
  w68 = casadi_dot(4, w59, w32);
  /* #395: @47 = (@47+@68) */
  w47 += w68;
  /* #396: @47 = (@47/@8) */
  w47 /= w08;
  /* #397: @68 = (@44/@8) */
  w68  = (w44/w08);
  /* #398: @69 = (@68*@50) */
  w69  = (w68*w50);
  /* #399: @47 = (@47-@69) */
  w47 -= w69;
  /* #400: @59 = (@31*@47) */
  for (i=0, rr=w59, cr=w31; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #401: @53 = (@44*@53) */
  w53  = (w44*w53);
  /* #402: @71 = dense(@53) */
  casadi_densify((&w53), casadi_s3, w71, 0);
  /* #403: @59 = (@59+@71) */
  for (i=0, rr=w59, cs=w71; i<4; ++i) (*rr++) += (*cs++);
  /* #404: @48 = @21; (@48[6:10] += @59) */
  casadi_copy(w21, 13, w48);
  for (rr=w48+6, cs=w59; rr!=w48+10; rr+=1) *rr += *cs++;
  /* #405: @54 = sparsity_cast(@54) */
  /* #406: @54 = (-@54) */
  w54 = (- w54 );
  /* #407: @54 = @54' */
  /* #408: @22 = mac(@54,@24,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w54), casadi_s6, w24, casadi_s5, w22, casadi_s4, w, 0);
  /* #409: @22 = @22' */
  /* #410: @25 = mac(@54,@49,@1) */
  casadi_copy(w01, 3, w25);
  casadi_mtimes((&w54), casadi_s6, w49, casadi_s5, w25, casadi_s4, w, 0);
  /* #411: @25 = @25' */
  /* #412: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #413: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #414: (@48[:3] += @22) */
  for (rr=w48+0, cs=w22; rr!=w48+3; rr+=1) *rr += *cs++;
  /* #415: {@54, @53, @47, @69, @62, @17, @45, @46, @70, @72, @73, @74, @75} = vertsplit(@48) */
  w54 = w48[0];
  w53 = w48[1];
  w47 = w48[2];
  w69 = w48[3];
  w62 = w48[4];
  w17 = w48[5];
  w45 = w48[6];
  w46 = w48[7];
  w70 = w48[8];
  w72 = w48[9];
  w73 = w48[10];
  w74 = w48[11];
  w75 = w48[12];
  /* #416: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #417: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #418: @59 = (@28*@50) */
  for (i=0, rr=w59, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #419: @60 = (@60-@59) */
  for (i=0, rr=w60, cs=w59; i<4; ++i) (*rr++) -= (*cs++);
  /* #420: {@50, @76, @77, @78} = vertsplit(@60) */
  w50 = w60[0];
  w76 = w60[1];
  w77 = w60[2];
  w78 = w60[3];
  /* #421: @50 = (@50+@45) */
  w50 += w45;
  /* #422: @46 = (@46-@76) */
  w46 -= w76;
  /* #423: @70 = (@70-@77) */
  w70 -= w77;
  /* #424: @72 = (@72-@78) */
  w72 -= w78;
  /* #425: @19 = vertcat(@52, @55, @43, @51, @54, @53, @47, @69, @62, @17, @50, @46, @70, @72, @73, @74, @75) */
  rr=w19;
  *rr++ = w52;
  *rr++ = w55;
  *rr++ = w43;
  *rr++ = w51;
  *rr++ = w54;
  *rr++ = w53;
  *rr++ = w47;
  *rr++ = w69;
  *rr++ = w62;
  *rr++ = w17;
  *rr++ = w50;
  *rr++ = w46;
  *rr++ = w70;
  *rr++ = w72;
  *rr++ = w73;
  *rr++ = w74;
  *rr++ = w75;
  /* #426: @79 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w79, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #427: (@56[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @79) */
  for (cii=casadi_s8, rr=w56, cs=w79; cii!=casadi_s8+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #428: (@56[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @79) */
  for (cii=casadi_s9, rr=w56, cs=w79; cii!=casadi_s9+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #429: @22 = ones(17x1,3nz) */
  casadi_fill(w22, 3, 1.);
  /* #430: {NULL, @52, NULL, NULL, NULL, @55, NULL, NULL, NULL, NULL, NULL, @43, NULL, NULL, NULL, NULL, NULL} = vertsplit(@22) */
  w52 = w22[0];
  w55 = w22[1];
  w43 = w22[2];
  /* #431: @51 = vertcat(@58, @52, @58, @58) */
  rr=(&w51);
  *rr++ = w52;
  /* #432: @51 = @51' */
  /* #433: @60 = mac(@51,@29,@26) */
  casadi_copy(w26, 4, w60);
  casadi_mtimes((&w51), casadi_s10, w29, casadi_s1, w60, casadi_s0, w, 0);
  /* #434: @60 = @60' */
  /* #435: @59 = mac(@51,@38,@26) */
  casadi_copy(w26, 4, w59);
  casadi_mtimes((&w51), casadi_s10, w38, casadi_s1, w59, casadi_s0, w, 0);
  /* #436: @59 = @59' */
  /* #437: @60 = (@60+@59) */
  for (i=0, rr=w60, cs=w59; i<4; ++i) (*rr++) += (*cs++);
  /* #438: {@51, @52, @54, @53} = vertsplit(@60) */
  w51 = w60[0];
  w52 = w60[1];
  w54 = w60[2];
  w53 = w60[3];
  /* #439: @47 = (-@43) */
  w47 = (- w43 );
  /* #440: @69 = vertcat(@58, @47, @58, @58) */
  rr=(&w69);
  *rr++ = w47;
  /* #441: @69 = (@69/@8) */
  w69 /= w08;
  /* #442: @60 = dense(@69) */
  casadi_densify((&w69), casadi_s11, w60, 0);
  /* #443: @69 = project(@31) */
  casadi_sparsify(w31, (&w69), casadi_s11, 0);
  /* #444: @43 = sparsity_cast(@43) */
  /* #445: @47 = dot(@69, @43) */
  w47 = casadi_dot(1, (&w69), (&w43));
  /* #446: @47 = (@47/@8) */
  w47 /= w08;
  /* #447: @59 = (@27*@47) */
  for (i=0, rr=w59, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #448: @60 = (@60-@59) */
  for (i=0, rr=w60, cs=w59; i<4; ++i) (*rr++) -= (*cs++);
  /* #449: {@69, @62, @17, @50} = vertsplit(@60) */
  w69 = w60[0];
  w62 = w60[1];
  w17 = w60[2];
  w50 = w60[3];
  /* #450: @46 = (@4*@69) */
  w46  = (w04*w69);
  /* #451: @70 = (@5*@62) */
  w70  = (w05*w62);
  /* #452: @46 = (@46-@70) */
  w46 -= w70;
  /* #453: @70 = (@6*@17) */
  w70  = (w06*w17);
  /* #454: @46 = (@46-@70) */
  w46 -= w70;
  /* #455: @70 = (@7*@50) */
  w70  = (w07*w50);
  /* #456: @46 = (@46-@70) */
  w46 -= w70;
  /* #457: @70 = (@5*@69) */
  w70  = (w05*w69);
  /* #458: @72 = (@4*@62) */
  w72  = (w04*w62);
  /* #459: @70 = (@70+@72) */
  w70 += w72;
  /* #460: @72 = (@7*@17) */
  w72  = (w07*w17);
  /* #461: @70 = (@70+@72) */
  w70 += w72;
  /* #462: @72 = (@6*@50) */
  w72  = (w06*w50);
  /* #463: @70 = (@70-@72) */
  w70 -= w72;
  /* #464: @72 = (@6*@69) */
  w72  = (w06*w69);
  /* #465: @73 = (@7*@62) */
  w73  = (w07*w62);
  /* #466: @72 = (@72-@73) */
  w72 -= w73;
  /* #467: @73 = (@4*@17) */
  w73  = (w04*w17);
  /* #468: @72 = (@72+@73) */
  w72 += w73;
  /* #469: @73 = (@5*@50) */
  w73  = (w05*w50);
  /* #470: @72 = (@72+@73) */
  w72 += w73;
  /* #471: @69 = (@7*@69) */
  w69  = (w07*w69);
  /* #472: @62 = (@6*@62) */
  w62  = (w06*w62);
  /* #473: @69 = (@69+@62) */
  w69 += w62;
  /* #474: @17 = (@5*@17) */
  w17  = (w05*w17);
  /* #475: @69 = (@69-@17) */
  w69 -= w17;
  /* #476: @50 = (@4*@50) */
  w50  = (w04*w50);
  /* #477: @69 = (@69+@50) */
  w69 += w50;
  /* #478: @59 = vertcat(@46, @70, @72, @69) */
  rr=w59;
  *rr++ = w46;
  *rr++ = w70;
  *rr++ = w72;
  *rr++ = w69;
  /* #479: @71 = (-@59) */
  for (i=0, rr=w71, cs=w59; i<4; ++i) *rr++ = (- *cs++ );
  /* #480: @71 = (@13?@71:0) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #481: @59 = (@12?@59:0) */
  for (i=0, rr=w59, cs=w59; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #482: @71 = (@71+@59) */
  for (i=0, rr=w71, cs=w59; i<4; ++i) (*rr++) += (*cs++);
  /* #483: @22 = @71[1:4] */
  for (rr=w22, cs=w71+1; cs!=w71+4; cs+=1) *rr++ = *cs;
  /* #484: @46 = dot(@20, @22) */
  w46 = casadi_dot(3, w20, w22);
  /* #485: @46 = (@46/@14) */
  w46 /= w14;
  /* #486: @70 = (@46/@11) */
  w70  = (w46/w11);
  /* #487: @72 = (@16*@46) */
  w72  = (w16*w46);
  /* #488: @69 = @71[0] */
  for (rr=(&w69), cs=w71+0; cs!=w71+1; cs+=1) *rr++ = *cs;
  /* #489: @50 = (@15*@69) */
  w50  = (w15*w69);
  /* #490: @72 = (@72+@50) */
  w72 += w50;
  /* #491: @50 = (@61*@72) */
  w50  = (w61*w72);
  /* #492: @70 = (@70-@50) */
  w70 -= w50;
  /* #493: @70 = (@0*@70) */
  w70  = (w00*w70);
  /* #494: @25 = (2.*@22) */
  for (i=0, rr=w25, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #495: @65 = (@9*@25) */
  for (i=0, rr=w65, cs=w25; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #496: @50 = (@10*@46) */
  w50  = (w10*w46);
  /* #497: @17 = (@3*@69) */
  w17  = (w03*w69);
  /* #498: @50 = (@50-@17) */
  w50 -= w17;
  /* #499: @41 = (@34*@50) */
  for (i=0, rr=w41, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w50);
  /* #500: @65 = (@65+@41) */
  for (i=0, rr=w65, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #501: @65 = (@65/@14) */
  for (i=0, rr=w65; i<3; ++i) (*rr++) /= w14;
  /* #502: @41 = (@35*@46) */
  for (i=0, rr=w41, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #503: @65 = (@65-@41) */
  for (i=0, rr=w65, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #504: @41 = @65' */
  casadi_copy(w65, 3, w41);
  /* #505: @66 = mac(@41,@23,@1) */
  casadi_copy(w01, 3, w66);
  for (i=0, rr=w66; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #506: @66 = @66' */
  /* #507: @80 = mac(@41,@39,@1) */
  casadi_copy(w01, 3, w80);
  for (i=0, rr=w80; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #508: @80 = @80' */
  /* #509: @66 = (@66+@80) */
  for (i=0, rr=w66, cs=w80; i<3; ++i) (*rr++) += (*cs++);
  /* #510: @80 = (@66/@14) */
  for (i=0, rr=w80, cr=w66; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #511: @41 = (@42*@46) */
  for (i=0, rr=w41, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #512: @80 = (@80-@41) */
  for (i=0, rr=w80, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #513: @17 = dot(@34, @80) */
  w17 = casadi_dot(3, w34, w80);
  /* #514: @62 = dot(@25, @40) */
  w62 = casadi_dot(3, w25, w40);
  /* #515: @17 = (@17+@62) */
  w17 += w62;
  /* #516: @62 = (@3*@17) */
  w62  = (w03*w17);
  /* #517: @70 = (@70+@62) */
  w70 += w62;
  /* #518: @70 = (-@70) */
  w70 = (- w70 );
  /* #519: @71 = @33; (@71[0] += @70) */
  casadi_copy(w33, 4, w71);
  for (rr=w71+0, cs=(&w70); rr!=w71+1; rr+=1) *rr += *cs++;
  /* #520: @70 = dot(@36, @66) */
  w70 = casadi_dot(3, w36, w66);
  /* #521: @65 = (@65/@14) */
  for (i=0, rr=w65; i<3; ++i) (*rr++) /= w14;
  /* #522: @66 = (@64*@46) */
  for (i=0, rr=w66, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #523: @65 = (@65-@66) */
  for (i=0, rr=w65, cs=w66; i<3; ++i) (*rr++) -= (*cs++);
  /* #524: @65 = (-@65) */
  for (i=0, rr=w65, cs=w65; i<3; ++i) *rr++ = (- *cs++ );
  /* #525: @62 = dot(@65, @37) */
  w62 = casadi_dot(3, w65, w37);
  /* #526: @70 = (@70+@62) */
  w70 += w62;
  /* #527: @69 = (@69/@11) */
  w69 /= w11;
  /* #528: @72 = (@67*@72) */
  w72  = (w67*w72);
  /* #529: @69 = (@69-@72) */
  w69 -= w72;
  /* #530: @69 = (@0*@69) */
  w69  = (w00*w69);
  /* #531: @17 = (@10*@17) */
  w17  = (w10*w17);
  /* #532: @69 = (@69+@17) */
  w69 += w17;
  /* #533: @70 = (@70+@69) */
  w70 += w69;
  /* #534: @70 = (@70/@14) */
  w70 /= w14;
  /* #535: @46 = (@18*@46) */
  w46  = (w18*w46);
  /* #536: @70 = (@70-@46) */
  w70 -= w46;
  /* #537: @65 = (@20*@70) */
  for (i=0, rr=w65, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w70);
  /* #538: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #539: @65 = (@65+@22) */
  for (i=0, rr=w65, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #540: @22 = (@40*@50) */
  for (i=0, rr=w22, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w50);
  /* #541: @80 = (@9*@80) */
  for (i=0, rr=w80, cs=w80; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #542: @22 = (@22+@80) */
  for (i=0, rr=w22, cs=w80; i<3; ++i) (*rr++) += (*cs++);
  /* #543: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #544: @65 = (@65+@22) */
  for (i=0, rr=w65, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #545: (@71[1:4] += @65) */
  for (rr=w71+1, cs=w65; rr!=w71+4; rr+=1) *rr += *cs++;
  /* #546: @59 = (@12?@71:0) */
  for (i=0, rr=w59, cs=w71; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #547: @71 = (-@71) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) *rr++ = (- *cs++ );
  /* #548: @71 = (@13?@71:0) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #549: @59 = (@59+@71) */
  for (i=0, rr=w59, cs=w71; i<4; ++i) (*rr++) += (*cs++);
  /* #550: {@50, @70, @46, @69} = vertsplit(@59) */
  w50 = w59[0];
  w70 = w59[1];
  w46 = w59[2];
  w69 = w59[3];
  /* #551: @17 = (@7*@69) */
  w17  = (w07*w69);
  /* #552: @72 = (@6*@46) */
  w72  = (w06*w46);
  /* #553: @17 = (@17+@72) */
  w17 += w72;
  /* #554: @72 = (@5*@70) */
  w72  = (w05*w70);
  /* #555: @17 = (@17+@72) */
  w17 += w72;
  /* #556: @72 = (@4*@50) */
  w72  = (w04*w50);
  /* #557: @17 = (@17+@72) */
  w17 += w72;
  /* #558: @72 = (@6*@69) */
  w72  = (w06*w69);
  /* #559: @62 = (@7*@46) */
  w62  = (w07*w46);
  /* #560: @72 = (@72-@62) */
  w72 -= w62;
  /* #561: @62 = (@4*@70) */
  w62  = (w04*w70);
  /* #562: @72 = (@72+@62) */
  w72 += w62;
  /* #563: @62 = (@5*@50) */
  w62  = (w05*w50);
  /* #564: @72 = (@72-@62) */
  w72 -= w62;
  /* #565: @62 = (@4*@46) */
  w62  = (w04*w46);
  /* #566: @73 = (@5*@69) */
  w73  = (w05*w69);
  /* #567: @62 = (@62-@73) */
  w62 -= w73;
  /* #568: @73 = (@7*@70) */
  w73  = (w07*w70);
  /* #569: @62 = (@62+@73) */
  w62 += w73;
  /* #570: @73 = (@6*@50) */
  w73  = (w06*w50);
  /* #571: @62 = (@62-@73) */
  w62 -= w73;
  /* #572: @69 = (@4*@69) */
  w69  = (w04*w69);
  /* #573: @46 = (@5*@46) */
  w46  = (w05*w46);
  /* #574: @69 = (@69+@46) */
  w69 += w46;
  /* #575: @70 = (@6*@70) */
  w70  = (w06*w70);
  /* #576: @69 = (@69-@70) */
  w69 -= w70;
  /* #577: @50 = (@7*@50) */
  w50  = (w07*w50);
  /* #578: @69 = (@69-@50) */
  w69 -= w50;
  /* #579: @59 = vertcat(@17, @72, @62, @69) */
  rr=w59;
  *rr++ = w17;
  *rr++ = w72;
  *rr++ = w62;
  *rr++ = w69;
  /* #580: @17 = dot(@30, @59) */
  w17 = casadi_dot(4, w30, w59);
  /* #581: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #582: @71 = (@63*@47) */
  for (i=0, rr=w71, cr=w63; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #583: @60 = (@60-@71) */
  for (i=0, rr=w60, cs=w71; i<4; ++i) (*rr++) -= (*cs++);
  /* #584: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #585: @72 = dot(@60, @32) */
  w72 = casadi_dot(4, w60, w32);
  /* #586: @17 = (@17+@72) */
  w17 += w72;
  /* #587: @17 = (@17/@8) */
  w17 /= w08;
  /* #588: @72 = (@68*@47) */
  w72  = (w68*w47);
  /* #589: @17 = (@17-@72) */
  w17 -= w72;
  /* #590: @60 = (@31*@17) */
  for (i=0, rr=w60, cr=w31; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #591: @43 = (@44*@43) */
  w43  = (w44*w43);
  /* #592: @71 = dense(@43) */
  casadi_densify((&w43), casadi_s11, w71, 0);
  /* #593: @60 = (@60+@71) */
  for (i=0, rr=w60, cs=w71; i<4; ++i) (*rr++) += (*cs++);
  /* #594: @48 = @21; (@48[6:10] += @60) */
  casadi_copy(w21, 13, w48);
  for (rr=w48+6, cs=w60; rr!=w48+10; rr+=1) *rr += *cs++;
  /* #595: @55 = sparsity_cast(@55) */
  /* #596: @55 = (-@55) */
  w55 = (- w55 );
  /* #597: @55 = @55' */
  /* #598: @65 = mac(@55,@24,@1) */
  casadi_copy(w01, 3, w65);
  casadi_mtimes((&w55), casadi_s12, w24, casadi_s5, w65, casadi_s4, w, 0);
  /* #599: @65 = @65' */
  /* #600: @22 = mac(@55,@49,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w55), casadi_s12, w49, casadi_s5, w22, casadi_s4, w, 0);
  /* #601: @22 = @22' */
  /* #602: @65 = (@65+@22) */
  for (i=0, rr=w65, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #603: @65 = (-@65) */
  for (i=0, rr=w65, cs=w65; i<3; ++i) *rr++ = (- *cs++ );
  /* #604: (@48[:3] += @65) */
  for (rr=w48+0, cs=w65; rr!=w48+3; rr+=1) *rr += *cs++;
  /* #605: {@55, @43, @17, @72, @62, @69, @50, @70, @46, @73, @74, @75, @78} = vertsplit(@48) */
  w55 = w48[0];
  w43 = w48[1];
  w17 = w48[2];
  w72 = w48[3];
  w62 = w48[4];
  w69 = w48[5];
  w50 = w48[6];
  w70 = w48[7];
  w46 = w48[8];
  w73 = w48[9];
  w74 = w48[10];
  w75 = w48[11];
  w78 = w48[12];
  /* #606: @59 = (@59/@8) */
  for (i=0, rr=w59; i<4; ++i) (*rr++) /= w08;
  /* #607: @60 = (@28*@47) */
  for (i=0, rr=w60, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #608: @59 = (@59-@60) */
  for (i=0, rr=w59, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #609: {@47, @77, @76, @45} = vertsplit(@59) */
  w47 = w59[0];
  w77 = w59[1];
  w76 = w59[2];
  w45 = w59[3];
  /* #610: @47 = (@47+@50) */
  w47 += w50;
  /* #611: @70 = (@70-@77) */
  w70 -= w77;
  /* #612: @46 = (@46-@76) */
  w46 -= w76;
  /* #613: @73 = (@73-@45) */
  w73 -= w45;
  /* #614: @19 = vertcat(@51, @52, @54, @53, @55, @43, @17, @72, @62, @69, @47, @70, @46, @73, @74, @75, @78) */
  rr=w19;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w54;
  *rr++ = w53;
  *rr++ = w55;
  *rr++ = w43;
  *rr++ = w17;
  *rr++ = w72;
  *rr++ = w62;
  *rr++ = w69;
  *rr++ = w47;
  *rr++ = w70;
  *rr++ = w46;
  *rr++ = w73;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w78;
  /* #615: @79 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w79, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #616: (@56[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @79) */
  for (cii=casadi_s13, rr=w56, cs=w79; cii!=casadi_s13+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #617: (@56[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @79) */
  for (cii=casadi_s14, rr=w56, cs=w79; cii!=casadi_s14+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #618: @65 = ones(17x1,3nz) */
  casadi_fill(w65, 3, 1.);
  /* #619: {NULL, NULL, @51, NULL, NULL, NULL, @52, NULL, NULL, NULL, NULL, NULL, @54, NULL, NULL, NULL, NULL} = vertsplit(@65) */
  w51 = w65[0];
  w52 = w65[1];
  w54 = w65[2];
  /* #620: @53 = vertcat(@58, @58, @51, @58) */
  rr=(&w53);
  *rr++ = w51;
  /* #621: @53 = @53' */
  /* #622: @59 = mac(@53,@29,@26) */
  casadi_copy(w26, 4, w59);
  casadi_mtimes((&w53), casadi_s15, w29, casadi_s1, w59, casadi_s0, w, 0);
  /* #623: @59 = @59' */
  /* #624: @60 = mac(@53,@38,@26) */
  casadi_copy(w26, 4, w60);
  casadi_mtimes((&w53), casadi_s15, w38, casadi_s1, w60, casadi_s0, w, 0);
  /* #625: @60 = @60' */
  /* #626: @59 = (@59+@60) */
  for (i=0, rr=w59, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #627: {@53, @51, @55, @43} = vertsplit(@59) */
  w53 = w59[0];
  w51 = w59[1];
  w55 = w59[2];
  w43 = w59[3];
  /* #628: @17 = (-@54) */
  w17 = (- w54 );
  /* #629: @72 = vertcat(@58, @58, @17, @58) */
  rr=(&w72);
  *rr++ = w17;
  /* #630: @72 = (@72/@8) */
  w72 /= w08;
  /* #631: @59 = dense(@72) */
  casadi_densify((&w72), casadi_s16, w59, 0);
  /* #632: @72 = project(@31) */
  casadi_sparsify(w31, (&w72), casadi_s16, 0);
  /* #633: @54 = sparsity_cast(@54) */
  /* #634: @17 = dot(@72, @54) */
  w17 = casadi_dot(1, (&w72), (&w54));
  /* #635: @17 = (@17/@8) */
  w17 /= w08;
  /* #636: @60 = (@27*@17) */
  for (i=0, rr=w60, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #637: @59 = (@59-@60) */
  for (i=0, rr=w59, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #638: {@72, @62, @69, @47} = vertsplit(@59) */
  w72 = w59[0];
  w62 = w59[1];
  w69 = w59[2];
  w47 = w59[3];
  /* #639: @70 = (@4*@72) */
  w70  = (w04*w72);
  /* #640: @46 = (@5*@62) */
  w46  = (w05*w62);
  /* #641: @70 = (@70-@46) */
  w70 -= w46;
  /* #642: @46 = (@6*@69) */
  w46  = (w06*w69);
  /* #643: @70 = (@70-@46) */
  w70 -= w46;
  /* #644: @46 = (@7*@47) */
  w46  = (w07*w47);
  /* #645: @70 = (@70-@46) */
  w70 -= w46;
  /* #646: @46 = (@5*@72) */
  w46  = (w05*w72);
  /* #647: @73 = (@4*@62) */
  w73  = (w04*w62);
  /* #648: @46 = (@46+@73) */
  w46 += w73;
  /* #649: @73 = (@7*@69) */
  w73  = (w07*w69);
  /* #650: @46 = (@46+@73) */
  w46 += w73;
  /* #651: @73 = (@6*@47) */
  w73  = (w06*w47);
  /* #652: @46 = (@46-@73) */
  w46 -= w73;
  /* #653: @73 = (@6*@72) */
  w73  = (w06*w72);
  /* #654: @74 = (@7*@62) */
  w74  = (w07*w62);
  /* #655: @73 = (@73-@74) */
  w73 -= w74;
  /* #656: @74 = (@4*@69) */
  w74  = (w04*w69);
  /* #657: @73 = (@73+@74) */
  w73 += w74;
  /* #658: @74 = (@5*@47) */
  w74  = (w05*w47);
  /* #659: @73 = (@73+@74) */
  w73 += w74;
  /* #660: @72 = (@7*@72) */
  w72  = (w07*w72);
  /* #661: @62 = (@6*@62) */
  w62  = (w06*w62);
  /* #662: @72 = (@72+@62) */
  w72 += w62;
  /* #663: @69 = (@5*@69) */
  w69  = (w05*w69);
  /* #664: @72 = (@72-@69) */
  w72 -= w69;
  /* #665: @47 = (@4*@47) */
  w47  = (w04*w47);
  /* #666: @72 = (@72+@47) */
  w72 += w47;
  /* #667: @60 = vertcat(@70, @46, @73, @72) */
  rr=w60;
  *rr++ = w70;
  *rr++ = w46;
  *rr++ = w73;
  *rr++ = w72;
  /* #668: @71 = (-@60) */
  for (i=0, rr=w71, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #669: @71 = (@13?@71:0) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #670: @60 = (@12?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #671: @71 = (@71+@60) */
  for (i=0, rr=w71, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #672: @65 = @71[1:4] */
  for (rr=w65, cs=w71+1; cs!=w71+4; cs+=1) *rr++ = *cs;
  /* #673: @70 = dot(@20, @65) */
  w70 = casadi_dot(3, w20, w65);
  /* #674: @70 = (@70/@14) */
  w70 /= w14;
  /* #675: @46 = (@70/@11) */
  w46  = (w70/w11);
  /* #676: @73 = (@16*@70) */
  w73  = (w16*w70);
  /* #677: @72 = @71[0] */
  for (rr=(&w72), cs=w71+0; cs!=w71+1; cs+=1) *rr++ = *cs;
  /* #678: @47 = (@15*@72) */
  w47  = (w15*w72);
  /* #679: @73 = (@73+@47) */
  w73 += w47;
  /* #680: @47 = (@61*@73) */
  w47  = (w61*w73);
  /* #681: @46 = (@46-@47) */
  w46 -= w47;
  /* #682: @46 = (@0*@46) */
  w46  = (w00*w46);
  /* #683: @22 = (2.*@65) */
  for (i=0, rr=w22, cs=w65; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #684: @80 = (@9*@22) */
  for (i=0, rr=w80, cs=w22; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #685: @47 = (@10*@70) */
  w47  = (w10*w70);
  /* #686: @69 = (@3*@72) */
  w69  = (w03*w72);
  /* #687: @47 = (@47-@69) */
  w47 -= w69;
  /* #688: @66 = (@34*@47) */
  for (i=0, rr=w66, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #689: @80 = (@80+@66) */
  for (i=0, rr=w80, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #690: @80 = (@80/@14) */
  for (i=0, rr=w80; i<3; ++i) (*rr++) /= w14;
  /* #691: @66 = (@35*@70) */
  for (i=0, rr=w66, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w70);
  /* #692: @80 = (@80-@66) */
  for (i=0, rr=w80, cs=w66; i<3; ++i) (*rr++) -= (*cs++);
  /* #693: @66 = @80' */
  casadi_copy(w80, 3, w66);
  /* #694: @25 = mac(@66,@23,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w66+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #695: @25 = @25' */
  /* #696: @41 = mac(@66,@39,@1) */
  casadi_copy(w01, 3, w41);
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w66+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #697: @41 = @41' */
  /* #698: @25 = (@25+@41) */
  for (i=0, rr=w25, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #699: @41 = (@25/@14) */
  for (i=0, rr=w41, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #700: @66 = (@42*@70) */
  for (i=0, rr=w66, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w70);
  /* #701: @41 = (@41-@66) */
  for (i=0, rr=w41, cs=w66; i<3; ++i) (*rr++) -= (*cs++);
  /* #702: @69 = dot(@34, @41) */
  w69 = casadi_dot(3, w34, w41);
  /* #703: @62 = dot(@22, @40) */
  w62 = casadi_dot(3, w22, w40);
  /* #704: @69 = (@69+@62) */
  w69 += w62;
  /* #705: @62 = (@3*@69) */
  w62  = (w03*w69);
  /* #706: @46 = (@46+@62) */
  w46 += w62;
  /* #707: @46 = (-@46) */
  w46 = (- w46 );
  /* #708: @71 = @33; (@71[0] += @46) */
  casadi_copy(w33, 4, w71);
  for (rr=w71+0, cs=(&w46); rr!=w71+1; rr+=1) *rr += *cs++;
  /* #709: @46 = dot(@36, @25) */
  w46 = casadi_dot(3, w36, w25);
  /* #710: @80 = (@80/@14) */
  for (i=0, rr=w80; i<3; ++i) (*rr++) /= w14;
  /* #711: @25 = (@64*@70) */
  for (i=0, rr=w25, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)*w70);
  /* #712: @80 = (@80-@25) */
  for (i=0, rr=w80, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #713: @80 = (-@80) */
  for (i=0, rr=w80, cs=w80; i<3; ++i) *rr++ = (- *cs++ );
  /* #714: @62 = dot(@80, @37) */
  w62 = casadi_dot(3, w80, w37);
  /* #715: @46 = (@46+@62) */
  w46 += w62;
  /* #716: @72 = (@72/@11) */
  w72 /= w11;
  /* #717: @73 = (@67*@73) */
  w73  = (w67*w73);
  /* #718: @72 = (@72-@73) */
  w72 -= w73;
  /* #719: @72 = (@0*@72) */
  w72  = (w00*w72);
  /* #720: @69 = (@10*@69) */
  w69  = (w10*w69);
  /* #721: @72 = (@72+@69) */
  w72 += w69;
  /* #722: @46 = (@46+@72) */
  w46 += w72;
  /* #723: @46 = (@46/@14) */
  w46 /= w14;
  /* #724: @70 = (@18*@70) */
  w70  = (w18*w70);
  /* #725: @46 = (@46-@70) */
  w46 -= w70;
  /* #726: @80 = (@20*@46) */
  for (i=0, rr=w80, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #727: @65 = (@2*@65) */
  for (i=0, rr=w65, cs=w65; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #728: @80 = (@80+@65) */
  for (i=0, rr=w80, cs=w65; i<3; ++i) (*rr++) += (*cs++);
  /* #729: @65 = (@40*@47) */
  for (i=0, rr=w65, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #730: @41 = (@9*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #731: @65 = (@65+@41) */
  for (i=0, rr=w65, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #732: @65 = (2.*@65) */
  for (i=0, rr=w65, cs=w65; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #733: @80 = (@80+@65) */
  for (i=0, rr=w80, cs=w65; i<3; ++i) (*rr++) += (*cs++);
  /* #734: (@71[1:4] += @80) */
  for (rr=w71+1, cs=w80; rr!=w71+4; rr+=1) *rr += *cs++;
  /* #735: @60 = (@12?@71:0) */
  for (i=0, rr=w60, cs=w71; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #736: @71 = (-@71) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) *rr++ = (- *cs++ );
  /* #737: @71 = (@13?@71:0) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #738: @60 = (@60+@71) */
  for (i=0, rr=w60, cs=w71; i<4; ++i) (*rr++) += (*cs++);
  /* #739: {@47, @46, @70, @72} = vertsplit(@60) */
  w47 = w60[0];
  w46 = w60[1];
  w70 = w60[2];
  w72 = w60[3];
  /* #740: @69 = (@7*@72) */
  w69  = (w07*w72);
  /* #741: @73 = (@6*@70) */
  w73  = (w06*w70);
  /* #742: @69 = (@69+@73) */
  w69 += w73;
  /* #743: @73 = (@5*@46) */
  w73  = (w05*w46);
  /* #744: @69 = (@69+@73) */
  w69 += w73;
  /* #745: @73 = (@4*@47) */
  w73  = (w04*w47);
  /* #746: @69 = (@69+@73) */
  w69 += w73;
  /* #747: @73 = (@6*@72) */
  w73  = (w06*w72);
  /* #748: @62 = (@7*@70) */
  w62  = (w07*w70);
  /* #749: @73 = (@73-@62) */
  w73 -= w62;
  /* #750: @62 = (@4*@46) */
  w62  = (w04*w46);
  /* #751: @73 = (@73+@62) */
  w73 += w62;
  /* #752: @62 = (@5*@47) */
  w62  = (w05*w47);
  /* #753: @73 = (@73-@62) */
  w73 -= w62;
  /* #754: @62 = (@4*@70) */
  w62  = (w04*w70);
  /* #755: @74 = (@5*@72) */
  w74  = (w05*w72);
  /* #756: @62 = (@62-@74) */
  w62 -= w74;
  /* #757: @74 = (@7*@46) */
  w74  = (w07*w46);
  /* #758: @62 = (@62+@74) */
  w62 += w74;
  /* #759: @74 = (@6*@47) */
  w74  = (w06*w47);
  /* #760: @62 = (@62-@74) */
  w62 -= w74;
  /* #761: @72 = (@4*@72) */
  w72  = (w04*w72);
  /* #762: @70 = (@5*@70) */
  w70  = (w05*w70);
  /* #763: @72 = (@72+@70) */
  w72 += w70;
  /* #764: @46 = (@6*@46) */
  w46  = (w06*w46);
  /* #765: @72 = (@72-@46) */
  w72 -= w46;
  /* #766: @47 = (@7*@47) */
  w47  = (w07*w47);
  /* #767: @72 = (@72-@47) */
  w72 -= w47;
  /* #768: @60 = vertcat(@69, @73, @62, @72) */
  rr=w60;
  *rr++ = w69;
  *rr++ = w73;
  *rr++ = w62;
  *rr++ = w72;
  /* #769: @69 = dot(@30, @60) */
  w69 = casadi_dot(4, w30, w60);
  /* #770: @59 = (@59/@8) */
  for (i=0, rr=w59; i<4; ++i) (*rr++) /= w08;
  /* #771: @71 = (@63*@17) */
  for (i=0, rr=w71, cr=w63; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #772: @59 = (@59-@71) */
  for (i=0, rr=w59, cs=w71; i<4; ++i) (*rr++) -= (*cs++);
  /* #773: @59 = (-@59) */
  for (i=0, rr=w59, cs=w59; i<4; ++i) *rr++ = (- *cs++ );
  /* #774: @73 = dot(@59, @32) */
  w73 = casadi_dot(4, w59, w32);
  /* #775: @69 = (@69+@73) */
  w69 += w73;
  /* #776: @69 = (@69/@8) */
  w69 /= w08;
  /* #777: @73 = (@68*@17) */
  w73  = (w68*w17);
  /* #778: @69 = (@69-@73) */
  w69 -= w73;
  /* #779: @59 = (@31*@69) */
  for (i=0, rr=w59, cr=w31; i<4; ++i) (*rr++)  = ((*cr++)*w69);
  /* #780: @54 = (@44*@54) */
  w54  = (w44*w54);
  /* #781: @71 = dense(@54) */
  casadi_densify((&w54), casadi_s16, w71, 0);
  /* #782: @59 = (@59+@71) */
  for (i=0, rr=w59, cs=w71; i<4; ++i) (*rr++) += (*cs++);
  /* #783: @48 = @21; (@48[6:10] += @59) */
  casadi_copy(w21, 13, w48);
  for (rr=w48+6, cs=w59; rr!=w48+10; rr+=1) *rr += *cs++;
  /* #784: @52 = sparsity_cast(@52) */
  /* #785: @52 = (-@52) */
  w52 = (- w52 );
  /* #786: @52 = @52' */
  /* #787: @80 = mac(@52,@24,@1) */
  casadi_copy(w01, 3, w80);
  casadi_mtimes((&w52), casadi_s17, w24, casadi_s5, w80, casadi_s4, w, 0);
  /* #788: @80 = @80' */
  /* #789: @65 = mac(@52,@49,@1) */
  casadi_copy(w01, 3, w65);
  casadi_mtimes((&w52), casadi_s17, w49, casadi_s5, w65, casadi_s4, w, 0);
  /* #790: @65 = @65' */
  /* #791: @80 = (@80+@65) */
  for (i=0, rr=w80, cs=w65; i<3; ++i) (*rr++) += (*cs++);
  /* #792: @80 = (-@80) */
  for (i=0, rr=w80, cs=w80; i<3; ++i) *rr++ = (- *cs++ );
  /* #793: (@48[:3] += @80) */
  for (rr=w48+0, cs=w80; rr!=w48+3; rr+=1) *rr += *cs++;
  /* #794: {@52, @54, @69, @73, @62, @72, @47, @46, @70, @74, @75, @78, @45} = vertsplit(@48) */
  w52 = w48[0];
  w54 = w48[1];
  w69 = w48[2];
  w73 = w48[3];
  w62 = w48[4];
  w72 = w48[5];
  w47 = w48[6];
  w46 = w48[7];
  w70 = w48[8];
  w74 = w48[9];
  w75 = w48[10];
  w78 = w48[11];
  w45 = w48[12];
  /* #795: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #796: @59 = (@28*@17) */
  for (i=0, rr=w59, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #797: @60 = (@60-@59) */
  for (i=0, rr=w60, cs=w59; i<4; ++i) (*rr++) -= (*cs++);
  /* #798: {@17, @76, @77, @50} = vertsplit(@60) */
  w17 = w60[0];
  w76 = w60[1];
  w77 = w60[2];
  w50 = w60[3];
  /* #799: @17 = (@17+@47) */
  w17 += w47;
  /* #800: @46 = (@46-@76) */
  w46 -= w76;
  /* #801: @70 = (@70-@77) */
  w70 -= w77;
  /* #802: @74 = (@74-@50) */
  w74 -= w50;
  /* #803: @19 = vertcat(@53, @51, @55, @43, @52, @54, @69, @73, @62, @72, @17, @46, @70, @74, @75, @78, @45) */
  rr=w19;
  *rr++ = w53;
  *rr++ = w51;
  *rr++ = w55;
  *rr++ = w43;
  *rr++ = w52;
  *rr++ = w54;
  *rr++ = w69;
  *rr++ = w73;
  *rr++ = w62;
  *rr++ = w72;
  *rr++ = w17;
  *rr++ = w46;
  *rr++ = w70;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w78;
  *rr++ = w45;
  /* #804: @79 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w79, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #805: (@56[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @79) */
  for (cii=casadi_s18, rr=w56, cs=w79; cii!=casadi_s18+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #806: (@56[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @79) */
  for (cii=casadi_s19, rr=w56, cs=w79; cii!=casadi_s19+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #807: @81 = ones(17x1,2nz) */
  casadi_fill(w81, 2, 1.);
  /* #808: {NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @51, NULL, NULL, NULL} = vertsplit(@81) */
  w53 = w81[0];
  w51 = w81[1];
  /* #809: @55 = vertcat(@58, @58, @58, @53) */
  rr=(&w55);
  *rr++ = w53;
  /* #810: @55 = @55' */
  /* #811: @60 = mac(@55,@29,@26) */
  casadi_copy(w26, 4, w60);
  casadi_mtimes((&w55), casadi_s20, w29, casadi_s1, w60, casadi_s0, w, 0);
  /* #812: @60 = @60' */
  /* #813: @26 = mac(@55,@38,@26) */
  casadi_mtimes((&w55), casadi_s20, w38, casadi_s1, w26, casadi_s0, w, 0);
  /* #814: @26 = @26' */
  /* #815: @60 = (@60+@26) */
  for (i=0, rr=w60, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #816: {@55, @53, @43, @52} = vertsplit(@60) */
  w55 = w60[0];
  w53 = w60[1];
  w43 = w60[2];
  w52 = w60[3];
  /* #817: @54 = (-@51) */
  w54 = (- w51 );
  /* #818: @69 = vertcat(@58, @58, @58, @54) */
  rr=(&w69);
  *rr++ = w54;
  /* #819: @69 = (@69/@8) */
  w69 /= w08;
  /* #820: @60 = dense(@69) */
  casadi_densify((&w69), casadi_s21, w60, 0);
  /* #821: @69 = project(@31) */
  casadi_sparsify(w31, (&w69), casadi_s21, 0);
  /* #822: @51 = sparsity_cast(@51) */
  /* #823: @54 = dot(@69, @51) */
  w54 = casadi_dot(1, (&w69), (&w51));
  /* #824: @54 = (@54/@8) */
  w54 /= w08;
  /* #825: @27 = (@27*@54) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) *= w54;
  /* #826: @60 = (@60-@27) */
  for (i=0, rr=w60, cs=w27; i<4; ++i) (*rr++) -= (*cs++);
  /* #827: {@69, @73, @62, @72} = vertsplit(@60) */
  w69 = w60[0];
  w73 = w60[1];
  w62 = w60[2];
  w72 = w60[3];
  /* #828: @17 = (@4*@69) */
  w17  = (w04*w69);
  /* #829: @46 = (@5*@73) */
  w46  = (w05*w73);
  /* #830: @17 = (@17-@46) */
  w17 -= w46;
  /* #831: @46 = (@6*@62) */
  w46  = (w06*w62);
  /* #832: @17 = (@17-@46) */
  w17 -= w46;
  /* #833: @46 = (@7*@72) */
  w46  = (w07*w72);
  /* #834: @17 = (@17-@46) */
  w17 -= w46;
  /* #835: @46 = (@5*@69) */
  w46  = (w05*w69);
  /* #836: @70 = (@4*@73) */
  w70  = (w04*w73);
  /* #837: @46 = (@46+@70) */
  w46 += w70;
  /* #838: @70 = (@7*@62) */
  w70  = (w07*w62);
  /* #839: @46 = (@46+@70) */
  w46 += w70;
  /* #840: @70 = (@6*@72) */
  w70  = (w06*w72);
  /* #841: @46 = (@46-@70) */
  w46 -= w70;
  /* #842: @70 = (@6*@69) */
  w70  = (w06*w69);
  /* #843: @74 = (@7*@73) */
  w74  = (w07*w73);
  /* #844: @70 = (@70-@74) */
  w70 -= w74;
  /* #845: @74 = (@4*@62) */
  w74  = (w04*w62);
  /* #846: @70 = (@70+@74) */
  w70 += w74;
  /* #847: @74 = (@5*@72) */
  w74  = (w05*w72);
  /* #848: @70 = (@70+@74) */
  w70 += w74;
  /* #849: @69 = (@7*@69) */
  w69  = (w07*w69);
  /* #850: @73 = (@6*@73) */
  w73  = (w06*w73);
  /* #851: @69 = (@69+@73) */
  w69 += w73;
  /* #852: @62 = (@5*@62) */
  w62  = (w05*w62);
  /* #853: @69 = (@69-@62) */
  w69 -= w62;
  /* #854: @72 = (@4*@72) */
  w72  = (w04*w72);
  /* #855: @69 = (@69+@72) */
  w69 += w72;
  /* #856: @27 = vertcat(@17, @46, @70, @69) */
  rr=w27;
  *rr++ = w17;
  *rr++ = w46;
  *rr++ = w70;
  *rr++ = w69;
  /* #857: @26 = (-@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #858: @26 = (@13?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #859: @27 = (@12?@27:0) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #860: @26 = (@26+@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) (*rr++) += (*cs++);
  /* #861: @80 = @26[1:4] */
  for (rr=w80, cs=w26+1; cs!=w26+4; cs+=1) *rr++ = *cs;
  /* #862: @17 = dot(@20, @80) */
  w17 = casadi_dot(3, w20, w80);
  /* #863: @17 = (@17/@14) */
  w17 /= w14;
  /* #864: @46 = (@17/@11) */
  w46  = (w17/w11);
  /* #865: @16 = (@16*@17) */
  w16 *= w17;
  /* #866: @70 = @26[0] */
  for (rr=(&w70), cs=w26+0; cs!=w26+1; cs+=1) *rr++ = *cs;
  /* #867: @15 = (@15*@70) */
  w15 *= w70;
  /* #868: @16 = (@16+@15) */
  w16 += w15;
  /* #869: @61 = (@61*@16) */
  w61 *= w16;
  /* #870: @46 = (@46-@61) */
  w46 -= w61;
  /* #871: @46 = (@0*@46) */
  w46  = (w00*w46);
  /* #872: @65 = (2.*@80) */
  for (i=0, rr=w65, cs=w80; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #873: @41 = (@9*@65) */
  for (i=0, rr=w41, cs=w65; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #874: @61 = (@10*@17) */
  w61  = (w10*w17);
  /* #875: @15 = (@3*@70) */
  w15  = (w03*w70);
  /* #876: @61 = (@61-@15) */
  w61 -= w15;
  /* #877: @25 = (@34*@61) */
  for (i=0, rr=w25, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #878: @41 = (@41+@25) */
  for (i=0, rr=w41, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #879: @41 = (@41/@14) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w14;
  /* #880: @35 = (@35*@17) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) *= w17;
  /* #881: @41 = (@41-@35) */
  for (i=0, rr=w41, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #882: @35 = @41' */
  casadi_copy(w41, 3, w35);
  /* #883: @25 = mac(@35,@23,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #884: @25 = @25' */
  /* #885: @1 = mac(@35,@39,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #886: @1 = @1' */
  /* #887: @25 = (@25+@1) */
  for (i=0, rr=w25, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #888: @1 = (@25/@14) */
  for (i=0, rr=w01, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #889: @42 = (@42*@17) */
  for (i=0, rr=w42; i<3; ++i) (*rr++) *= w17;
  /* #890: @1 = (@1-@42) */
  for (i=0, rr=w01, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  /* #891: @15 = dot(@34, @1) */
  w15 = casadi_dot(3, w34, w01);
  /* #892: @69 = dot(@65, @40) */
  w69 = casadi_dot(3, w65, w40);
  /* #893: @15 = (@15+@69) */
  w15 += w69;
  /* #894: @3 = (@3*@15) */
  w03 *= w15;
  /* #895: @46 = (@46+@3) */
  w46 += w03;
  /* #896: @46 = (-@46) */
  w46 = (- w46 );
  /* #897: (@33[0] += @46) */
  for (rr=w33+0, cs=(&w46); rr!=w33+1; rr+=1) *rr += *cs++;
  /* #898: @46 = dot(@36, @25) */
  w46 = casadi_dot(3, w36, w25);
  /* #899: @41 = (@41/@14) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w14;
  /* #900: @64 = (@64*@17) */
  for (i=0, rr=w64; i<3; ++i) (*rr++) *= w17;
  /* #901: @41 = (@41-@64) */
  for (i=0, rr=w41, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #902: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #903: @3 = dot(@41, @37) */
  w03 = casadi_dot(3, w41, w37);
  /* #904: @46 = (@46+@3) */
  w46 += w03;
  /* #905: @70 = (@70/@11) */
  w70 /= w11;
  /* #906: @67 = (@67*@16) */
  w67 *= w16;
  /* #907: @70 = (@70-@67) */
  w70 -= w67;
  /* #908: @0 = (@0*@70) */
  w00 *= w70;
  /* #909: @10 = (@10*@15) */
  w10 *= w15;
  /* #910: @0 = (@0+@10) */
  w00 += w10;
  /* #911: @46 = (@46+@0) */
  w46 += w00;
  /* #912: @46 = (@46/@14) */
  w46 /= w14;
  /* #913: @18 = (@18*@17) */
  w18 *= w17;
  /* #914: @46 = (@46-@18) */
  w46 -= w18;
  /* #915: @20 = (@20*@46) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w46;
  /* #916: @80 = (@2*@80) */
  for (i=0, rr=w80, cs=w80; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #917: @20 = (@20+@80) */
  for (i=0, rr=w20, cs=w80; i<3; ++i) (*rr++) += (*cs++);
  /* #918: @40 = (@40*@61) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w61;
  /* #919: @1 = (@9*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #920: @40 = (@40+@1) */
  for (i=0, rr=w40, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #921: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #922: @20 = (@20+@40) */
  for (i=0, rr=w20, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #923: (@33[1:4] += @20) */
  for (rr=w33+1, cs=w20; rr!=w33+4; rr+=1) *rr += *cs++;
  /* #924: @26 = (@12?@33:0) */
  for (i=0, rr=w26, cs=w33; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #925: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) *rr++ = (- *cs++ );
  /* #926: @33 = (@13?@33:0) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #927: @26 = (@26+@33) */
  for (i=0, rr=w26, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #928: {@13, @12, @9, @61} = vertsplit(@26) */
  w13 = w26[0];
  w12 = w26[1];
  w09 = w26[2];
  w61 = w26[3];
  /* #929: @2 = (@7*@61) */
  w02  = (w07*w61);
  /* #930: @46 = (@6*@9) */
  w46  = (w06*w09);
  /* #931: @2 = (@2+@46) */
  w02 += w46;
  /* #932: @46 = (@5*@12) */
  w46  = (w05*w12);
  /* #933: @2 = (@2+@46) */
  w02 += w46;
  /* #934: @46 = (@4*@13) */
  w46  = (w04*w13);
  /* #935: @2 = (@2+@46) */
  w02 += w46;
  /* #936: @46 = (@6*@61) */
  w46  = (w06*w61);
  /* #937: @18 = (@7*@9) */
  w18  = (w07*w09);
  /* #938: @46 = (@46-@18) */
  w46 -= w18;
  /* #939: @18 = (@4*@12) */
  w18  = (w04*w12);
  /* #940: @46 = (@46+@18) */
  w46 += w18;
  /* #941: @18 = (@5*@13) */
  w18  = (w05*w13);
  /* #942: @46 = (@46-@18) */
  w46 -= w18;
  /* #943: @18 = (@4*@9) */
  w18  = (w04*w09);
  /* #944: @17 = (@5*@61) */
  w17  = (w05*w61);
  /* #945: @18 = (@18-@17) */
  w18 -= w17;
  /* #946: @17 = (@7*@12) */
  w17  = (w07*w12);
  /* #947: @18 = (@18+@17) */
  w18 += w17;
  /* #948: @17 = (@6*@13) */
  w17  = (w06*w13);
  /* #949: @18 = (@18-@17) */
  w18 -= w17;
  /* #950: @4 = (@4*@61) */
  w04 *= w61;
  /* #951: @5 = (@5*@9) */
  w05 *= w09;
  /* #952: @4 = (@4+@5) */
  w04 += w05;
  /* #953: @6 = (@6*@12) */
  w06 *= w12;
  /* #954: @4 = (@4-@6) */
  w04 -= w06;
  /* #955: @7 = (@7*@13) */
  w07 *= w13;
  /* #956: @4 = (@4-@7) */
  w04 -= w07;
  /* #957: @26 = vertcat(@2, @46, @18, @4) */
  rr=w26;
  *rr++ = w02;
  *rr++ = w46;
  *rr++ = w18;
  *rr++ = w04;
  /* #958: @2 = dot(@30, @26) */
  w02 = casadi_dot(4, w30, w26);
  /* #959: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #960: @63 = (@63*@54) */
  for (i=0, rr=w63; i<4; ++i) (*rr++) *= w54;
  /* #961: @60 = (@60-@63) */
  for (i=0, rr=w60, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #962: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #963: @46 = dot(@60, @32) */
  w46 = casadi_dot(4, w60, w32);
  /* #964: @2 = (@2+@46) */
  w02 += w46;
  /* #965: @2 = (@2/@8) */
  w02 /= w08;
  /* #966: @68 = (@68*@54) */
  w68 *= w54;
  /* #967: @2 = (@2-@68) */
  w02 -= w68;
  /* #968: @31 = (@31*@2) */
  for (i=0, rr=w31; i<4; ++i) (*rr++) *= w02;
  /* #969: @44 = (@44*@51) */
  w44 *= w51;
  /* #970: @60 = dense(@44) */
  casadi_densify((&w44), casadi_s21, w60, 0);
  /* #971: @31 = (@31+@60) */
  for (i=0, rr=w31, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #972: (@21[6:10] += @31) */
  for (rr=w21+6, cs=w31; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #973: {@44, @51, @2, @68, @46, @18, @4, @7, @13, @6, @12, @5, @9} = vertsplit(@21) */
  w44 = w21[0];
  w51 = w21[1];
  w02 = w21[2];
  w68 = w21[3];
  w46 = w21[4];
  w18 = w21[5];
  w04 = w21[6];
  w07 = w21[7];
  w13 = w21[8];
  w06 = w21[9];
  w12 = w21[10];
  w05 = w21[11];
  w09 = w21[12];
  /* #974: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #975: @28 = (@28*@54) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) *= w54;
  /* #976: @26 = (@26-@28) */
  for (i=0, rr=w26, cs=w28; i<4; ++i) (*rr++) -= (*cs++);
  /* #977: {@54, @8, @61, @17} = vertsplit(@26) */
  w54 = w26[0];
  w08 = w26[1];
  w61 = w26[2];
  w17 = w26[3];
  /* #978: @54 = (@54+@4) */
  w54 += w04;
  /* #979: @7 = (@7-@8) */
  w07 -= w08;
  /* #980: @13 = (@13-@61) */
  w13 -= w61;
  /* #981: @6 = (@6-@17) */
  w06 -= w17;
  /* #982: @19 = vertcat(@55, @53, @43, @52, @44, @51, @2, @68, @46, @18, @54, @7, @13, @6, @12, @5, @9) */
  rr=w19;
  *rr++ = w55;
  *rr++ = w53;
  *rr++ = w43;
  *rr++ = w52;
  *rr++ = w44;
  *rr++ = w51;
  *rr++ = w02;
  *rr++ = w68;
  *rr++ = w46;
  *rr++ = w18;
  *rr++ = w54;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w09;
  /* #983: @82 = @19[:20:10;:4] */
  for (rr=w82, cs=w19+0; cs!=w19+20; cs+=10) for (ct=cs+0; ct!=cs+4; ct+=1) *rr++ = *ct;
  /* #984: (@56[:50:25;12:16] = @82) */
  for (rr=w56+0, cs=w82; rr!=w56+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *cs++;
  /* #985: (@56[:50:25;3:19:4] = @82) */
  for (rr=w56+0, cs=w82; rr!=w56+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *cs++;
  /* #986: @83 = @56' */
  casadi_trans(w56,casadi_s22, w83, casadi_s22, iw);
  /* #987: output[2][0] = @83 */
  casadi_copy(w83, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s23;
    case 1: return casadi_s24;
    case 2: return casadi_s25;
    case 3: return casadi_s26;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s27;
    case 1: return casadi_s26;
    case 2: return casadi_s22;
    case 3: return casadi_s28;
    case 4: return casadi_s29;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 355;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 22*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 18*sizeof(casadi_int);
  if (sz_w) *sz_w = 355*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
