/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {17, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

/* Drone_ode_complete_cost_ext_cost_e_fun_jac:(i0[13],i1[0],i2[0],i3[17])->(o0,o1[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55;
  casadi_real *w23=w+58, *w24=w+67, *w25=w+76, *w26=w+79, *w27=w+83, *w28=w+87, *w29=w+91, *w30=w+95, *w31=w+98, *w32=w+101, *w33=w+104, *w34=w+107;
  casadi_real *w35=w+116;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 25 */
  w02 = 25.;
  /* #40: @24 = @23; (@24[0] = @2) */
  casadi_copy(w23, 9, w24);
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #41: (@24[4] = @2) */
  for (rr=w24+4, cs=(&w02); rr!=w24+5; rr+=1) *rr = *cs++;
  /* #42: @2 = 30 */
  w02 = 30.;
  /* #43: (@24[8] = @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr = *cs++;
  /* #44: @25 = mac(@22,@24,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #45: @2 = mac(@25,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @9 = (-@9) */
  w09 = (- w09 );
  /* #47: @10 = (-@10) */
  w10 = (- w10 );
  /* #48: @11 = (-@11) */
  w11 = (- w11 );
  /* #49: @26 = vertcat(@8, @9, @10, @11) */
  rr=w26;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #50: @27 = @21[6:10] */
  for (rr=w27, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #51: @8 = ||@27||_F */
  w08 = casadi_norm_2(4, w27);
  /* #52: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #53: {@9, @10, @11, @3} = vertsplit(@26) */
  w09 = w26[0];
  w10 = w26[1];
  w11 = w26[2];
  w03 = w26[3];
  /* #54: @28 = @19[6:10] */
  for (rr=w28, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #55: {@4, @5, @6, @7} = vertsplit(@28) */
  w04 = w28[0];
  w05 = w28[1];
  w06 = w28[2];
  w07 = w28[3];
  /* #56: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #57: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #58: @12 = (@12-@13) */
  w12 -= w13;
  /* #59: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #60: @12 = (@12-@13) */
  w12 -= w13;
  /* #61: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #62: @12 = (@12-@13) */
  w12 -= w13;
  /* #63: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #64: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #65: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #66: @14 = (@14+@15) */
  w14 += w15;
  /* #67: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #68: @14 = (@14+@15) */
  w14 += w15;
  /* #69: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #70: @14 = (@14-@15) */
  w14 -= w15;
  /* #71: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #72: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #73: @15 = (@15-@16) */
  w15 -= w16;
  /* #74: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #75: @15 = (@15+@16) */
  w15 += w16;
  /* #76: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #77: @15 = (@15+@16) */
  w15 += w16;
  /* #78: @9 = (@9*@7) */
  w09 *= w07;
  /* #79: @10 = (@10*@6) */
  w10 *= w06;
  /* #80: @9 = (@9+@10) */
  w09 += w10;
  /* #81: @11 = (@11*@5) */
  w11 *= w05;
  /* #82: @9 = (@9-@11) */
  w09 -= w11;
  /* #83: @3 = (@3*@4) */
  w03 *= w04;
  /* #84: @9 = (@9+@3) */
  w09 += w03;
  /* #85: @28 = vertcat(@12, @14, @15, @9) */
  rr=w28;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #86: @29 = (-@28) */
  for (i=0, rr=w29, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #87: @29 = (@13?@29:0) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #88: @12 = (!@13) */
  w12 = (! w13 );
  /* #89: @28 = (@12?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #90: @29 = (@29+@28) */
  for (i=0, rr=w29, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #91: @20 = @29[1:4] */
  for (rr=w20, cs=w29+1; cs!=w29+4; cs+=1) *rr++ = *cs;
  /* #92: @30 = (2.*@20) */
  for (i=0, rr=w30, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #93: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #94: @15 = @29[0] */
  for (rr=(&w15), cs=w29+0; cs!=w29+1; cs+=1) *rr++ = *cs;
  /* #95: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #96: @31 = (@30*@9) */
  for (i=0, rr=w31, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #97: @31 = (@31/@14) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w14;
  /* #98: @32 = @31' */
  casadi_copy(w31, 3, w32);
  /* #99: @3 = 12 */
  w03 = 12.;
  /* #100: (@23[0] = @3) */
  for (rr=w23+0, cs=(&w03); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #101: (@23[4] = @3) */
  for (rr=w23+4, cs=(&w03); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #102: (@23[8] = @3) */
  for (rr=w23+8, cs=(&w03); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #103: @33 = mac(@32,@23,@1) */
  casadi_copy(w01, 3, w33);
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #104: @0 = mac(@33,@31,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #105: @2 = (@2+@0) */
  w02 += w00;
  /* #106: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #107: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #108: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #109: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #110: @29 = zeros(4x1) */
  casadi_clear(w29, 4);
  /* #111: @2 = sq(@14) */
  w02 = casadi_sq( w14 );
  /* #112: @0 = sq(@15) */
  w00 = casadi_sq( w15 );
  /* #113: @2 = (@2+@0) */
  w02 += w00;
  /* #114: @0 = (@14/@2) */
  w00  = (w14/w02);
  /* #115: @33 = @33' */
  /* #116: @34 = @23' */
  for (i=0, rr=w34, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #117: @35 = mac(@32,@34,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #118: @35 = @35' */
  /* #119: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #120: @35 = (@33/@14) */
  for (i=0, rr=w35, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #121: @3 = dot(@30, @35) */
  w03 = casadi_dot(3, w30, w35);
  /* #122: @0 = (@0*@3) */
  w00 *= w03;
  /* #123: @0 = (-@0) */
  w00 = (- w00 );
  /* #124: (@29[0] += @0) */
  for (rr=w29+0, cs=(&w00); rr!=w29+1; rr+=1) *rr += *cs++;
  /* #125: @31 = (@31/@14) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w14;
  /* #126: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #127: @0 = dot(@31, @33) */
  w00 = casadi_dot(3, w31, w33);
  /* #128: @15 = (@15/@2) */
  w15 /= w02;
  /* #129: @15 = (@15*@3) */
  w15 *= w03;
  /* #130: @0 = (@0+@15) */
  w00 += w15;
  /* #131: @0 = (@0/@14) */
  w00 /= w14;
  /* #132: @20 = (@0*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #133: @35 = (@9*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #134: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #135: @20 = (@20+@35) */
  for (i=0, rr=w20, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #136: (@29[1:4] += @20) */
  for (rr=w29+1, cs=w20; rr!=w29+4; rr+=1) *rr += *cs++;
  /* #137: @28 = (@12?@29:0) */
  for (i=0, rr=w28, cs=w29; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #138: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) *rr++ = (- *cs++ );
  /* #139: @29 = (@13?@29:0) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #140: @28 = (@28+@29) */
  for (i=0, rr=w28, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #141: {@13, @12, @9, @0} = vertsplit(@28) */
  w13 = w28[0];
  w12 = w28[1];
  w09 = w28[2];
  w00 = w28[3];
  /* #142: @14 = (@7*@0) */
  w14  = (w07*w00);
  /* #143: @15 = (@6*@9) */
  w15  = (w06*w09);
  /* #144: @14 = (@14+@15) */
  w14 += w15;
  /* #145: @15 = (@5*@12) */
  w15  = (w05*w12);
  /* #146: @14 = (@14+@15) */
  w14 += w15;
  /* #147: @15 = (@4*@13) */
  w15  = (w04*w13);
  /* #148: @14 = (@14+@15) */
  w14 += w15;
  /* #149: @15 = (@6*@0) */
  w15  = (w06*w00);
  /* #150: @3 = (@7*@9) */
  w03  = (w07*w09);
  /* #151: @15 = (@15-@3) */
  w15 -= w03;
  /* #152: @3 = (@4*@12) */
  w03  = (w04*w12);
  /* #153: @15 = (@15+@3) */
  w15 += w03;
  /* #154: @3 = (@5*@13) */
  w03  = (w05*w13);
  /* #155: @15 = (@15-@3) */
  w15 -= w03;
  /* #156: @3 = (@4*@9) */
  w03  = (w04*w09);
  /* #157: @2 = (@5*@0) */
  w02  = (w05*w00);
  /* #158: @3 = (@3-@2) */
  w03 -= w02;
  /* #159: @2 = (@7*@12) */
  w02  = (w07*w12);
  /* #160: @3 = (@3+@2) */
  w03 += w02;
  /* #161: @2 = (@6*@13) */
  w02  = (w06*w13);
  /* #162: @3 = (@3-@2) */
  w03 -= w02;
  /* #163: @4 = (@4*@0) */
  w04 *= w00;
  /* #164: @5 = (@5*@9) */
  w05 *= w09;
  /* #165: @4 = (@4+@5) */
  w04 += w05;
  /* #166: @6 = (@6*@12) */
  w06 *= w12;
  /* #167: @4 = (@4-@6) */
  w04 -= w06;
  /* #168: @7 = (@7*@13) */
  w07 *= w13;
  /* #169: @4 = (@4-@7) */
  w04 -= w07;
  /* #170: @28 = vertcat(@14, @15, @3, @4) */
  rr=w28;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w03;
  *rr++ = w04;
  /* #171: @14 = dot(@26, @28) */
  w14 = casadi_dot(4, w26, w28);
  /* #172: @14 = (@14/@8) */
  w14 /= w08;
  /* #173: @27 = (@14*@27) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #174: (@21[6:10] += @27) */
  for (rr=w21+6, cs=w27; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #175: @25 = @25' */
  /* #176: @34 = @24' */
  for (i=0, rr=w34, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #177: @1 = mac(@22,@34,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #178: @1 = @1' */
  /* #179: @25 = (@25+@1) */
  for (i=0, rr=w25, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #180: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #181: (@21[:3] += @25) */
  for (rr=w21+0, cs=w25; rr!=w21+3; rr+=1) *rr += *cs++;
  /* #182: {@14, @15, @3, @4, @7, @13, @6, @12, @5, @9, @0, @2, @11} = vertsplit(@21) */
  w14 = w21[0];
  w15 = w21[1];
  w03 = w21[2];
  w04 = w21[3];
  w07 = w21[4];
  w13 = w21[5];
  w06 = w21[6];
  w12 = w21[7];
  w05 = w21[8];
  w09 = w21[9];
  w00 = w21[10];
  w02 = w21[11];
  w11 = w21[12];
  /* #183: output[1][0] = @14 */
  if (res[1]) res[1][0] = w14;
  /* #184: output[1][1] = @15 */
  if (res[1]) res[1][1] = w15;
  /* #185: output[1][2] = @3 */
  if (res[1]) res[1][2] = w03;
  /* #186: output[1][3] = @4 */
  if (res[1]) res[1][3] = w04;
  /* #187: output[1][4] = @7 */
  if (res[1]) res[1][4] = w07;
  /* #188: output[1][5] = @13 */
  if (res[1]) res[1][5] = w13;
  /* #189: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #190: {@8, @13, @7, @4} = vertsplit(@28) */
  w08 = w28[0];
  w13 = w28[1];
  w07 = w28[2];
  w04 = w28[3];
  /* #191: @8 = (@8+@6) */
  w08 += w06;
  /* #192: output[1][6] = @8 */
  if (res[1]) res[1][6] = w08;
  /* #193: @12 = (@12-@13) */
  w12 -= w13;
  /* #194: output[1][7] = @12 */
  if (res[1]) res[1][7] = w12;
  /* #195: @5 = (@5-@7) */
  w05 -= w07;
  /* #196: output[1][8] = @5 */
  if (res[1]) res[1][8] = w05;
  /* #197: @9 = (@9-@4) */
  w09 -= w04;
  /* #198: output[1][9] = @9 */
  if (res[1]) res[1][9] = w09;
  /* #199: output[1][10] = @0 */
  if (res[1]) res[1][10] = w00;
  /* #200: output[1][11] = @2 */
  if (res[1]) res[1][11] = w02;
  /* #201: output[1][12] = @11 */
  if (res[1]) res[1][12] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 119;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 15*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 119*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
