/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {17, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* Drone_ode_complete_cost_ext_cost_fun_jac:(i0[13],i1[4],i2[0],i3[17])->(o0,o1[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55;
  casadi_real *w23=w+58, *w24=w+67, *w25=w+76, *w26=w+79, *w27=w+83, *w28=w+87, *w29=w+91, *w30=w+107, *w31=w+111, *w32=w+115, *w33=w+119, *w34=w+123;
  casadi_real *w35=w+126, *w36=w+129, *w37=w+132, *w38=w+135, *w39=w+151, *w40=w+160;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 25 */
  w02 = 25.;
  /* #40: @24 = @23; (@24[0] = @2) */
  casadi_copy(w23, 9, w24);
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #41: (@24[4] = @2) */
  for (rr=w24+4, cs=(&w02); rr!=w24+5; rr+=1) *rr = *cs++;
  /* #42: @2 = 30 */
  w02 = 30.;
  /* #43: (@24[8] = @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr = *cs++;
  /* #44: @25 = mac(@22,@24,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #45: @2 = mac(@25,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #47: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #48: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #49: @5 = input[1][2] */
  w05 = arg[1] ? arg[1][2] : 0;
  /* #50: @6 = input[1][3] */
  w06 = arg[1] ? arg[1][3] : 0;
  /* #51: @27 = vertcat(@3, @4, @5, @6) */
  rr=w27;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #52: @28 = @27' */
  casadi_copy(w27, 4, w28);
  /* #53: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #54: @3 = 1 */
  w03 = 1.;
  /* #55: (@29[0] = @3) */
  for (rr=w29+0, cs=(&w03); rr!=w29+1; rr+=1) *rr = *cs++;
  /* #56: @3 = 800 */
  w03 = 800.;
  /* #57: (@29[5] = @3) */
  for (rr=w29+5, cs=(&w03); rr!=w29+6; rr+=1) *rr = *cs++;
  /* #58: (@29[10] = @3) */
  for (rr=w29+10, cs=(&w03); rr!=w29+11; rr+=1) *rr = *cs++;
  /* #59: (@29[15] = @3) */
  for (rr=w29+15, cs=(&w03); rr!=w29+16; rr+=1) *rr = *cs++;
  /* #60: @30 = mac(@28,@29,@26) */
  casadi_copy(w26, 4, w30);
  for (i=0, rr=w30; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #61: @3 = mac(@30,@27,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w30+j, ct=w27+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #62: @2 = (@2+@3) */
  w02 += w03;
  /* #63: @9 = (-@9) */
  w09 = (- w09 );
  /* #64: @10 = (-@10) */
  w10 = (- w10 );
  /* #65: @11 = (-@11) */
  w11 = (- w11 );
  /* #66: @27 = vertcat(@8, @9, @10, @11) */
  rr=w27;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #67: @31 = @21[6:10] */
  for (rr=w31, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #68: @8 = ||@31||_F */
  w08 = casadi_norm_2(4, w31);
  /* #69: @27 = (@27/@8) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w08;
  /* #70: {@9, @10, @11, @3} = vertsplit(@27) */
  w09 = w27[0];
  w10 = w27[1];
  w11 = w27[2];
  w03 = w27[3];
  /* #71: @32 = @19[6:10] */
  for (rr=w32, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #72: {@4, @5, @6, @7} = vertsplit(@32) */
  w04 = w32[0];
  w05 = w32[1];
  w06 = w32[2];
  w07 = w32[3];
  /* #73: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #74: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #75: @12 = (@12-@13) */
  w12 -= w13;
  /* #76: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #77: @12 = (@12-@13) */
  w12 -= w13;
  /* #78: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #79: @12 = (@12-@13) */
  w12 -= w13;
  /* #80: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #81: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #82: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #83: @14 = (@14+@15) */
  w14 += w15;
  /* #84: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #85: @14 = (@14+@15) */
  w14 += w15;
  /* #86: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #87: @14 = (@14-@15) */
  w14 -= w15;
  /* #88: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #89: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #90: @15 = (@15-@16) */
  w15 -= w16;
  /* #91: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #92: @15 = (@15+@16) */
  w15 += w16;
  /* #93: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #94: @15 = (@15+@16) */
  w15 += w16;
  /* #95: @9 = (@9*@7) */
  w09 *= w07;
  /* #96: @10 = (@10*@6) */
  w10 *= w06;
  /* #97: @9 = (@9+@10) */
  w09 += w10;
  /* #98: @11 = (@11*@5) */
  w11 *= w05;
  /* #99: @9 = (@9-@11) */
  w09 -= w11;
  /* #100: @3 = (@3*@4) */
  w03 *= w04;
  /* #101: @9 = (@9+@3) */
  w09 += w03;
  /* #102: @32 = vertcat(@12, @14, @15, @9) */
  rr=w32;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #103: @33 = (-@32) */
  for (i=0, rr=w33, cs=w32; i<4; ++i) *rr++ = (- *cs++ );
  /* #104: @33 = (@13?@33:0) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #105: @12 = (!@13) */
  w12 = (! w13 );
  /* #106: @32 = (@12?@32:0) */
  for (i=0, rr=w32, cs=w32; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #107: @33 = (@33+@32) */
  for (i=0, rr=w33, cs=w32; i<4; ++i) (*rr++) += (*cs++);
  /* #108: @20 = @33[1:4] */
  for (rr=w20, cs=w33+1; cs!=w33+4; cs+=1) *rr++ = *cs;
  /* #109: @34 = (2.*@20) */
  for (i=0, rr=w34, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #110: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #111: @15 = @33[0] */
  for (rr=(&w15), cs=w33+0; cs!=w33+1; cs+=1) *rr++ = *cs;
  /* #112: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #113: @35 = (@34*@9) */
  for (i=0, rr=w35, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #114: @35 = (@35/@14) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w14;
  /* #115: @36 = @35' */
  casadi_copy(w35, 3, w36);
  /* #116: @3 = 12 */
  w03 = 12.;
  /* #117: (@23[0] = @3) */
  for (rr=w23+0, cs=(&w03); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #118: (@23[4] = @3) */
  for (rr=w23+4, cs=(&w03); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #119: (@23[8] = @3) */
  for (rr=w23+8, cs=(&w03); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #120: @37 = mac(@36,@23,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #121: @0 = mac(@37,@35,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #122: @2 = (@2+@0) */
  w02 += w00;
  /* #123: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #124: @30 = @30' */
  /* #125: @38 = @29' */
  for (i=0, rr=w38, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #126: @26 = mac(@28,@38,@26) */
  for (i=0, rr=w26; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w38+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #127: @26 = @26' */
  /* #128: @30 = (@30+@26) */
  for (i=0, rr=w30, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #129: {@2, @0, @3, @11} = vertsplit(@30) */
  w02 = w30[0];
  w00 = w30[1];
  w03 = w30[2];
  w11 = w30[3];
  /* #130: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #131: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #132: output[1][2] = @3 */
  if (res[1]) res[1][2] = w03;
  /* #133: output[1][3] = @11 */
  if (res[1]) res[1][3] = w11;
  /* #134: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #135: @27 = (@27/@8) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w08;
  /* #136: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #137: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #138: @11 = sq(@14) */
  w11 = casadi_sq( w14 );
  /* #139: @3 = sq(@15) */
  w03 = casadi_sq( w15 );
  /* #140: @11 = (@11+@3) */
  w11 += w03;
  /* #141: @3 = (@14/@11) */
  w03  = (w14/w11);
  /* #142: @37 = @37' */
  /* #143: @39 = @23' */
  for (i=0, rr=w39, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #144: @40 = mac(@36,@39,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #145: @40 = @40' */
  /* #146: @37 = (@37+@40) */
  for (i=0, rr=w37, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #147: @40 = (@37/@14) */
  for (i=0, rr=w40, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #148: @0 = dot(@34, @40) */
  w00 = casadi_dot(3, w34, w40);
  /* #149: @3 = (@3*@0) */
  w03 *= w00;
  /* #150: @3 = (-@3) */
  w03 = (- w03 );
  /* #151: (@30[0] += @3) */
  for (rr=w30+0, cs=(&w03); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #152: @35 = (@35/@14) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w14;
  /* #153: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #154: @3 = dot(@35, @37) */
  w03 = casadi_dot(3, w35, w37);
  /* #155: @15 = (@15/@11) */
  w15 /= w11;
  /* #156: @15 = (@15*@0) */
  w15 *= w00;
  /* #157: @3 = (@3+@15) */
  w03 += w15;
  /* #158: @3 = (@3/@14) */
  w03 /= w14;
  /* #159: @20 = (@3*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #160: @40 = (@9*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #161: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #162: @20 = (@20+@40) */
  for (i=0, rr=w20, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #163: (@30[1:4] += @20) */
  for (rr=w30+1, cs=w20; rr!=w30+4; rr+=1) *rr += *cs++;
  /* #164: @26 = (@12?@30:0) */
  for (i=0, rr=w26, cs=w30; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #165: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) *rr++ = (- *cs++ );
  /* #166: @30 = (@13?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #167: @26 = (@26+@30) */
  for (i=0, rr=w26, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #168: {@13, @12, @9, @3} = vertsplit(@26) */
  w13 = w26[0];
  w12 = w26[1];
  w09 = w26[2];
  w03 = w26[3];
  /* #169: @14 = (@7*@3) */
  w14  = (w07*w03);
  /* #170: @15 = (@6*@9) */
  w15  = (w06*w09);
  /* #171: @14 = (@14+@15) */
  w14 += w15;
  /* #172: @15 = (@5*@12) */
  w15  = (w05*w12);
  /* #173: @14 = (@14+@15) */
  w14 += w15;
  /* #174: @15 = (@4*@13) */
  w15  = (w04*w13);
  /* #175: @14 = (@14+@15) */
  w14 += w15;
  /* #176: @15 = (@6*@3) */
  w15  = (w06*w03);
  /* #177: @0 = (@7*@9) */
  w00  = (w07*w09);
  /* #178: @15 = (@15-@0) */
  w15 -= w00;
  /* #179: @0 = (@4*@12) */
  w00  = (w04*w12);
  /* #180: @15 = (@15+@0) */
  w15 += w00;
  /* #181: @0 = (@5*@13) */
  w00  = (w05*w13);
  /* #182: @15 = (@15-@0) */
  w15 -= w00;
  /* #183: @0 = (@4*@9) */
  w00  = (w04*w09);
  /* #184: @11 = (@5*@3) */
  w11  = (w05*w03);
  /* #185: @0 = (@0-@11) */
  w00 -= w11;
  /* #186: @11 = (@7*@12) */
  w11  = (w07*w12);
  /* #187: @0 = (@0+@11) */
  w00 += w11;
  /* #188: @11 = (@6*@13) */
  w11  = (w06*w13);
  /* #189: @0 = (@0-@11) */
  w00 -= w11;
  /* #190: @4 = (@4*@3) */
  w04 *= w03;
  /* #191: @5 = (@5*@9) */
  w05 *= w09;
  /* #192: @4 = (@4+@5) */
  w04 += w05;
  /* #193: @6 = (@6*@12) */
  w06 *= w12;
  /* #194: @4 = (@4-@6) */
  w04 -= w06;
  /* #195: @7 = (@7*@13) */
  w07 *= w13;
  /* #196: @4 = (@4-@7) */
  w04 -= w07;
  /* #197: @26 = vertcat(@14, @15, @0, @4) */
  rr=w26;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w00;
  *rr++ = w04;
  /* #198: @14 = dot(@27, @26) */
  w14 = casadi_dot(4, w27, w26);
  /* #199: @14 = (@14/@8) */
  w14 /= w08;
  /* #200: @31 = (@14*@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #201: (@21[6:10] += @31) */
  for (rr=w21+6, cs=w31; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #202: @25 = @25' */
  /* #203: @39 = @24' */
  for (i=0, rr=w39, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #204: @1 = mac(@22,@39,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #205: @1 = @1' */
  /* #206: @25 = (@25+@1) */
  for (i=0, rr=w25, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #207: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #208: (@21[:3] += @25) */
  for (rr=w21+0, cs=w25; rr!=w21+3; rr+=1) *rr += *cs++;
  /* #209: {@14, @15, @0, @4, @7, @13, @6, @12, @5, @9, @3, @11, @2} = vertsplit(@21) */
  w14 = w21[0];
  w15 = w21[1];
  w00 = w21[2];
  w04 = w21[3];
  w07 = w21[4];
  w13 = w21[5];
  w06 = w21[6];
  w12 = w21[7];
  w05 = w21[8];
  w09 = w21[9];
  w03 = w21[10];
  w11 = w21[11];
  w02 = w21[12];
  /* #210: output[1][4] = @14 */
  if (res[1]) res[1][4] = w14;
  /* #211: output[1][5] = @15 */
  if (res[1]) res[1][5] = w15;
  /* #212: output[1][6] = @0 */
  if (res[1]) res[1][6] = w00;
  /* #213: output[1][7] = @4 */
  if (res[1]) res[1][7] = w04;
  /* #214: output[1][8] = @7 */
  if (res[1]) res[1][8] = w07;
  /* #215: output[1][9] = @13 */
  if (res[1]) res[1][9] = w13;
  /* #216: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #217: {@8, @13, @7, @4} = vertsplit(@26) */
  w08 = w26[0];
  w13 = w26[1];
  w07 = w26[2];
  w04 = w26[3];
  /* #218: @8 = (@8+@6) */
  w08 += w06;
  /* #219: output[1][10] = @8 */
  if (res[1]) res[1][10] = w08;
  /* #220: @12 = (@12-@13) */
  w12 -= w13;
  /* #221: output[1][11] = @12 */
  if (res[1]) res[1][11] = w12;
  /* #222: @5 = (@5-@7) */
  w05 -= w07;
  /* #223: output[1][12] = @5 */
  if (res[1]) res[1][12] = w05;
  /* #224: @9 = (@9-@4) */
  w09 -= w04;
  /* #225: output[1][13] = @9 */
  if (res[1]) res[1][13] = w09;
  /* #226: output[1][14] = @3 */
  if (res[1]) res[1][14] = w03;
  /* #227: output[1][15] = @11 */
  if (res[1]) res[1][15] = w11;
  /* #228: output[1][16] = @2 */
  if (res[1]) res[1][16] = w02;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 163;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 15*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 163*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
