/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s2[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[7] = {0, 1, 2, 6, 7, 8, 9};
static const casadi_int casadi_s5[7] = {0, 1, 2, 9, 10, 11, 12};
static const casadi_int casadi_s6[7] = {0, 3, 6, 9, 13, 17, 21};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s9[7] = {3, 4, 5, 13, 14, 15, 16};
static const casadi_int casadi_s10[7] = {1, 4, 7, 10, 14, 18, 22};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s13[7] = {6, 7, 8, 17, 18, 19, 20};
static const casadi_int casadi_s14[7] = {2, 5, 8, 11, 15, 19, 23};
static const casadi_int casadi_s15[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s16[41] = 
  {13, 13, 0, 3, 6, 9, 9, 9,
  9, 13, 17, 21, 25, 25, 25, 25,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 6, 7, 8, 9, 6, 7, 8,
  9, 6, 7, 8, 9, 6, 7, 8,
  9};
static const casadi_int casadi_s17[3] = {13, 1, 1};
static const casadi_int casadi_s18[3] = {0, 1, 1};
static const casadi_int casadi_s19[3] = {17, 1, 1};
static const casadi_int casadi_s20[3] = {1, 1, 1};
static const casadi_int casadi_s21[3] = {0, 0, 1};
static const casadi_int casadi_s22[3] = {0, 13, 1};

/* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[0],i2[0],i3[17])->(o0,o1[13],o2[13x13,25nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55;
  casadi_real *w23=w+58, *w24=w+67, *w25=w+76, *w26=w+79, *w27=w+83, *w28=w+87, *w29=w+91, *w30=w+95, *w31=w+98, *w32=w+101, *w33=w+104, *w34=w+107;
  casadi_real *w35=w+116, *w36=w+119, *w37=w+123, *w38=w+126, *w39=w+129, w40, w41, w42, w43, w44, *w45=w+138, *w46=w+151;
  casadi_real w47, w48, w49, w50, w51, w52, *w53=w+166, *w54=w+191, *w56=w+199, *w57=w+203, *w58=w+207, *w59=w+211;
  casadi_real *w60=w+214, *w61=w+217, w62, w63, *w64=w+222, w65, w66, w67, w68, w69, w70, w71;
  casadi_real *w72=w+233, *w73=w+240, *w74=w+242, *w75=w+245;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 25 */
  w02 = 25.;
  /* #40: @24 = @23; (@24[0] = @2) */
  casadi_copy(w23, 9, w24);
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #41: (@24[4] = @2) */
  for (rr=w24+4, cs=(&w02); rr!=w24+5; rr+=1) *rr = *cs++;
  /* #42: @2 = 30 */
  w02 = 30.;
  /* #43: (@24[8] = @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr = *cs++;
  /* #44: @25 = mac(@22,@24,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #45: @2 = mac(@25,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @9 = (-@9) */
  w09 = (- w09 );
  /* #47: @10 = (-@10) */
  w10 = (- w10 );
  /* #48: @11 = (-@11) */
  w11 = (- w11 );
  /* #49: @26 = vertcat(@8, @9, @10, @11) */
  rr=w26;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #50: @27 = @21[6:10] */
  for (rr=w27, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #51: @8 = ||@27||_F */
  w08 = casadi_norm_2(4, w27);
  /* #52: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #53: {@9, @10, @11, @3} = vertsplit(@26) */
  w09 = w26[0];
  w10 = w26[1];
  w11 = w26[2];
  w03 = w26[3];
  /* #54: @28 = @19[6:10] */
  for (rr=w28, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #55: {@4, @5, @6, @7} = vertsplit(@28) */
  w04 = w28[0];
  w05 = w28[1];
  w06 = w28[2];
  w07 = w28[3];
  /* #56: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #57: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #58: @12 = (@12-@13) */
  w12 -= w13;
  /* #59: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #60: @12 = (@12-@13) */
  w12 -= w13;
  /* #61: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #62: @12 = (@12-@13) */
  w12 -= w13;
  /* #63: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #64: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #65: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #66: @14 = (@14+@15) */
  w14 += w15;
  /* #67: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #68: @14 = (@14+@15) */
  w14 += w15;
  /* #69: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #70: @14 = (@14-@15) */
  w14 -= w15;
  /* #71: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #72: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #73: @15 = (@15-@16) */
  w15 -= w16;
  /* #74: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #75: @15 = (@15+@16) */
  w15 += w16;
  /* #76: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #77: @15 = (@15+@16) */
  w15 += w16;
  /* #78: @9 = (@9*@7) */
  w09 *= w07;
  /* #79: @10 = (@10*@6) */
  w10 *= w06;
  /* #80: @9 = (@9+@10) */
  w09 += w10;
  /* #81: @11 = (@11*@5) */
  w11 *= w05;
  /* #82: @9 = (@9-@11) */
  w09 -= w11;
  /* #83: @3 = (@3*@4) */
  w03 *= w04;
  /* #84: @9 = (@9+@3) */
  w09 += w03;
  /* #85: @28 = vertcat(@12, @14, @15, @9) */
  rr=w28;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #86: @29 = (-@28) */
  for (i=0, rr=w29, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #87: @29 = (@13?@29:0) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #88: @12 = (!@13) */
  w12 = (! w13 );
  /* #89: @28 = (@12?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #90: @29 = (@29+@28) */
  for (i=0, rr=w29, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #91: @20 = @29[1:4] */
  for (rr=w20, cs=w29+1; cs!=w29+4; cs+=1) *rr++ = *cs;
  /* #92: @30 = (2.*@20) */
  for (i=0, rr=w30, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #93: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #94: @15 = @29[0] */
  for (rr=(&w15), cs=w29+0; cs!=w29+1; cs+=1) *rr++ = *cs;
  /* #95: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #96: @31 = (@30*@9) */
  for (i=0, rr=w31, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #97: @31 = (@31/@14) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w14;
  /* #98: @32 = @31' */
  casadi_copy(w31, 3, w32);
  /* #99: @3 = 12 */
  w03 = 12.;
  /* #100: (@23[0] = @3) */
  for (rr=w23+0, cs=(&w03); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #101: (@23[4] = @3) */
  for (rr=w23+4, cs=(&w03); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #102: (@23[8] = @3) */
  for (rr=w23+8, cs=(&w03); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #103: @33 = mac(@32,@23,@1) */
  casadi_copy(w01, 3, w33);
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #104: @0 = mac(@33,@31,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #105: @2 = (@2+@0) */
  w02 += w00;
  /* #106: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #107: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #108: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #109: @29 = (-@26) */
  for (i=0, rr=w29, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #110: @28 = zeros(4x1) */
  casadi_clear(w28, 4);
  /* #111: @2 = sq(@14) */
  w02 = casadi_sq( w14 );
  /* #112: @0 = sq(@15) */
  w00 = casadi_sq( w15 );
  /* #113: @2 = (@2+@0) */
  w02 += w00;
  /* #114: @0 = (@14/@2) */
  w00  = (w14/w02);
  /* #115: @33 = @33' */
  /* #116: @34 = @23' */
  for (i=0, rr=w34, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #117: @35 = mac(@32,@34,@1) */
  casadi_copy(w01, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #118: @35 = @35' */
  /* #119: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #120: @35 = (@33/@14) */
  for (i=0, rr=w35, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #121: @3 = dot(@30, @35) */
  w03 = casadi_dot(3, w30, w35);
  /* #122: @11 = (@0*@3) */
  w11  = (w00*w03);
  /* #123: @11 = (-@11) */
  w11 = (- w11 );
  /* #124: @36 = @28; (@36[0] += @11) */
  casadi_copy(w28, 4, w36);
  for (rr=w36+0, cs=(&w11); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #125: @31 = (@31/@14) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w14;
  /* #126: @32 = (-@31) */
  for (i=0, rr=w32, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #127: @11 = dot(@32, @33) */
  w11 = casadi_dot(3, w32, w33);
  /* #128: @10 = (@15/@2) */
  w10  = (w15/w02);
  /* #129: @16 = (@10*@3) */
  w16  = (w10*w03);
  /* #130: @11 = (@11+@16) */
  w11 += w16;
  /* #131: @11 = (@11/@14) */
  w11 /= w14;
  /* #132: @37 = (@11*@20) */
  for (i=0, rr=w37, cs=w20; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #133: @38 = (@9*@35) */
  for (i=0, rr=w38, cs=w35; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #134: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #135: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #136: (@36[1:4] += @37) */
  for (rr=w36+1, cs=w37; rr!=w36+4; rr+=1) *rr += *cs++;
  /* #137: @39 = (@12?@36:0) */
  for (i=0, rr=w39, cs=w36; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #138: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #139: @36 = (@13?@36:0) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #140: @39 = (@39+@36) */
  for (i=0, rr=w39, cs=w36; i<4; ++i) (*rr++) += (*cs++);
  /* #141: {@16, @17, @18, @40} = vertsplit(@39) */
  w16 = w39[0];
  w17 = w39[1];
  w18 = w39[2];
  w40 = w39[3];
  /* #142: @41 = (@7*@40) */
  w41  = (w07*w40);
  /* #143: @42 = (@6*@18) */
  w42  = (w06*w18);
  /* #144: @41 = (@41+@42) */
  w41 += w42;
  /* #145: @42 = (@5*@17) */
  w42  = (w05*w17);
  /* #146: @41 = (@41+@42) */
  w41 += w42;
  /* #147: @42 = (@4*@16) */
  w42  = (w04*w16);
  /* #148: @41 = (@41+@42) */
  w41 += w42;
  /* #149: @42 = (@6*@40) */
  w42  = (w06*w40);
  /* #150: @43 = (@7*@18) */
  w43  = (w07*w18);
  /* #151: @42 = (@42-@43) */
  w42 -= w43;
  /* #152: @43 = (@4*@17) */
  w43  = (w04*w17);
  /* #153: @42 = (@42+@43) */
  w42 += w43;
  /* #154: @43 = (@5*@16) */
  w43  = (w05*w16);
  /* #155: @42 = (@42-@43) */
  w42 -= w43;
  /* #156: @43 = (@4*@18) */
  w43  = (w04*w18);
  /* #157: @44 = (@5*@40) */
  w44  = (w05*w40);
  /* #158: @43 = (@43-@44) */
  w43 -= w44;
  /* #159: @44 = (@7*@17) */
  w44  = (w07*w17);
  /* #160: @43 = (@43+@44) */
  w43 += w44;
  /* #161: @44 = (@6*@16) */
  w44  = (w06*w16);
  /* #162: @43 = (@43-@44) */
  w43 -= w44;
  /* #163: @40 = (@4*@40) */
  w40  = (w04*w40);
  /* #164: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #165: @40 = (@40+@18) */
  w40 += w18;
  /* #166: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #167: @40 = (@40-@17) */
  w40 -= w17;
  /* #168: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #169: @40 = (@40-@16) */
  w40 -= w16;
  /* #170: @39 = vertcat(@41, @42, @43, @40) */
  rr=w39;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w40;
  /* #171: @41 = dot(@29, @39) */
  w41 = casadi_dot(4, w29, w39);
  /* #172: @41 = (@41/@8) */
  w41 /= w08;
  /* #173: @36 = (@41*@27) */
  for (i=0, rr=w36, cs=w27; i<4; ++i) (*rr++)  = (w41*(*cs++));
  /* #174: @45 = @21; (@45[6:10] += @36) */
  casadi_copy(w21, 13, w45);
  for (rr=w45+6, cs=w36; rr!=w45+10; rr+=1) *rr += *cs++;
  /* #175: @25 = @25' */
  /* #176: @46 = @24' */
  for (i=0, rr=w46, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #177: @37 = mac(@22,@46,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w46+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #178: @37 = @37' */
  /* #179: @25 = (@25+@37) */
  for (i=0, rr=w25, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #180: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #181: (@45[:3] += @25) */
  for (rr=w45+0, cs=w25; rr!=w45+3; rr+=1) *rr += *cs++;
  /* #182: {@42, @43, @40, @16, @17, @18, @44, @47, @48, @49, @50, @51, @52} = vertsplit(@45) */
  w42 = w45[0];
  w43 = w45[1];
  w40 = w45[2];
  w16 = w45[3];
  w17 = w45[4];
  w18 = w45[5];
  w44 = w45[6];
  w47 = w45[7];
  w48 = w45[8];
  w49 = w45[9];
  w50 = w45[10];
  w51 = w45[11];
  w52 = w45[12];
  /* #183: output[1][0] = @42 */
  if (res[1]) res[1][0] = w42;
  /* #184: output[1][1] = @43 */
  if (res[1]) res[1][1] = w43;
  /* #185: output[1][2] = @40 */
  if (res[1]) res[1][2] = w40;
  /* #186: output[1][3] = @16 */
  if (res[1]) res[1][3] = w16;
  /* #187: output[1][4] = @17 */
  if (res[1]) res[1][4] = w17;
  /* #188: output[1][5] = @18 */
  if (res[1]) res[1][5] = w18;
  /* #189: @36 = (@39/@8) */
  for (i=0, rr=w36, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #190: {@18, @17, @16, @40} = vertsplit(@36) */
  w18 = w36[0];
  w17 = w36[1];
  w16 = w36[2];
  w40 = w36[3];
  /* #191: @18 = (@18+@44) */
  w18 += w44;
  /* #192: output[1][6] = @18 */
  if (res[1]) res[1][6] = w18;
  /* #193: @47 = (@47-@17) */
  w47 -= w17;
  /* #194: output[1][7] = @47 */
  if (res[1]) res[1][7] = w47;
  /* #195: @48 = (@48-@16) */
  w48 -= w16;
  /* #196: output[1][8] = @48 */
  if (res[1]) res[1][8] = w48;
  /* #197: @49 = (@49-@40) */
  w49 -= w40;
  /* #198: output[1][9] = @49 */
  if (res[1]) res[1][9] = w49;
  /* #199: output[1][10] = @50 */
  if (res[1]) res[1][10] = w50;
  /* #200: output[1][11] = @51 */
  if (res[1]) res[1][11] = w51;
  /* #201: output[1][12] = @52 */
  if (res[1]) res[1][12] = w52;
  /* #202: @53 = zeros(13x13,25nz) */
  casadi_clear(w53, 25);
  /* #203: @54 = ones(13x1,8nz) */
  casadi_fill(w54, 8, 1.);
  /* #204: {@52, NULL, NULL, NULL, NULL, NULL, @51, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@54) */
  w52 = w54[0];
  w51 = w54[4];
  /* #205: @55 = 00 */
  /* #206: @50 = vertcat(@51, @55, @55, @55) */
  rr=(&w50);
  *rr++ = w51;
  /* #207: @50 = (@50/@8) */
  w50 /= w08;
  /* #208: @56 = dense(@50) */
  casadi_densify((&w50), casadi_s0, w56, 0);
  /* #209: @50 = project(@27) */
  casadi_sparsify(w27, (&w50), casadi_s0, 0);
  /* #210: @51 = sparsity_cast(@51) */
  /* #211: @49 = dot(@50, @51) */
  w49 = casadi_dot(1, (&w50), (&w51));
  /* #212: @49 = (@49/@8) */
  w49 /= w08;
  /* #213: @57 = (@26*@49) */
  for (i=0, rr=w57, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w49);
  /* #214: @56 = (@56-@57) */
  for (i=0, rr=w56, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #215: {@50, @40, @48, @16} = vertsplit(@56) */
  w50 = w56[0];
  w40 = w56[1];
  w48 = w56[2];
  w16 = w56[3];
  /* #216: @47 = (@4*@50) */
  w47  = (w04*w50);
  /* #217: @17 = (@5*@40) */
  w17  = (w05*w40);
  /* #218: @47 = (@47-@17) */
  w47 -= w17;
  /* #219: @17 = (@6*@48) */
  w17  = (w06*w48);
  /* #220: @47 = (@47-@17) */
  w47 -= w17;
  /* #221: @17 = (@7*@16) */
  w17  = (w07*w16);
  /* #222: @47 = (@47-@17) */
  w47 -= w17;
  /* #223: @17 = (@5*@50) */
  w17  = (w05*w50);
  /* #224: @18 = (@4*@40) */
  w18  = (w04*w40);
  /* #225: @17 = (@17+@18) */
  w17 += w18;
  /* #226: @18 = (@7*@48) */
  w18  = (w07*w48);
  /* #227: @17 = (@17+@18) */
  w17 += w18;
  /* #228: @18 = (@6*@16) */
  w18  = (w06*w16);
  /* #229: @17 = (@17-@18) */
  w17 -= w18;
  /* #230: @18 = (@6*@50) */
  w18  = (w06*w50);
  /* #231: @44 = (@7*@40) */
  w44  = (w07*w40);
  /* #232: @18 = (@18-@44) */
  w18 -= w44;
  /* #233: @44 = (@4*@48) */
  w44  = (w04*w48);
  /* #234: @18 = (@18+@44) */
  w18 += w44;
  /* #235: @44 = (@5*@16) */
  w44  = (w05*w16);
  /* #236: @18 = (@18+@44) */
  w18 += w44;
  /* #237: @50 = (@7*@50) */
  w50  = (w07*w50);
  /* #238: @40 = (@6*@40) */
  w40  = (w06*w40);
  /* #239: @50 = (@50+@40) */
  w50 += w40;
  /* #240: @48 = (@5*@48) */
  w48  = (w05*w48);
  /* #241: @50 = (@50-@48) */
  w50 -= w48;
  /* #242: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #243: @50 = (@50+@16) */
  w50 += w16;
  /* #244: @57 = vertcat(@47, @17, @18, @50) */
  rr=w57;
  *rr++ = w47;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w50;
  /* #245: @58 = (-@57) */
  for (i=0, rr=w58, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #246: @58 = (@13?@58:0) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #247: @57 = (@12?@57:0) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #248: @58 = (@58+@57) */
  for (i=0, rr=w58, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #249: @25 = @58[1:4] */
  for (rr=w25, cs=w58+1; cs!=w58+4; cs+=1) *rr++ = *cs;
  /* #250: @47 = dot(@20, @25) */
  w47 = casadi_dot(3, w20, w25);
  /* #251: @47 = (@47/@14) */
  w47 /= w14;
  /* #252: @17 = (@47/@2) */
  w17  = (w47/w02);
  /* #253: @18 = (@0/@2) */
  w18  = (w00/w02);
  /* #254: @50 = (2.*@14) */
  w50 = (2.* w14 );
  /* #255: @16 = (@50*@47) */
  w16  = (w50*w47);
  /* #256: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #257: @48 = @58[0] */
  for (rr=(&w48), cs=w58+0; cs!=w58+1; cs+=1) *rr++ = *cs;
  /* #258: @40 = (@15*@48) */
  w40  = (w15*w48);
  /* #259: @16 = (@16+@40) */
  w16 += w40;
  /* #260: @40 = (@18*@16) */
  w40  = (w18*w16);
  /* #261: @17 = (@17-@40) */
  w17 -= w40;
  /* #262: @17 = (@3*@17) */
  w17  = (w03*w17);
  /* #263: @37 = (2.*@25) */
  for (i=0, rr=w37, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #264: @22 = (@9*@37) */
  for (i=0, rr=w22, cs=w37; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #265: @40 = (@10*@47) */
  w40  = (w10*w47);
  /* #266: @44 = (@0*@48) */
  w44  = (w00*w48);
  /* #267: @40 = (@40-@44) */
  w40 -= w44;
  /* #268: @38 = (@30*@40) */
  for (i=0, rr=w38, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w40);
  /* #269: @22 = (@22+@38) */
  for (i=0, rr=w22, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #270: @22 = (@22/@14) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w14;
  /* #271: @38 = (@31*@47) */
  for (i=0, rr=w38, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #272: @22 = (@22-@38) */
  for (i=0, rr=w22, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #273: @38 = @22' */
  casadi_copy(w22, 3, w38);
  /* #274: @59 = mac(@38,@23,@1) */
  casadi_copy(w01, 3, w59);
  for (i=0, rr=w59; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #275: @59 = @59' */
  /* #276: @60 = mac(@38,@34,@1) */
  casadi_copy(w01, 3, w60);
  for (i=0, rr=w60; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #277: @60 = @60' */
  /* #278: @59 = (@59+@60) */
  for (i=0, rr=w59, cs=w60; i<3; ++i) (*rr++) += (*cs++);
  /* #279: @60 = (@59/@14) */
  for (i=0, rr=w60, cr=w59; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #280: @38 = (@35/@14) */
  for (i=0, rr=w38, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #281: @61 = (@38*@47) */
  for (i=0, rr=w61, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #282: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<3; ++i) (*rr++) -= (*cs++);
  /* #283: @44 = dot(@30, @60) */
  w44 = casadi_dot(3, w30, w60);
  /* #284: @43 = dot(@37, @35) */
  w43 = casadi_dot(3, w37, w35);
  /* #285: @44 = (@44+@43) */
  w44 += w43;
  /* #286: @43 = (@0*@44) */
  w43  = (w00*w44);
  /* #287: @17 = (@17+@43) */
  w17 += w43;
  /* #288: @17 = (-@17) */
  w17 = (- w17 );
  /* #289: @58 = @28; (@58[0] += @17) */
  casadi_copy(w28, 4, w58);
  for (rr=w58+0, cs=(&w17); rr!=w58+1; rr+=1) *rr += *cs++;
  /* #290: @17 = dot(@32, @59) */
  w17 = casadi_dot(3, w32, w59);
  /* #291: @22 = (@22/@14) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w14;
  /* #292: @59 = (@31/@14) */
  for (i=0, rr=w59, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #293: @37 = (@59*@47) */
  for (i=0, rr=w37, cr=w59; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #294: @22 = (@22-@37) */
  for (i=0, rr=w22, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #295: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #296: @43 = dot(@22, @33) */
  w43 = casadi_dot(3, w22, w33);
  /* #297: @17 = (@17+@43) */
  w17 += w43;
  /* #298: @48 = (@48/@2) */
  w48 /= w02;
  /* #299: @43 = (@10/@2) */
  w43  = (w10/w02);
  /* #300: @16 = (@43*@16) */
  w16  = (w43*w16);
  /* #301: @48 = (@48-@16) */
  w48 -= w16;
  /* #302: @48 = (@3*@48) */
  w48  = (w03*w48);
  /* #303: @44 = (@10*@44) */
  w44  = (w10*w44);
  /* #304: @48 = (@48+@44) */
  w48 += w44;
  /* #305: @17 = (@17+@48) */
  w17 += w48;
  /* #306: @17 = (@17/@14) */
  w17 /= w14;
  /* #307: @48 = (@11/@14) */
  w48  = (w11/w14);
  /* #308: @47 = (@48*@47) */
  w47  = (w48*w47);
  /* #309: @17 = (@17-@47) */
  w17 -= w47;
  /* #310: @22 = (@20*@17) */
  for (i=0, rr=w22, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #311: @25 = (@11*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #312: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #313: @25 = (@35*@40) */
  for (i=0, rr=w25, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w40);
  /* #314: @60 = (@9*@60) */
  for (i=0, rr=w60, cs=w60; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #315: @25 = (@25+@60) */
  for (i=0, rr=w25, cs=w60; i<3; ++i) (*rr++) += (*cs++);
  /* #316: @25 = (2.*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #317: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #318: (@58[1:4] += @22) */
  for (rr=w58+1, cs=w22; rr!=w58+4; rr+=1) *rr += *cs++;
  /* #319: @57 = (@12?@58:0) */
  for (i=0, rr=w57, cs=w58; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #320: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) *rr++ = (- *cs++ );
  /* #321: @58 = (@13?@58:0) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #322: @57 = (@57+@58) */
  for (i=0, rr=w57, cs=w58; i<4; ++i) (*rr++) += (*cs++);
  /* #323: {@40, @17, @47, @44} = vertsplit(@57) */
  w40 = w57[0];
  w17 = w57[1];
  w47 = w57[2];
  w44 = w57[3];
  /* #324: @16 = (@7*@44) */
  w16  = (w07*w44);
  /* #325: @42 = (@6*@47) */
  w42  = (w06*w47);
  /* #326: @16 = (@16+@42) */
  w16 += w42;
  /* #327: @42 = (@5*@17) */
  w42  = (w05*w17);
  /* #328: @16 = (@16+@42) */
  w16 += w42;
  /* #329: @42 = (@4*@40) */
  w42  = (w04*w40);
  /* #330: @16 = (@16+@42) */
  w16 += w42;
  /* #331: @42 = (@6*@44) */
  w42  = (w06*w44);
  /* #332: @62 = (@7*@47) */
  w62  = (w07*w47);
  /* #333: @42 = (@42-@62) */
  w42 -= w62;
  /* #334: @62 = (@4*@17) */
  w62  = (w04*w17);
  /* #335: @42 = (@42+@62) */
  w42 += w62;
  /* #336: @62 = (@5*@40) */
  w62  = (w05*w40);
  /* #337: @42 = (@42-@62) */
  w42 -= w62;
  /* #338: @62 = (@4*@47) */
  w62  = (w04*w47);
  /* #339: @63 = (@5*@44) */
  w63  = (w05*w44);
  /* #340: @62 = (@62-@63) */
  w62 -= w63;
  /* #341: @63 = (@7*@17) */
  w63  = (w07*w17);
  /* #342: @62 = (@62+@63) */
  w62 += w63;
  /* #343: @63 = (@6*@40) */
  w63  = (w06*w40);
  /* #344: @62 = (@62-@63) */
  w62 -= w63;
  /* #345: @44 = (@4*@44) */
  w44  = (w04*w44);
  /* #346: @47 = (@5*@47) */
  w47  = (w05*w47);
  /* #347: @44 = (@44+@47) */
  w44 += w47;
  /* #348: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #349: @44 = (@44-@17) */
  w44 -= w17;
  /* #350: @40 = (@7*@40) */
  w40  = (w07*w40);
  /* #351: @44 = (@44-@40) */
  w44 -= w40;
  /* #352: @57 = vertcat(@16, @42, @62, @44) */
  rr=w57;
  *rr++ = w16;
  *rr++ = w42;
  *rr++ = w62;
  *rr++ = w44;
  /* #353: @16 = dot(@29, @57) */
  w16 = casadi_dot(4, w29, w57);
  /* #354: @56 = (@56/@8) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) /= w08;
  /* #355: @58 = (@26/@8) */
  for (i=0, rr=w58, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #356: @64 = (@58*@49) */
  for (i=0, rr=w64, cr=w58; i<4; ++i) (*rr++)  = ((*cr++)*w49);
  /* #357: @56 = (@56-@64) */
  for (i=0, rr=w56, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #358: @56 = (-@56) */
  for (i=0, rr=w56, cs=w56; i<4; ++i) *rr++ = (- *cs++ );
  /* #359: @42 = dot(@56, @39) */
  w42 = casadi_dot(4, w56, w39);
  /* #360: @16 = (@16+@42) */
  w16 += w42;
  /* #361: @16 = (@16/@8) */
  w16 /= w08;
  /* #362: @42 = (@41/@8) */
  w42  = (w41/w08);
  /* #363: @62 = (@42*@49) */
  w62  = (w42*w49);
  /* #364: @16 = (@16-@62) */
  w16 -= w62;
  /* #365: @56 = (@27*@16) */
  for (i=0, rr=w56, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #366: @51 = (@41*@51) */
  w51  = (w41*w51);
  /* #367: @64 = dense(@51) */
  casadi_densify((&w51), casadi_s0, w64, 0);
  /* #368: @56 = (@56+@64) */
  for (i=0, rr=w56, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #369: @45 = @21; (@45[6:10] += @56) */
  casadi_copy(w21, 13, w45);
  for (rr=w45+6, cs=w56; rr!=w45+10; rr+=1) *rr += *cs++;
  /* #370: @52 = sparsity_cast(@52) */
  /* #371: @52 = (-@52) */
  w52 = (- w52 );
  /* #372: @52 = @52' */
  /* #373: @22 = mac(@52,@24,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w52), casadi_s3, w24, casadi_s2, w22, casadi_s1, w, 0);
  /* #374: @22 = @22' */
  /* #375: @25 = mac(@52,@46,@1) */
  casadi_copy(w01, 3, w25);
  casadi_mtimes((&w52), casadi_s3, w46, casadi_s2, w25, casadi_s1, w, 0);
  /* #376: @25 = @25' */
  /* #377: @22 = (@22+@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #378: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #379: (@45[:3] += @22) */
  for (rr=w45+0, cs=w22; rr!=w45+3; rr+=1) *rr += *cs++;
  /* #380: {@52, @51, @16, @62, @44, @40, @17, @47, @63, @65, @66, @67, @68} = vertsplit(@45) */
  w52 = w45[0];
  w51 = w45[1];
  w16 = w45[2];
  w62 = w45[3];
  w44 = w45[4];
  w40 = w45[5];
  w17 = w45[6];
  w47 = w45[7];
  w63 = w45[8];
  w65 = w45[9];
  w66 = w45[10];
  w67 = w45[11];
  w68 = w45[12];
  /* #381: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w08;
  /* #382: @36 = (@36/@8) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w08;
  /* #383: @56 = (@36*@49) */
  for (i=0, rr=w56, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w49);
  /* #384: @57 = (@57-@56) */
  for (i=0, rr=w57, cs=w56; i<4; ++i) (*rr++) -= (*cs++);
  /* #385: {@49, @69, @70, @71} = vertsplit(@57) */
  w49 = w57[0];
  w69 = w57[1];
  w70 = w57[2];
  w71 = w57[3];
  /* #386: @49 = (@49+@17) */
  w49 += w17;
  /* #387: @47 = (@47-@69) */
  w47 -= w69;
  /* #388: @63 = (@63-@70) */
  w63 -= w70;
  /* #389: @65 = (@65-@71) */
  w65 -= w71;
  /* #390: @45 = vertcat(@52, @51, @16, @62, @44, @40, @49, @47, @63, @65, @66, @67, @68) */
  rr=w45;
  *rr++ = w52;
  *rr++ = w51;
  *rr++ = w16;
  *rr++ = w62;
  *rr++ = w44;
  *rr++ = w40;
  *rr++ = w49;
  *rr++ = w47;
  *rr++ = w63;
  *rr++ = w65;
  *rr++ = w66;
  *rr++ = w67;
  *rr++ = w68;
  /* #391: @72 = @45[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w72, cs=w45; cii!=casadi_s4+7; ++cii) *rr++ = cs[*cii];
  /* #392: (@53[0, 1, 2, 9, 10, 11, 12] = @72) */
  for (cii=casadi_s5, rr=w53, cs=w72; cii!=casadi_s5+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #393: (@53[0, 3, 6, 9, 13, 17, 21] = @72) */
  for (cii=casadi_s6, rr=w53, cs=w72; cii!=casadi_s6+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #394: @73 = ones(13x1,2nz) */
  casadi_fill(w73, 2, 1.);
  /* #395: {NULL, @52, NULL, NULL, NULL, NULL, NULL, @51, NULL, NULL, NULL, NULL, NULL} = vertsplit(@73) */
  w52 = w73[0];
  w51 = w73[1];
  /* #396: @16 = (-@51) */
  w16 = (- w51 );
  /* #397: @62 = vertcat(@55, @16, @55, @55) */
  rr=(&w62);
  *rr++ = w16;
  /* #398: @62 = (@62/@8) */
  w62 /= w08;
  /* #399: @57 = dense(@62) */
  casadi_densify((&w62), casadi_s7, w57, 0);
  /* #400: @62 = project(@27) */
  casadi_sparsify(w27, (&w62), casadi_s7, 0);
  /* #401: @51 = sparsity_cast(@51) */
  /* #402: @16 = dot(@62, @51) */
  w16 = casadi_dot(1, (&w62), (&w51));
  /* #403: @16 = (@16/@8) */
  w16 /= w08;
  /* #404: @56 = (@26*@16) */
  for (i=0, rr=w56, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #405: @57 = (@57-@56) */
  for (i=0, rr=w57, cs=w56; i<4; ++i) (*rr++) -= (*cs++);
  /* #406: {@62, @44, @40, @49} = vertsplit(@57) */
  w62 = w57[0];
  w44 = w57[1];
  w40 = w57[2];
  w49 = w57[3];
  /* #407: @47 = (@4*@62) */
  w47  = (w04*w62);
  /* #408: @63 = (@5*@44) */
  w63  = (w05*w44);
  /* #409: @47 = (@47-@63) */
  w47 -= w63;
  /* #410: @63 = (@6*@40) */
  w63  = (w06*w40);
  /* #411: @47 = (@47-@63) */
  w47 -= w63;
  /* #412: @63 = (@7*@49) */
  w63  = (w07*w49);
  /* #413: @47 = (@47-@63) */
  w47 -= w63;
  /* #414: @63 = (@5*@62) */
  w63  = (w05*w62);
  /* #415: @65 = (@4*@44) */
  w65  = (w04*w44);
  /* #416: @63 = (@63+@65) */
  w63 += w65;
  /* #417: @65 = (@7*@40) */
  w65  = (w07*w40);
  /* #418: @63 = (@63+@65) */
  w63 += w65;
  /* #419: @65 = (@6*@49) */
  w65  = (w06*w49);
  /* #420: @63 = (@63-@65) */
  w63 -= w65;
  /* #421: @65 = (@6*@62) */
  w65  = (w06*w62);
  /* #422: @66 = (@7*@44) */
  w66  = (w07*w44);
  /* #423: @65 = (@65-@66) */
  w65 -= w66;
  /* #424: @66 = (@4*@40) */
  w66  = (w04*w40);
  /* #425: @65 = (@65+@66) */
  w65 += w66;
  /* #426: @66 = (@5*@49) */
  w66  = (w05*w49);
  /* #427: @65 = (@65+@66) */
  w65 += w66;
  /* #428: @62 = (@7*@62) */
  w62  = (w07*w62);
  /* #429: @44 = (@6*@44) */
  w44  = (w06*w44);
  /* #430: @62 = (@62+@44) */
  w62 += w44;
  /* #431: @40 = (@5*@40) */
  w40  = (w05*w40);
  /* #432: @62 = (@62-@40) */
  w62 -= w40;
  /* #433: @49 = (@4*@49) */
  w49  = (w04*w49);
  /* #434: @62 = (@62+@49) */
  w62 += w49;
  /* #435: @56 = vertcat(@47, @63, @65, @62) */
  rr=w56;
  *rr++ = w47;
  *rr++ = w63;
  *rr++ = w65;
  *rr++ = w62;
  /* #436: @64 = (-@56) */
  for (i=0, rr=w64, cs=w56; i<4; ++i) *rr++ = (- *cs++ );
  /* #437: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #438: @56 = (@12?@56:0) */
  for (i=0, rr=w56, cs=w56; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #439: @64 = (@64+@56) */
  for (i=0, rr=w64, cs=w56; i<4; ++i) (*rr++) += (*cs++);
  /* #440: @22 = @64[1:4] */
  for (rr=w22, cs=w64+1; cs!=w64+4; cs+=1) *rr++ = *cs;
  /* #441: @47 = dot(@20, @22) */
  w47 = casadi_dot(3, w20, w22);
  /* #442: @47 = (@47/@14) */
  w47 /= w14;
  /* #443: @63 = (@47/@2) */
  w63  = (w47/w02);
  /* #444: @65 = (@50*@47) */
  w65  = (w50*w47);
  /* #445: @62 = @64[0] */
  for (rr=(&w62), cs=w64+0; cs!=w64+1; cs+=1) *rr++ = *cs;
  /* #446: @49 = (@15*@62) */
  w49  = (w15*w62);
  /* #447: @65 = (@65+@49) */
  w65 += w49;
  /* #448: @49 = (@18*@65) */
  w49  = (w18*w65);
  /* #449: @63 = (@63-@49) */
  w63 -= w49;
  /* #450: @63 = (@3*@63) */
  w63  = (w03*w63);
  /* #451: @25 = (2.*@22) */
  for (i=0, rr=w25, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #452: @60 = (@9*@25) */
  for (i=0, rr=w60, cs=w25; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #453: @49 = (@10*@47) */
  w49  = (w10*w47);
  /* #454: @40 = (@0*@62) */
  w40  = (w00*w62);
  /* #455: @49 = (@49-@40) */
  w49 -= w40;
  /* #456: @37 = (@30*@49) */
  for (i=0, rr=w37, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w49);
  /* #457: @60 = (@60+@37) */
  for (i=0, rr=w60, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #458: @60 = (@60/@14) */
  for (i=0, rr=w60; i<3; ++i) (*rr++) /= w14;
  /* #459: @37 = (@31*@47) */
  for (i=0, rr=w37, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #460: @60 = (@60-@37) */
  for (i=0, rr=w60, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #461: @37 = @60' */
  casadi_copy(w60, 3, w37);
  /* #462: @61 = mac(@37,@23,@1) */
  casadi_copy(w01, 3, w61);
  for (i=0, rr=w61; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #463: @61 = @61' */
  /* #464: @74 = mac(@37,@34,@1) */
  casadi_copy(w01, 3, w74);
  for (i=0, rr=w74; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #465: @74 = @74' */
  /* #466: @61 = (@61+@74) */
  for (i=0, rr=w61, cs=w74; i<3; ++i) (*rr++) += (*cs++);
  /* #467: @74 = (@61/@14) */
  for (i=0, rr=w74, cr=w61; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #468: @37 = (@38*@47) */
  for (i=0, rr=w37, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #469: @74 = (@74-@37) */
  for (i=0, rr=w74, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #470: @40 = dot(@30, @74) */
  w40 = casadi_dot(3, w30, w74);
  /* #471: @44 = dot(@25, @35) */
  w44 = casadi_dot(3, w25, w35);
  /* #472: @40 = (@40+@44) */
  w40 += w44;
  /* #473: @44 = (@0*@40) */
  w44  = (w00*w40);
  /* #474: @63 = (@63+@44) */
  w63 += w44;
  /* #475: @63 = (-@63) */
  w63 = (- w63 );
  /* #476: @64 = @28; (@64[0] += @63) */
  casadi_copy(w28, 4, w64);
  for (rr=w64+0, cs=(&w63); rr!=w64+1; rr+=1) *rr += *cs++;
  /* #477: @63 = dot(@32, @61) */
  w63 = casadi_dot(3, w32, w61);
  /* #478: @60 = (@60/@14) */
  for (i=0, rr=w60; i<3; ++i) (*rr++) /= w14;
  /* #479: @61 = (@59*@47) */
  for (i=0, rr=w61, cr=w59; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #480: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<3; ++i) (*rr++) -= (*cs++);
  /* #481: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<3; ++i) *rr++ = (- *cs++ );
  /* #482: @44 = dot(@60, @33) */
  w44 = casadi_dot(3, w60, w33);
  /* #483: @63 = (@63+@44) */
  w63 += w44;
  /* #484: @62 = (@62/@2) */
  w62 /= w02;
  /* #485: @65 = (@43*@65) */
  w65  = (w43*w65);
  /* #486: @62 = (@62-@65) */
  w62 -= w65;
  /* #487: @62 = (@3*@62) */
  w62  = (w03*w62);
  /* #488: @40 = (@10*@40) */
  w40  = (w10*w40);
  /* #489: @62 = (@62+@40) */
  w62 += w40;
  /* #490: @63 = (@63+@62) */
  w63 += w62;
  /* #491: @63 = (@63/@14) */
  w63 /= w14;
  /* #492: @47 = (@48*@47) */
  w47  = (w48*w47);
  /* #493: @63 = (@63-@47) */
  w63 -= w47;
  /* #494: @60 = (@20*@63) */
  for (i=0, rr=w60, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #495: @22 = (@11*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #496: @60 = (@60+@22) */
  for (i=0, rr=w60, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #497: @22 = (@35*@49) */
  for (i=0, rr=w22, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w49);
  /* #498: @74 = (@9*@74) */
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #499: @22 = (@22+@74) */
  for (i=0, rr=w22, cs=w74; i<3; ++i) (*rr++) += (*cs++);
  /* #500: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #501: @60 = (@60+@22) */
  for (i=0, rr=w60, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #502: (@64[1:4] += @60) */
  for (rr=w64+1, cs=w60; rr!=w64+4; rr+=1) *rr += *cs++;
  /* #503: @56 = (@12?@64:0) */
  for (i=0, rr=w56, cs=w64; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #504: @64 = (-@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) *rr++ = (- *cs++ );
  /* #505: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #506: @56 = (@56+@64) */
  for (i=0, rr=w56, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #507: {@49, @63, @47, @62} = vertsplit(@56) */
  w49 = w56[0];
  w63 = w56[1];
  w47 = w56[2];
  w62 = w56[3];
  /* #508: @40 = (@7*@62) */
  w40  = (w07*w62);
  /* #509: @65 = (@6*@47) */
  w65  = (w06*w47);
  /* #510: @40 = (@40+@65) */
  w40 += w65;
  /* #511: @65 = (@5*@63) */
  w65  = (w05*w63);
  /* #512: @40 = (@40+@65) */
  w40 += w65;
  /* #513: @65 = (@4*@49) */
  w65  = (w04*w49);
  /* #514: @40 = (@40+@65) */
  w40 += w65;
  /* #515: @65 = (@6*@62) */
  w65  = (w06*w62);
  /* #516: @44 = (@7*@47) */
  w44  = (w07*w47);
  /* #517: @65 = (@65-@44) */
  w65 -= w44;
  /* #518: @44 = (@4*@63) */
  w44  = (w04*w63);
  /* #519: @65 = (@65+@44) */
  w65 += w44;
  /* #520: @44 = (@5*@49) */
  w44  = (w05*w49);
  /* #521: @65 = (@65-@44) */
  w65 -= w44;
  /* #522: @44 = (@4*@47) */
  w44  = (w04*w47);
  /* #523: @66 = (@5*@62) */
  w66  = (w05*w62);
  /* #524: @44 = (@44-@66) */
  w44 -= w66;
  /* #525: @66 = (@7*@63) */
  w66  = (w07*w63);
  /* #526: @44 = (@44+@66) */
  w44 += w66;
  /* #527: @66 = (@6*@49) */
  w66  = (w06*w49);
  /* #528: @44 = (@44-@66) */
  w44 -= w66;
  /* #529: @62 = (@4*@62) */
  w62  = (w04*w62);
  /* #530: @47 = (@5*@47) */
  w47  = (w05*w47);
  /* #531: @62 = (@62+@47) */
  w62 += w47;
  /* #532: @63 = (@6*@63) */
  w63  = (w06*w63);
  /* #533: @62 = (@62-@63) */
  w62 -= w63;
  /* #534: @49 = (@7*@49) */
  w49  = (w07*w49);
  /* #535: @62 = (@62-@49) */
  w62 -= w49;
  /* #536: @56 = vertcat(@40, @65, @44, @62) */
  rr=w56;
  *rr++ = w40;
  *rr++ = w65;
  *rr++ = w44;
  *rr++ = w62;
  /* #537: @40 = dot(@29, @56) */
  w40 = casadi_dot(4, w29, w56);
  /* #538: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w08;
  /* #539: @64 = (@58*@16) */
  for (i=0, rr=w64, cr=w58; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #540: @57 = (@57-@64) */
  for (i=0, rr=w57, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #541: @57 = (-@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #542: @65 = dot(@57, @39) */
  w65 = casadi_dot(4, w57, w39);
  /* #543: @40 = (@40+@65) */
  w40 += w65;
  /* #544: @40 = (@40/@8) */
  w40 /= w08;
  /* #545: @65 = (@42*@16) */
  w65  = (w42*w16);
  /* #546: @40 = (@40-@65) */
  w40 -= w65;
  /* #547: @57 = (@27*@40) */
  for (i=0, rr=w57, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w40);
  /* #548: @51 = (@41*@51) */
  w51  = (w41*w51);
  /* #549: @64 = dense(@51) */
  casadi_densify((&w51), casadi_s7, w64, 0);
  /* #550: @57 = (@57+@64) */
  for (i=0, rr=w57, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #551: @45 = @21; (@45[6:10] += @57) */
  casadi_copy(w21, 13, w45);
  for (rr=w45+6, cs=w57; rr!=w45+10; rr+=1) *rr += *cs++;
  /* #552: @52 = sparsity_cast(@52) */
  /* #553: @52 = (-@52) */
  w52 = (- w52 );
  /* #554: @52 = @52' */
  /* #555: @60 = mac(@52,@24,@1) */
  casadi_copy(w01, 3, w60);
  casadi_mtimes((&w52), casadi_s8, w24, casadi_s2, w60, casadi_s1, w, 0);
  /* #556: @60 = @60' */
  /* #557: @22 = mac(@52,@46,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w52), casadi_s8, w46, casadi_s2, w22, casadi_s1, w, 0);
  /* #558: @22 = @22' */
  /* #559: @60 = (@60+@22) */
  for (i=0, rr=w60, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #560: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<3; ++i) *rr++ = (- *cs++ );
  /* #561: (@45[:3] += @60) */
  for (rr=w45+0, cs=w60; rr!=w45+3; rr+=1) *rr += *cs++;
  /* #562: {@52, @51, @40, @65, @44, @62, @49, @63, @47, @66, @67, @68, @71} = vertsplit(@45) */
  w52 = w45[0];
  w51 = w45[1];
  w40 = w45[2];
  w65 = w45[3];
  w44 = w45[4];
  w62 = w45[5];
  w49 = w45[6];
  w63 = w45[7];
  w47 = w45[8];
  w66 = w45[9];
  w67 = w45[10];
  w68 = w45[11];
  w71 = w45[12];
  /* #563: @56 = (@56/@8) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) /= w08;
  /* #564: @57 = (@36*@16) */
  for (i=0, rr=w57, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #565: @56 = (@56-@57) */
  for (i=0, rr=w56, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #566: {@16, @70, @69, @17} = vertsplit(@56) */
  w16 = w56[0];
  w70 = w56[1];
  w69 = w56[2];
  w17 = w56[3];
  /* #567: @16 = (@16+@49) */
  w16 += w49;
  /* #568: @63 = (@63-@70) */
  w63 -= w70;
  /* #569: @47 = (@47-@69) */
  w47 -= w69;
  /* #570: @66 = (@66-@17) */
  w66 -= w17;
  /* #571: @45 = vertcat(@52, @51, @40, @65, @44, @62, @16, @63, @47, @66, @67, @68, @71) */
  rr=w45;
  *rr++ = w52;
  *rr++ = w51;
  *rr++ = w40;
  *rr++ = w65;
  *rr++ = w44;
  *rr++ = w62;
  *rr++ = w16;
  *rr++ = w63;
  *rr++ = w47;
  *rr++ = w66;
  *rr++ = w67;
  *rr++ = w68;
  *rr++ = w71;
  /* #572: @72 = @45[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w72, cs=w45; cii!=casadi_s4+7; ++cii) *rr++ = cs[*cii];
  /* #573: (@53[3, 4, 5, 13, 14, 15, 16] = @72) */
  for (cii=casadi_s9, rr=w53, cs=w72; cii!=casadi_s9+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #574: (@53[1, 4, 7, 10, 14, 18, 22] = @72) */
  for (cii=casadi_s10, rr=w53, cs=w72; cii!=casadi_s10+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #575: @73 = ones(13x1,2nz) */
  casadi_fill(w73, 2, 1.);
  /* #576: {NULL, NULL, @52, NULL, NULL, NULL, NULL, NULL, @51, NULL, NULL, NULL, NULL} = vertsplit(@73) */
  w52 = w73[0];
  w51 = w73[1];
  /* #577: @40 = (-@51) */
  w40 = (- w51 );
  /* #578: @65 = vertcat(@55, @55, @40, @55) */
  rr=(&w65);
  *rr++ = w40;
  /* #579: @65 = (@65/@8) */
  w65 /= w08;
  /* #580: @56 = dense(@65) */
  casadi_densify((&w65), casadi_s11, w56, 0);
  /* #581: @65 = project(@27) */
  casadi_sparsify(w27, (&w65), casadi_s11, 0);
  /* #582: @51 = sparsity_cast(@51) */
  /* #583: @40 = dot(@65, @51) */
  w40 = casadi_dot(1, (&w65), (&w51));
  /* #584: @40 = (@40/@8) */
  w40 /= w08;
  /* #585: @57 = (@26*@40) */
  for (i=0, rr=w57, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w40);
  /* #586: @56 = (@56-@57) */
  for (i=0, rr=w56, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #587: {@65, @44, @62, @16} = vertsplit(@56) */
  w65 = w56[0];
  w44 = w56[1];
  w62 = w56[2];
  w16 = w56[3];
  /* #588: @63 = (@4*@65) */
  w63  = (w04*w65);
  /* #589: @47 = (@5*@44) */
  w47  = (w05*w44);
  /* #590: @63 = (@63-@47) */
  w63 -= w47;
  /* #591: @47 = (@6*@62) */
  w47  = (w06*w62);
  /* #592: @63 = (@63-@47) */
  w63 -= w47;
  /* #593: @47 = (@7*@16) */
  w47  = (w07*w16);
  /* #594: @63 = (@63-@47) */
  w63 -= w47;
  /* #595: @47 = (@5*@65) */
  w47  = (w05*w65);
  /* #596: @66 = (@4*@44) */
  w66  = (w04*w44);
  /* #597: @47 = (@47+@66) */
  w47 += w66;
  /* #598: @66 = (@7*@62) */
  w66  = (w07*w62);
  /* #599: @47 = (@47+@66) */
  w47 += w66;
  /* #600: @66 = (@6*@16) */
  w66  = (w06*w16);
  /* #601: @47 = (@47-@66) */
  w47 -= w66;
  /* #602: @66 = (@6*@65) */
  w66  = (w06*w65);
  /* #603: @67 = (@7*@44) */
  w67  = (w07*w44);
  /* #604: @66 = (@66-@67) */
  w66 -= w67;
  /* #605: @67 = (@4*@62) */
  w67  = (w04*w62);
  /* #606: @66 = (@66+@67) */
  w66 += w67;
  /* #607: @67 = (@5*@16) */
  w67  = (w05*w16);
  /* #608: @66 = (@66+@67) */
  w66 += w67;
  /* #609: @65 = (@7*@65) */
  w65  = (w07*w65);
  /* #610: @44 = (@6*@44) */
  w44  = (w06*w44);
  /* #611: @65 = (@65+@44) */
  w65 += w44;
  /* #612: @62 = (@5*@62) */
  w62  = (w05*w62);
  /* #613: @65 = (@65-@62) */
  w65 -= w62;
  /* #614: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #615: @65 = (@65+@16) */
  w65 += w16;
  /* #616: @57 = vertcat(@63, @47, @66, @65) */
  rr=w57;
  *rr++ = w63;
  *rr++ = w47;
  *rr++ = w66;
  *rr++ = w65;
  /* #617: @64 = (-@57) */
  for (i=0, rr=w64, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #618: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #619: @57 = (@12?@57:0) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #620: @64 = (@64+@57) */
  for (i=0, rr=w64, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #621: @60 = @64[1:4] */
  for (rr=w60, cs=w64+1; cs!=w64+4; cs+=1) *rr++ = *cs;
  /* #622: @63 = dot(@20, @60) */
  w63 = casadi_dot(3, w20, w60);
  /* #623: @63 = (@63/@14) */
  w63 /= w14;
  /* #624: @47 = (@63/@2) */
  w47  = (w63/w02);
  /* #625: @66 = (@50*@63) */
  w66  = (w50*w63);
  /* #626: @65 = @64[0] */
  for (rr=(&w65), cs=w64+0; cs!=w64+1; cs+=1) *rr++ = *cs;
  /* #627: @16 = (@15*@65) */
  w16  = (w15*w65);
  /* #628: @66 = (@66+@16) */
  w66 += w16;
  /* #629: @16 = (@18*@66) */
  w16  = (w18*w66);
  /* #630: @47 = (@47-@16) */
  w47 -= w16;
  /* #631: @47 = (@3*@47) */
  w47  = (w03*w47);
  /* #632: @22 = (2.*@60) */
  for (i=0, rr=w22, cs=w60; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #633: @74 = (@9*@22) */
  for (i=0, rr=w74, cs=w22; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #634: @16 = (@10*@63) */
  w16  = (w10*w63);
  /* #635: @62 = (@0*@65) */
  w62  = (w00*w65);
  /* #636: @16 = (@16-@62) */
  w16 -= w62;
  /* #637: @61 = (@30*@16) */
  for (i=0, rr=w61, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w16);
  /* #638: @74 = (@74+@61) */
  for (i=0, rr=w74, cs=w61; i<3; ++i) (*rr++) += (*cs++);
  /* #639: @74 = (@74/@14) */
  for (i=0, rr=w74; i<3; ++i) (*rr++) /= w14;
  /* #640: @61 = (@31*@63) */
  for (i=0, rr=w61, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #641: @74 = (@74-@61) */
  for (i=0, rr=w74, cs=w61; i<3; ++i) (*rr++) -= (*cs++);
  /* #642: @61 = @74' */
  casadi_copy(w74, 3, w61);
  /* #643: @25 = mac(@61,@23,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w61+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #644: @25 = @25' */
  /* #645: @37 = mac(@61,@34,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w61+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #646: @37 = @37' */
  /* #647: @25 = (@25+@37) */
  for (i=0, rr=w25, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #648: @37 = (@25/@14) */
  for (i=0, rr=w37, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #649: @61 = (@38*@63) */
  for (i=0, rr=w61, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #650: @37 = (@37-@61) */
  for (i=0, rr=w37, cs=w61; i<3; ++i) (*rr++) -= (*cs++);
  /* #651: @62 = dot(@30, @37) */
  w62 = casadi_dot(3, w30, w37);
  /* #652: @44 = dot(@22, @35) */
  w44 = casadi_dot(3, w22, w35);
  /* #653: @62 = (@62+@44) */
  w62 += w44;
  /* #654: @44 = (@0*@62) */
  w44  = (w00*w62);
  /* #655: @47 = (@47+@44) */
  w47 += w44;
  /* #656: @47 = (-@47) */
  w47 = (- w47 );
  /* #657: @64 = @28; (@64[0] += @47) */
  casadi_copy(w28, 4, w64);
  for (rr=w64+0, cs=(&w47); rr!=w64+1; rr+=1) *rr += *cs++;
  /* #658: @47 = dot(@32, @25) */
  w47 = casadi_dot(3, w32, w25);
  /* #659: @74 = (@74/@14) */
  for (i=0, rr=w74; i<3; ++i) (*rr++) /= w14;
  /* #660: @25 = (@59*@63) */
  for (i=0, rr=w25, cr=w59; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #661: @74 = (@74-@25) */
  for (i=0, rr=w74, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #662: @74 = (-@74) */
  for (i=0, rr=w74, cs=w74; i<3; ++i) *rr++ = (- *cs++ );
  /* #663: @44 = dot(@74, @33) */
  w44 = casadi_dot(3, w74, w33);
  /* #664: @47 = (@47+@44) */
  w47 += w44;
  /* #665: @65 = (@65/@2) */
  w65 /= w02;
  /* #666: @66 = (@43*@66) */
  w66  = (w43*w66);
  /* #667: @65 = (@65-@66) */
  w65 -= w66;
  /* #668: @65 = (@3*@65) */
  w65  = (w03*w65);
  /* #669: @62 = (@10*@62) */
  w62  = (w10*w62);
  /* #670: @65 = (@65+@62) */
  w65 += w62;
  /* #671: @47 = (@47+@65) */
  w47 += w65;
  /* #672: @47 = (@47/@14) */
  w47 /= w14;
  /* #673: @63 = (@48*@63) */
  w63  = (w48*w63);
  /* #674: @47 = (@47-@63) */
  w47 -= w63;
  /* #675: @74 = (@20*@47) */
  for (i=0, rr=w74, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #676: @60 = (@11*@60) */
  for (i=0, rr=w60, cs=w60; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #677: @74 = (@74+@60) */
  for (i=0, rr=w74, cs=w60; i<3; ++i) (*rr++) += (*cs++);
  /* #678: @60 = (@35*@16) */
  for (i=0, rr=w60, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w16);
  /* #679: @37 = (@9*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #680: @60 = (@60+@37) */
  for (i=0, rr=w60, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #681: @60 = (2.*@60) */
  for (i=0, rr=w60, cs=w60; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #682: @74 = (@74+@60) */
  for (i=0, rr=w74, cs=w60; i<3; ++i) (*rr++) += (*cs++);
  /* #683: (@64[1:4] += @74) */
  for (rr=w64+1, cs=w74; rr!=w64+4; rr+=1) *rr += *cs++;
  /* #684: @57 = (@12?@64:0) */
  for (i=0, rr=w57, cs=w64; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #685: @64 = (-@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) *rr++ = (- *cs++ );
  /* #686: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #687: @57 = (@57+@64) */
  for (i=0, rr=w57, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #688: {@16, @47, @63, @65} = vertsplit(@57) */
  w16 = w57[0];
  w47 = w57[1];
  w63 = w57[2];
  w65 = w57[3];
  /* #689: @62 = (@7*@65) */
  w62  = (w07*w65);
  /* #690: @66 = (@6*@63) */
  w66  = (w06*w63);
  /* #691: @62 = (@62+@66) */
  w62 += w66;
  /* #692: @66 = (@5*@47) */
  w66  = (w05*w47);
  /* #693: @62 = (@62+@66) */
  w62 += w66;
  /* #694: @66 = (@4*@16) */
  w66  = (w04*w16);
  /* #695: @62 = (@62+@66) */
  w62 += w66;
  /* #696: @66 = (@6*@65) */
  w66  = (w06*w65);
  /* #697: @44 = (@7*@63) */
  w44  = (w07*w63);
  /* #698: @66 = (@66-@44) */
  w66 -= w44;
  /* #699: @44 = (@4*@47) */
  w44  = (w04*w47);
  /* #700: @66 = (@66+@44) */
  w66 += w44;
  /* #701: @44 = (@5*@16) */
  w44  = (w05*w16);
  /* #702: @66 = (@66-@44) */
  w66 -= w44;
  /* #703: @44 = (@4*@63) */
  w44  = (w04*w63);
  /* #704: @67 = (@5*@65) */
  w67  = (w05*w65);
  /* #705: @44 = (@44-@67) */
  w44 -= w67;
  /* #706: @67 = (@7*@47) */
  w67  = (w07*w47);
  /* #707: @44 = (@44+@67) */
  w44 += w67;
  /* #708: @67 = (@6*@16) */
  w67  = (w06*w16);
  /* #709: @44 = (@44-@67) */
  w44 -= w67;
  /* #710: @65 = (@4*@65) */
  w65  = (w04*w65);
  /* #711: @63 = (@5*@63) */
  w63  = (w05*w63);
  /* #712: @65 = (@65+@63) */
  w65 += w63;
  /* #713: @47 = (@6*@47) */
  w47  = (w06*w47);
  /* #714: @65 = (@65-@47) */
  w65 -= w47;
  /* #715: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #716: @65 = (@65-@16) */
  w65 -= w16;
  /* #717: @57 = vertcat(@62, @66, @44, @65) */
  rr=w57;
  *rr++ = w62;
  *rr++ = w66;
  *rr++ = w44;
  *rr++ = w65;
  /* #718: @62 = dot(@29, @57) */
  w62 = casadi_dot(4, w29, w57);
  /* #719: @56 = (@56/@8) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) /= w08;
  /* #720: @64 = (@58*@40) */
  for (i=0, rr=w64, cr=w58; i<4; ++i) (*rr++)  = ((*cr++)*w40);
  /* #721: @56 = (@56-@64) */
  for (i=0, rr=w56, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #722: @56 = (-@56) */
  for (i=0, rr=w56, cs=w56; i<4; ++i) *rr++ = (- *cs++ );
  /* #723: @66 = dot(@56, @39) */
  w66 = casadi_dot(4, w56, w39);
  /* #724: @62 = (@62+@66) */
  w62 += w66;
  /* #725: @62 = (@62/@8) */
  w62 /= w08;
  /* #726: @66 = (@42*@40) */
  w66  = (w42*w40);
  /* #727: @62 = (@62-@66) */
  w62 -= w66;
  /* #728: @56 = (@27*@62) */
  for (i=0, rr=w56, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w62);
  /* #729: @51 = (@41*@51) */
  w51  = (w41*w51);
  /* #730: @64 = dense(@51) */
  casadi_densify((&w51), casadi_s11, w64, 0);
  /* #731: @56 = (@56+@64) */
  for (i=0, rr=w56, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #732: @45 = @21; (@45[6:10] += @56) */
  casadi_copy(w21, 13, w45);
  for (rr=w45+6, cs=w56; rr!=w45+10; rr+=1) *rr += *cs++;
  /* #733: @52 = sparsity_cast(@52) */
  /* #734: @52 = (-@52) */
  w52 = (- w52 );
  /* #735: @52 = @52' */
  /* #736: @74 = mac(@52,@24,@1) */
  casadi_copy(w01, 3, w74);
  casadi_mtimes((&w52), casadi_s12, w24, casadi_s2, w74, casadi_s1, w, 0);
  /* #737: @74 = @74' */
  /* #738: @60 = mac(@52,@46,@1) */
  casadi_copy(w01, 3, w60);
  casadi_mtimes((&w52), casadi_s12, w46, casadi_s2, w60, casadi_s1, w, 0);
  /* #739: @60 = @60' */
  /* #740: @74 = (@74+@60) */
  for (i=0, rr=w74, cs=w60; i<3; ++i) (*rr++) += (*cs++);
  /* #741: @74 = (-@74) */
  for (i=0, rr=w74, cs=w74; i<3; ++i) *rr++ = (- *cs++ );
  /* #742: (@45[:3] += @74) */
  for (rr=w45+0, cs=w74; rr!=w45+3; rr+=1) *rr += *cs++;
  /* #743: {@52, @51, @62, @66, @44, @65, @16, @47, @63, @67, @68, @71, @17} = vertsplit(@45) */
  w52 = w45[0];
  w51 = w45[1];
  w62 = w45[2];
  w66 = w45[3];
  w44 = w45[4];
  w65 = w45[5];
  w16 = w45[6];
  w47 = w45[7];
  w63 = w45[8];
  w67 = w45[9];
  w68 = w45[10];
  w71 = w45[11];
  w17 = w45[12];
  /* #744: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w08;
  /* #745: @56 = (@36*@40) */
  for (i=0, rr=w56, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w40);
  /* #746: @57 = (@57-@56) */
  for (i=0, rr=w57, cs=w56; i<4; ++i) (*rr++) -= (*cs++);
  /* #747: {@40, @69, @70, @49} = vertsplit(@57) */
  w40 = w57[0];
  w69 = w57[1];
  w70 = w57[2];
  w49 = w57[3];
  /* #748: @40 = (@40+@16) */
  w40 += w16;
  /* #749: @47 = (@47-@69) */
  w47 -= w69;
  /* #750: @63 = (@63-@70) */
  w63 -= w70;
  /* #751: @67 = (@67-@49) */
  w67 -= w49;
  /* #752: @45 = vertcat(@52, @51, @62, @66, @44, @65, @40, @47, @63, @67, @68, @71, @17) */
  rr=w45;
  *rr++ = w52;
  *rr++ = w51;
  *rr++ = w62;
  *rr++ = w66;
  *rr++ = w44;
  *rr++ = w65;
  *rr++ = w40;
  *rr++ = w47;
  *rr++ = w63;
  *rr++ = w67;
  *rr++ = w68;
  *rr++ = w71;
  *rr++ = w17;
  /* #753: @72 = @45[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w72, cs=w45; cii!=casadi_s4+7; ++cii) *rr++ = cs[*cii];
  /* #754: (@53[6, 7, 8, 17, 18, 19, 20] = @72) */
  for (cii=casadi_s13, rr=w53, cs=w72; cii!=casadi_s13+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #755: (@53[2, 5, 8, 11, 15, 19, 23] = @72) */
  for (cii=casadi_s14, rr=w53, cs=w72; cii!=casadi_s14+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #756: @52 = ones(13x1,1nz) */
  w52 = 1.;
  /* #757: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @51, NULL, NULL, NULL} = vertsplit(@52) */
  w51 = w52;
  /* #758: @52 = (-@51) */
  w52 = (- w51 );
  /* #759: @62 = vertcat(@55, @55, @55, @52) */
  rr=(&w62);
  *rr++ = w52;
  /* #760: @62 = (@62/@8) */
  w62 /= w08;
  /* #761: @57 = dense(@62) */
  casadi_densify((&w62), casadi_s15, w57, 0);
  /* #762: @62 = project(@27) */
  casadi_sparsify(w27, (&w62), casadi_s15, 0);
  /* #763: @51 = sparsity_cast(@51) */
  /* #764: @52 = dot(@62, @51) */
  w52 = casadi_dot(1, (&w62), (&w51));
  /* #765: @52 = (@52/@8) */
  w52 /= w08;
  /* #766: @26 = (@26*@52) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) *= w52;
  /* #767: @57 = (@57-@26) */
  for (i=0, rr=w57, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #768: {@62, @66, @44, @65} = vertsplit(@57) */
  w62 = w57[0];
  w66 = w57[1];
  w44 = w57[2];
  w65 = w57[3];
  /* #769: @40 = (@4*@62) */
  w40  = (w04*w62);
  /* #770: @47 = (@5*@66) */
  w47  = (w05*w66);
  /* #771: @40 = (@40-@47) */
  w40 -= w47;
  /* #772: @47 = (@6*@44) */
  w47  = (w06*w44);
  /* #773: @40 = (@40-@47) */
  w40 -= w47;
  /* #774: @47 = (@7*@65) */
  w47  = (w07*w65);
  /* #775: @40 = (@40-@47) */
  w40 -= w47;
  /* #776: @47 = (@5*@62) */
  w47  = (w05*w62);
  /* #777: @63 = (@4*@66) */
  w63  = (w04*w66);
  /* #778: @47 = (@47+@63) */
  w47 += w63;
  /* #779: @63 = (@7*@44) */
  w63  = (w07*w44);
  /* #780: @47 = (@47+@63) */
  w47 += w63;
  /* #781: @63 = (@6*@65) */
  w63  = (w06*w65);
  /* #782: @47 = (@47-@63) */
  w47 -= w63;
  /* #783: @63 = (@6*@62) */
  w63  = (w06*w62);
  /* #784: @67 = (@7*@66) */
  w67  = (w07*w66);
  /* #785: @63 = (@63-@67) */
  w63 -= w67;
  /* #786: @67 = (@4*@44) */
  w67  = (w04*w44);
  /* #787: @63 = (@63+@67) */
  w63 += w67;
  /* #788: @67 = (@5*@65) */
  w67  = (w05*w65);
  /* #789: @63 = (@63+@67) */
  w63 += w67;
  /* #790: @62 = (@7*@62) */
  w62  = (w07*w62);
  /* #791: @66 = (@6*@66) */
  w66  = (w06*w66);
  /* #792: @62 = (@62+@66) */
  w62 += w66;
  /* #793: @44 = (@5*@44) */
  w44  = (w05*w44);
  /* #794: @62 = (@62-@44) */
  w62 -= w44;
  /* #795: @65 = (@4*@65) */
  w65  = (w04*w65);
  /* #796: @62 = (@62+@65) */
  w62 += w65;
  /* #797: @26 = vertcat(@40, @47, @63, @62) */
  rr=w26;
  *rr++ = w40;
  *rr++ = w47;
  *rr++ = w63;
  *rr++ = w62;
  /* #798: @56 = (-@26) */
  for (i=0, rr=w56, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #799: @56 = (@13?@56:0) */
  for (i=0, rr=w56, cs=w56; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #800: @26 = (@12?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #801: @56 = (@56+@26) */
  for (i=0, rr=w56, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #802: @74 = @56[1:4] */
  for (rr=w74, cs=w56+1; cs!=w56+4; cs+=1) *rr++ = *cs;
  /* #803: @40 = dot(@20, @74) */
  w40 = casadi_dot(3, w20, w74);
  /* #804: @40 = (@40/@14) */
  w40 /= w14;
  /* #805: @47 = (@40/@2) */
  w47  = (w40/w02);
  /* #806: @50 = (@50*@40) */
  w50 *= w40;
  /* #807: @63 = @56[0] */
  for (rr=(&w63), cs=w56+0; cs!=w56+1; cs+=1) *rr++ = *cs;
  /* #808: @15 = (@15*@63) */
  w15 *= w63;
  /* #809: @50 = (@50+@15) */
  w50 += w15;
  /* #810: @18 = (@18*@50) */
  w18 *= w50;
  /* #811: @47 = (@47-@18) */
  w47 -= w18;
  /* #812: @47 = (@3*@47) */
  w47  = (w03*w47);
  /* #813: @60 = (2.*@74) */
  for (i=0, rr=w60, cs=w74; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #814: @37 = (@9*@60) */
  for (i=0, rr=w37, cs=w60; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #815: @18 = (@10*@40) */
  w18  = (w10*w40);
  /* #816: @15 = (@0*@63) */
  w15  = (w00*w63);
  /* #817: @18 = (@18-@15) */
  w18 -= w15;
  /* #818: @25 = (@30*@18) */
  for (i=0, rr=w25, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #819: @37 = (@37+@25) */
  for (i=0, rr=w37, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #820: @37 = (@37/@14) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w14;
  /* #821: @31 = (@31*@40) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) *= w40;
  /* #822: @37 = (@37-@31) */
  for (i=0, rr=w37, cs=w31; i<3; ++i) (*rr++) -= (*cs++);
  /* #823: @31 = @37' */
  casadi_copy(w37, 3, w31);
  /* #824: @25 = mac(@31,@23,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w31+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #825: @25 = @25' */
  /* #826: @1 = mac(@31,@34,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w31+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #827: @1 = @1' */
  /* #828: @25 = (@25+@1) */
  for (i=0, rr=w25, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #829: @1 = (@25/@14) */
  for (i=0, rr=w01, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #830: @38 = (@38*@40) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) *= w40;
  /* #831: @1 = (@1-@38) */
  for (i=0, rr=w01, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #832: @15 = dot(@30, @1) */
  w15 = casadi_dot(3, w30, w01);
  /* #833: @62 = dot(@60, @35) */
  w62 = casadi_dot(3, w60, w35);
  /* #834: @15 = (@15+@62) */
  w15 += w62;
  /* #835: @0 = (@0*@15) */
  w00 *= w15;
  /* #836: @47 = (@47+@0) */
  w47 += w00;
  /* #837: @47 = (-@47) */
  w47 = (- w47 );
  /* #838: (@28[0] += @47) */
  for (rr=w28+0, cs=(&w47); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #839: @47 = dot(@32, @25) */
  w47 = casadi_dot(3, w32, w25);
  /* #840: @37 = (@37/@14) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w14;
  /* #841: @59 = (@59*@40) */
  for (i=0, rr=w59; i<3; ++i) (*rr++) *= w40;
  /* #842: @37 = (@37-@59) */
  for (i=0, rr=w37, cs=w59; i<3; ++i) (*rr++) -= (*cs++);
  /* #843: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (- *cs++ );
  /* #844: @0 = dot(@37, @33) */
  w00 = casadi_dot(3, w37, w33);
  /* #845: @47 = (@47+@0) */
  w47 += w00;
  /* #846: @63 = (@63/@2) */
  w63 /= w02;
  /* #847: @43 = (@43*@50) */
  w43 *= w50;
  /* #848: @63 = (@63-@43) */
  w63 -= w43;
  /* #849: @3 = (@3*@63) */
  w03 *= w63;
  /* #850: @10 = (@10*@15) */
  w10 *= w15;
  /* #851: @3 = (@3+@10) */
  w03 += w10;
  /* #852: @47 = (@47+@3) */
  w47 += w03;
  /* #853: @47 = (@47/@14) */
  w47 /= w14;
  /* #854: @48 = (@48*@40) */
  w48 *= w40;
  /* #855: @47 = (@47-@48) */
  w47 -= w48;
  /* #856: @20 = (@20*@47) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w47;
  /* #857: @74 = (@11*@74) */
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #858: @20 = (@20+@74) */
  for (i=0, rr=w20, cs=w74; i<3; ++i) (*rr++) += (*cs++);
  /* #859: @35 = (@35*@18) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) *= w18;
  /* #860: @1 = (@9*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #861: @35 = (@35+@1) */
  for (i=0, rr=w35, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #862: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #863: @20 = (@20+@35) */
  for (i=0, rr=w20, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #864: (@28[1:4] += @20) */
  for (rr=w28+1, cs=w20; rr!=w28+4; rr+=1) *rr += *cs++;
  /* #865: @56 = (@12?@28:0) */
  for (i=0, rr=w56, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #866: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #867: @28 = (@13?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #868: @56 = (@56+@28) */
  for (i=0, rr=w56, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #869: {@13, @12, @9, @18} = vertsplit(@56) */
  w13 = w56[0];
  w12 = w56[1];
  w09 = w56[2];
  w18 = w56[3];
  /* #870: @11 = (@7*@18) */
  w11  = (w07*w18);
  /* #871: @47 = (@6*@9) */
  w47  = (w06*w09);
  /* #872: @11 = (@11+@47) */
  w11 += w47;
  /* #873: @47 = (@5*@12) */
  w47  = (w05*w12);
  /* #874: @11 = (@11+@47) */
  w11 += w47;
  /* #875: @47 = (@4*@13) */
  w47  = (w04*w13);
  /* #876: @11 = (@11+@47) */
  w11 += w47;
  /* #877: @47 = (@6*@18) */
  w47  = (w06*w18);
  /* #878: @48 = (@7*@9) */
  w48  = (w07*w09);
  /* #879: @47 = (@47-@48) */
  w47 -= w48;
  /* #880: @48 = (@4*@12) */
  w48  = (w04*w12);
  /* #881: @47 = (@47+@48) */
  w47 += w48;
  /* #882: @48 = (@5*@13) */
  w48  = (w05*w13);
  /* #883: @47 = (@47-@48) */
  w47 -= w48;
  /* #884: @48 = (@4*@9) */
  w48  = (w04*w09);
  /* #885: @40 = (@5*@18) */
  w40  = (w05*w18);
  /* #886: @48 = (@48-@40) */
  w48 -= w40;
  /* #887: @40 = (@7*@12) */
  w40  = (w07*w12);
  /* #888: @48 = (@48+@40) */
  w48 += w40;
  /* #889: @40 = (@6*@13) */
  w40  = (w06*w13);
  /* #890: @48 = (@48-@40) */
  w48 -= w40;
  /* #891: @4 = (@4*@18) */
  w04 *= w18;
  /* #892: @5 = (@5*@9) */
  w05 *= w09;
  /* #893: @4 = (@4+@5) */
  w04 += w05;
  /* #894: @6 = (@6*@12) */
  w06 *= w12;
  /* #895: @4 = (@4-@6) */
  w04 -= w06;
  /* #896: @7 = (@7*@13) */
  w07 *= w13;
  /* #897: @4 = (@4-@7) */
  w04 -= w07;
  /* #898: @56 = vertcat(@11, @47, @48, @4) */
  rr=w56;
  *rr++ = w11;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w04;
  /* #899: @11 = dot(@29, @56) */
  w11 = casadi_dot(4, w29, w56);
  /* #900: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w08;
  /* #901: @58 = (@58*@52) */
  for (i=0, rr=w58; i<4; ++i) (*rr++) *= w52;
  /* #902: @57 = (@57-@58) */
  for (i=0, rr=w57, cs=w58; i<4; ++i) (*rr++) -= (*cs++);
  /* #903: @57 = (-@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #904: @47 = dot(@57, @39) */
  w47 = casadi_dot(4, w57, w39);
  /* #905: @11 = (@11+@47) */
  w11 += w47;
  /* #906: @11 = (@11/@8) */
  w11 /= w08;
  /* #907: @42 = (@42*@52) */
  w42 *= w52;
  /* #908: @11 = (@11-@42) */
  w11 -= w42;
  /* #909: @27 = (@27*@11) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) *= w11;
  /* #910: @41 = (@41*@51) */
  w41 *= w51;
  /* #911: @57 = dense(@41) */
  casadi_densify((&w41), casadi_s15, w57, 0);
  /* #912: @27 = (@27+@57) */
  for (i=0, rr=w27, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #913: (@21[6:10] += @27) */
  for (rr=w21+6, cs=w27; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #914: {@41, @51, @11, @42, @47, @48, @4, @7, @13, @6, @12, @5, @9} = vertsplit(@21) */
  w41 = w21[0];
  w51 = w21[1];
  w11 = w21[2];
  w42 = w21[3];
  w47 = w21[4];
  w48 = w21[5];
  w04 = w21[6];
  w07 = w21[7];
  w13 = w21[8];
  w06 = w21[9];
  w12 = w21[10];
  w05 = w21[11];
  w09 = w21[12];
  /* #915: @56 = (@56/@8) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) /= w08;
  /* #916: @36 = (@36*@52) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) *= w52;
  /* #917: @56 = (@56-@36) */
  for (i=0, rr=w56, cs=w36; i<4; ++i) (*rr++) -= (*cs++);
  /* #918: {@52, @8, @18, @40} = vertsplit(@56) */
  w52 = w56[0];
  w08 = w56[1];
  w18 = w56[2];
  w40 = w56[3];
  /* #919: @52 = (@52+@4) */
  w52 += w04;
  /* #920: @7 = (@7-@8) */
  w07 -= w08;
  /* #921: @13 = (@13-@18) */
  w13 -= w18;
  /* #922: @6 = (@6-@40) */
  w06 -= w40;
  /* #923: @21 = vertcat(@41, @51, @11, @42, @47, @48, @52, @7, @13, @6, @12, @5, @9) */
  rr=w21;
  *rr++ = w41;
  *rr++ = w51;
  *rr++ = w11;
  *rr++ = w42;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w52;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w09;
  /* #924: @56 = @21[6:10] */
  for (rr=w56, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #925: (@53[21:25] = @56) */
  for (rr=w53+21, cs=w56; rr!=w53+25; rr+=1) *rr = *cs++;
  /* #926: (@53[12:28:4] = @56) */
  for (rr=w53+12, cs=w56; rr!=w53+28; rr+=4) *rr = *cs++;
  /* #927: @75 = @53' */
  casadi_trans(w53,casadi_s16, w75, casadi_s16, iw);
  /* #928: output[2][0] = @75 */
  casadi_copy(w75, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s18;
    case 2: return casadi_s18;
    case 3: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    case 1: return casadi_s17;
    case 2: return casadi_s16;
    case 3: return casadi_s21;
    case 4: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 270;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 270*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
