/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[17] = 
  {13, 1, 0, 13, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12};
static const casadi_int casadi_s2[18] = 
  {1, 13, 0, 1, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  0, 0};
static const casadi_int casadi_s3[6] = {13, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[20] = 
  {1, 13, 0, 1, 2, 2, 3, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  0, 0, 0, 0};
static const casadi_int casadi_s5[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s7[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s8[13] = 
  {13, 4, 0, 3, 4, 5, 6, 3,
  4, 5, 10, 11, 12};
static const casadi_int casadi_s9[22] = 
  {4, 13, 0, 0, 0, 0, 1, 2,
  3, 3, 3, 3, 3, 4, 5, 6,
  0, 0, 0, 1, 2, 3};
static const casadi_int casadi_s10[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[3] = {13, 1, 1};
static const casadi_int casadi_s13[3] = {4, 1, 1};
static const casadi_int casadi_s14[3] = {0, 1, 1};
static const casadi_int casadi_s15[3] = {17, 1, 1};
static const casadi_int casadi_s16[3] = {2, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c2[9] = 
  {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0.,
  1.5968700000000000e-03};
static const casadi_real casadi_c3[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c4[2] = {15., 10.};

/* Drone_ode_complete_constr_h_fun:(i0[13],i1[4],i2[0],i3[17])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, w02, w03, *w04=w+8, w05, w06, w07, w08, w09, w10;
  casadi_real *w11=w+26, w12, w13, w14, *w15=w+31, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, *w29=w+47, *w30=w+51, *w31=w+54, *w32=w+57, *w33=w+66, *w34=w+69;
  casadi_real *w35=w+72, *w36=w+85, *w37=w+98, *w39=w+104, *w40=w+113, *w41=w+117, *w42=w+126, *w44=w+135, *w45=w+141;
  const casadi_real *cr, *cs, *ct, *wr32;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(13x1,2nz) */
  casadi_clear(w01, 2);
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = 2.9 */
  w03 = 2.8999999999999999e+00;
  /* #4: @2 = (@2-@3) */
  w02 -= w03;
  /* #5: @3 = (2.*@2) */
  w03 = (2.* w02 );
  /* #6: @4 = ones(13x1,12nz) */
  casadi_fill(w04, 12, 1.);
  /* #7: {@5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@4) */
  w05 = w04[0];
  /* #8: @6 = (@3*@5) */
  w06  = (w03*w05);
  /* #9: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #10: @7 = input[0][1] */
  w07 = arg[0] ? arg[0][1] : 0;
  /* #11: @8 = 0.17 */
  w08 = 1.7000000000000001e-01;
  /* #12: @7 = (@7-@8) */
  w07 -= w08;
  /* #13: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #14: @2 = (@2+@8) */
  w02 += w08;
  /* #15: @2 = sqrt(@2) */
  w02 = sqrt( w02 );
  /* #16: @8 = (2.*@2) */
  w08 = (2.* w02 );
  /* #17: @6 = (@6/@8) */
  w06 /= w08;
  /* #18: (@1[0] = @6) */
  for (rr=w01+0, cs=(&w06); rr!=w01+1; rr+=1) *rr = *cs++;
  /* #19: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #20: @9 = ones(13x1,1nz) */
  w09 = 1.;
  /* #21: {NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@9) */
  w10 = w09;
  /* #22: @9 = (@7*@10) */
  w09  = (w07*w10);
  /* #23: @9 = (@9/@8) */
  w09 /= w08;
  /* #24: (@1[1] = @9) */
  for (rr=w01+1, cs=(&w09); rr!=w01+2; rr+=1) *rr = *cs++;
  /* #25: @11 = @1' */
  casadi_copy(w01, 2, w11);
  /* #26: @12 = input[0][3] */
  w12 = arg[0] ? arg[0][3] : 0;
  /* #27: @13 = input[0][4] */
  w13 = arg[0] ? arg[0][4] : 0;
  /* #28: @14 = input[0][5] */
  w14 = arg[0] ? arg[0][5] : 0;
  /* #29: @15 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w15);
  /* #30: @16 = 9.81 */
  w16 = 9.8100000000000005e+00;
  /* #31: @15 = (@15*@16) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) *= w16;
  /* #32: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) *rr++ = (- *cs++ );
  /* #33: @16 = 0.5 */
  w16 = 5.0000000000000000e-01;
  /* #34: @17 = input[0][7] */
  w17 = arg[0] ? arg[0][7] : 0;
  /* #35: @18 = input[0][10] */
  w18 = arg[0] ? arg[0][10] : 0;
  /* #36: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #37: @19 = (-@19) */
  w19 = (- w19 );
  /* #38: @20 = input[0][8] */
  w20 = arg[0] ? arg[0][8] : 0;
  /* #39: @21 = input[0][11] */
  w21 = arg[0] ? arg[0][11] : 0;
  /* #40: @22 = (@20*@21) */
  w22  = (w20*w21);
  /* #41: @19 = (@19-@22) */
  w19 -= w22;
  /* #42: @22 = input[0][9] */
  w22 = arg[0] ? arg[0][9] : 0;
  /* #43: @23 = input[0][12] */
  w23 = arg[0] ? arg[0][12] : 0;
  /* #44: @24 = (@22*@23) */
  w24  = (w22*w23);
  /* #45: @19 = (@19-@24) */
  w19 -= w24;
  /* #46: @24 = input[0][6] */
  w24 = arg[0] ? arg[0][6] : 0;
  /* #47: @25 = (@24*@18) */
  w25  = (w24*w18);
  /* #48: @26 = (@20*@23) */
  w26  = (w20*w23);
  /* #49: @25 = (@25+@26) */
  w25 += w26;
  /* #50: @26 = (@22*@21) */
  w26  = (w22*w21);
  /* #51: @25 = (@25-@26) */
  w25 -= w26;
  /* #52: @26 = (@24*@21) */
  w26  = (w24*w21);
  /* #53: @27 = (@17*@23) */
  w27  = (w17*w23);
  /* #54: @26 = (@26-@27) */
  w26 -= w27;
  /* #55: @27 = (@22*@18) */
  w27  = (w22*w18);
  /* #56: @26 = (@26+@27) */
  w26 += w27;
  /* #57: @27 = (@24*@23) */
  w27  = (w24*w23);
  /* #58: @28 = (@17*@21) */
  w28  = (w17*w21);
  /* #59: @27 = (@27+@28) */
  w27 += w28;
  /* #60: @28 = (@20*@18) */
  w28  = (w20*w18);
  /* #61: @27 = (@27-@28) */
  w27 -= w28;
  /* #62: @29 = vertcat(@19, @25, @26, @27) */
  rr=w29;
  *rr++ = w19;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  /* #63: @29 = (@16*@29) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w16*(*cs++));
  /* #64: @30 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c1, 3, w30);
  /* #65: @30 = nonzeros(@30) */
  /* #66: @31 = zeros(3x1) */
  casadi_clear(w31, 3);
  /* #67: @32 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  wr32 = casadi_c2;
  /* #68: @33 = vertcat(@18, @21, @23) */
  rr=w33;
  *rr++ = w18;
  *rr++ = w21;
  *rr++ = w23;
  /* #69: @34 = mac(@32,@33,@31) */
  casadi_copy(w31, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr32+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #70: @16 = @34[2] */
  for (rr=(&w16), cs=w34+2; cs!=w34+3; cs+=1) *rr++ = *cs;
  /* #71: @19 = (@21*@16) */
  w19  = (w21*w16);
  /* #72: @25 = @34[1] */
  for (rr=(&w25), cs=w34+1; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #73: @26 = (@23*@25) */
  w26  = (w23*w25);
  /* #74: @19 = (@19-@26) */
  w19 -= w26;
  /* #75: @26 = @34[0] */
  for (rr=(&w26), cs=w34+0; cs!=w34+1; cs+=1) *rr++ = *cs;
  /* #76: @23 = (@23*@26) */
  w23 *= w26;
  /* #77: @16 = (@18*@16) */
  w16  = (w18*w16);
  /* #78: @23 = (@23-@16) */
  w23 -= w16;
  /* #79: @18 = (@18*@25) */
  w18 *= w25;
  /* #80: @21 = (@21*@26) */
  w21 *= w26;
  /* #81: @18 = (@18-@21) */
  w18 -= w21;
  /* #82: @34 = vertcat(@19, @23, @18) */
  rr=w34;
  *rr++ = w19;
  *rr++ = w23;
  *rr++ = w18;
  /* #83: @34 = (@30*@34) */
  for (i=0, rr=w34, cr=w30, cs=w34; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #84: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #85: @35 = vertcat(@12, @13, @14, @15, @29, @34) */
  rr=w35;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #86: @12 = mac(@11,@35,@0) */
  casadi_copy((&w00), 1, (&w12));
  casadi_mtimes(w11, casadi_s2, w35, casadi_s1, (&w12), casadi_s0, w, 0);
  /* #87: @14 = 5 */
  w14 = 5.;
  /* #88: @19 = 0.75 */
  w19 = 7.5000000000000000e-01;
  /* #89: @2 = (@2-@19) */
  w02 -= w19;
  /* #90: @14 = (@14*@2) */
  w14 *= w02;
  /* #91: @14 = (@12+@14) */
  w14  = (w12+w14);
  /* #92: output[0][0] = @14 */
  if (res[0]) res[0][0] = w14;
  /* #93: @29 = zeros(13x1,4nz) */
  casadi_clear(w29, 4);
  /* #94: @6 = (@6/@8) */
  w06 /= w08;
  /* #95: @36 = @35; (@36[1] = @0) */
  casadi_copy(w35, 13, w36);
  for (rr=w36+1, cs=(&w00); rr!=w36+2; rr+=1) *rr = *cs++;
  /* #96: @14 = @36[0] */
  for (rr=(&w14), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #97: @6 = (@6*@14) */
  w06 *= w14;
  /* #98: @6 = (-@6) */
  w06 = (- w06 );
  /* #99: @9 = (@9/@8) */
  w09 /= w08;
  /* #100: @9 = (@9*@13) */
  w09 *= w13;
  /* #101: @6 = (@6-@9) */
  w06 -= w09;
  /* #102: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #103: @6 = (@6/@8) */
  w06 /= w08;
  /* #104: @3 = (@3*@6) */
  w03 *= w06;
  /* #105: @14 = (@14/@8) */
  w14 /= w08;
  /* #106: @5 = (@5*@14) */
  w05 *= w14;
  /* #107: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #108: @3 = (@3+@5) */
  w03 += w05;
  /* #109: (@29[0] = @3) */
  for (rr=w29+0, cs=(&w03); rr!=w29+1; rr+=1) *rr = *cs++;
  /* #110: @13 = (@13/@8) */
  w13 /= w08;
  /* #111: @10 = (@10*@13) */
  w10 *= w13;
  /* #112: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #113: @7 = (@7*@6) */
  w07 *= w06;
  /* #114: @10 = (@10+@7) */
  w10 += w07;
  /* #115: (@29[1] = @10) */
  for (rr=w29+1, cs=(&w10); rr!=w29+2; rr+=1) *rr = *cs++;
  /* #116: @36 = dense(@1) */
  casadi_densify(w01, casadi_s3, w36, 0);
  /* #117: {@10, @7, NULL, NULL, NULL, NULL} = vertsplit(@36) */
  w10 = w36[0];
  w07 = w36[1];
  /* #118: (@29[2] = @10) */
  for (rr=w29+2, cs=(&w10); rr!=w29+3; rr+=1) *rr = *cs++;
  /* #119: (@29[3] = @7) */
  for (rr=w29+3, cs=(&w07); rr!=w29+4; rr+=1) *rr = *cs++;
  /* #120: @29 = @29' */
  /* #121: @7 = mac(@29,@35,@0) */
  casadi_copy((&w00), 1, (&w07));
  casadi_mtimes(w29, casadi_s4, w35, casadi_s1, (&w07), casadi_s0, w, 0);
  /* #122: @10 = zeros(1x4,1nz) */
  w10 = 0.;
  /* #123: @37 = zeros(4x13,6nz) */
  casadi_clear(w37, 6);
  /* #124: @38 = 00 */
  /* #125: @32 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr32 = casadi_c3;
  /* #126: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #127: @40 = vertcat(@24, @17, @20, @22) */
  rr=w40;
  *rr++ = w24;
  *rr++ = w17;
  *rr++ = w20;
  *rr++ = w22;
  /* #128: @24 = ||@40||_F */
  w24 = casadi_norm_2(4, w40);
  /* #129: @40 = (@40/@24) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) /= w24;
  /* #130: @24 = @40[3] */
  for (rr=(&w24), cs=w40+3; cs!=w40+4; cs+=1) *rr++ = *cs;
  /* #131: @17 = (-@24) */
  w17 = (- w24 );
  /* #132: @41 = @39; (@41[3] = @17) */
  casadi_copy(w39, 9, w41);
  for (rr=w41+3, cs=(&w17); rr!=w41+4; rr+=1) *rr = *cs++;
  /* #133: @17 = @40[2] */
  for (rr=(&w17), cs=w40+2; cs!=w40+3; cs+=1) *rr++ = *cs;
  /* #134: (@41[6] = @17) */
  for (rr=w41+6, cs=(&w17); rr!=w41+7; rr+=1) *rr = *cs++;
  /* #135: @20 = @40[1] */
  for (rr=(&w20), cs=w40+1; cs!=w40+2; cs+=1) *rr++ = *cs;
  /* #136: @22 = (-@20) */
  w22 = (- w20 );
  /* #137: (@41[7] = @22) */
  for (rr=w41+7, cs=(&w22); rr!=w41+8; rr+=1) *rr = *cs++;
  /* #138: (@41[1] = @24) */
  for (rr=w41+1, cs=(&w24); rr!=w41+2; rr+=1) *rr = *cs++;
  /* #139: @17 = (-@17) */
  w17 = (- w17 );
  /* #140: (@41[2] = @17) */
  for (rr=w41+2, cs=(&w17); rr!=w41+3; rr+=1) *rr = *cs++;
  /* #141: (@41[5] = @20) */
  for (rr=w41+5, cs=(&w20); rr!=w41+6; rr+=1) *rr = *cs++;
  /* #142: @42 = (2.*@41) */
  for (i=0, rr=w42, cs=w41; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #143: @39 = mac(@42,@41,@39) */
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w42+j, ct=w41+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #144: @32 = (@32+@39) */
  for (i=0, rr=w32, cr=wr32, cs=w39; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #145: @20 = @40[0] */
  for (rr=(&w20), cs=w40+0; cs!=w40+1; cs+=1) *rr++ = *cs;
  /* #146: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #147: @41 = (@20*@41) */
  for (i=0, rr=w41, cs=w41; i<9; ++i) (*rr++)  = (w20*(*cs++));
  /* #148: @32 = (@32+@41) */
  for (i=0, rr=w32, cs=w41; i<9; ++i) (*rr++) += (*cs++);
  /* #149: @40 = ones(4x1) */
  casadi_fill(w40, 4, 1.);
  /* #150: {@20, @17, @24, @22} = vertsplit(@40) */
  w20 = w40[0];
  w17 = w40[1];
  w24 = w40[2];
  w22 = w40[3];
  /* #151: @6 = vertcat(@38, @38, @20) */
  rr=(&w06);
  *rr++ = w20;
  /* #152: @31 = mac(@32,@6,@31) */
  casadi_mtimes(w32, casadi_s7, (&w06), casadi_s6, w31, casadi_s5, w, 0);
  /* #153: @43 = zeros(4x1,0nz) */
  /* #154: @15 = vertcat(@17, @24, @22) */
  rr=w15;
  *rr++ = w17;
  *rr++ = w24;
  *rr++ = w22;
  /* #155: @30 = (@30*@15) */
  for (i=0, rr=w30, cs=w15; i<3; ++i) (*rr++) *= (*cs++);
  /* #156: @44 = vertcat(@38, @38, @38, @31, @43, @30) */
  rr=w44;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #157: @45 = @44[:6] */
  for (rr=w45, cs=w44+0; cs!=w44+6; cs+=1) *rr++ = *cs;
  /* #158: (@37[:6] = @45) */
  for (rr=w37+0, cs=w45; rr!=w37+6; rr+=1) *rr = *cs++;
  /* #159: @45 = @37' */
  casadi_trans(w37,casadi_s9, w45, casadi_s8, iw);
  /* #160: @10 = mac(@29,@45,@10) */
  casadi_mtimes(w29, casadi_s4, w45, casadi_s8, (&w10), casadi_s10, w, 0);
  /* #161: @17 = input[1][0] */
  w17 = arg[1] ? arg[1][0] : 0;
  /* #162: @24 = input[1][1] */
  w24 = arg[1] ? arg[1][1] : 0;
  /* #163: @22 = input[1][2] */
  w22 = arg[1] ? arg[1][2] : 0;
  /* #164: @6 = input[1][3] */
  w06 = arg[1] ? arg[1][3] : 0;
  /* #165: @29 = vertcat(@17, @24, @22, @6) */
  rr=w29;
  *rr++ = w17;
  *rr++ = w24;
  *rr++ = w22;
  *rr++ = w06;
  /* #166: @17 = mac(@10,@29,@0) */
  casadi_copy((&w00), 1, (&w17));
  casadi_mtimes((&w10), casadi_s10, w29, casadi_s11, (&w17), casadi_s0, w, 0);
  /* #167: @7 = (@7+@17) */
  w07 += w17;
  /* #168: @1 = [15, 10] */
  casadi_copy(casadi_c4, 2, w01);
  /* #169: @1 = @1' */
  /* #170: @11 = vertcat(@2, @12) */
  rr=w11;
  *rr++ = w02;
  *rr++ = w12;
  /* #171: @0 = mac(@1,@11,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w11+i*2; k<2; ++k) *rr += cs[k*1]**ct++;
  /* #172: @7 = (@7+@0) */
  w07 += w00;
  /* #173: output[0][1] = @7 */
  if (res[0]) res[0][1] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s13;
    case 2: return casadi_s14;
    case 3: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 147;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 14*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 147*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
