/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[17] = 
  {13, 1, 0, 13, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12};
static const casadi_int casadi_s2[18] = 
  {1, 13, 0, 1, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2,
  0, 0};
static const casadi_int casadi_s3[6] = {13, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[20] = 
  {1, 13, 0, 1, 2, 2, 3, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  0, 0, 0, 0};
static const casadi_int casadi_s5[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s7[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s8[13] = 
  {13, 4, 0, 3, 4, 5, 6, 3,
  4, 5, 10, 11, 12};
static const casadi_int casadi_s9[22] = 
  {4, 13, 0, 0, 0, 0, 1, 2,
  3, 3, 3, 3, 3, 4, 5, 6,
  0, 0, 0, 1, 2, 3};
static const casadi_int casadi_s10[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s13[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s14[8] = {13, 1, 0, 4, 0, 1, 3, 4};
static const casadi_int casadi_s15[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s16[3] = {13, 1, 1};
static const casadi_int casadi_s17[3] = {4, 1, 1};
static const casadi_int casadi_s18[3] = {0, 1, 1};
static const casadi_int casadi_s19[3] = {17, 1, 1};
static const casadi_int casadi_s20[3] = {2, 1, 1};
static const casadi_int casadi_s21[18] = 
  {17, 2, 0, 4, 13, 4, 5, 7,
  8, 0, 4, 5, 7, 8, 10, 11,
  12, 13};
static const casadi_int casadi_s22[3] = {2, 0, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c2[9] = 
  {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0.,
  1.5968700000000000e-03};
static const casadi_real casadi_c3[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c4[2] = {15., 10.};

/* Drone_ode_complete_constr_h_fun_jac_uxt_zt:(i0[13],i1[4],i2[0],i3[17])->(o0[2],o1[17x2,13nz],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+14, w02, w03, *w04=w+18, w05, w06, w07, w08, w09, w10;
  casadi_real *w11=w+36, w12, w13, w14, *w15=w+41, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, *w29=w+57, *w30=w+61, *w31=w+64, *w32=w+67, *w33=w+76, *w34=w+79;
  casadi_real *w35=w+82, *w36=w+95, w37, *w38=w+109, *w39=w+113, *w41=w+119, *w42=w+128, *w43=w+132, *w44=w+136, w45, *w46=w+146, *w47=w+155;
  casadi_real *w48=w+164, w49, w50, *w52=w+170, *w53=w+176, *w54=w+182, *w55=w+184, *w56=w+186, *w57=w+199, *w58=w+212, *w59=w+216, *w60=w+220;
  casadi_real *w61=w+224, *w62=w+237, w63, w64, w65, w66, w67, w68, w69, w70, *w72=w+258;
  const casadi_real *cr, *cs, *ct, *wr32;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(13x1,2nz) */
  casadi_clear(w01, 2);
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = 2.9 */
  w03 = 2.8999999999999999e+00;
  /* #4: @2 = (@2-@3) */
  w02 -= w03;
  /* #5: @3 = (2.*@2) */
  w03 = (2.* w02 );
  /* #6: @4 = ones(13x1,12nz) */
  casadi_fill(w04, 12, 1.);
  /* #7: {@5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@4) */
  w05 = w04[0];
  /* #8: @6 = (@3*@5) */
  w06  = (w03*w05);
  /* #9: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #10: @7 = input[0][1] */
  w07 = arg[0] ? arg[0][1] : 0;
  /* #11: @8 = 0.17 */
  w08 = 1.7000000000000001e-01;
  /* #12: @7 = (@7-@8) */
  w07 -= w08;
  /* #13: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #14: @2 = (@2+@8) */
  w02 += w08;
  /* #15: @2 = sqrt(@2) */
  w02 = sqrt( w02 );
  /* #16: @8 = (2.*@2) */
  w08 = (2.* w02 );
  /* #17: @6 = (@6/@8) */
  w06 /= w08;
  /* #18: (@1[0] = @6) */
  for (rr=w01+0, cs=(&w06); rr!=w01+1; rr+=1) *rr = *cs++;
  /* #19: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #20: @9 = ones(13x1,1nz) */
  w09 = 1.;
  /* #21: {NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@9) */
  w10 = w09;
  /* #22: @9 = (@7*@10) */
  w09  = (w07*w10);
  /* #23: @9 = (@9/@8) */
  w09 /= w08;
  /* #24: (@1[1] = @9) */
  for (rr=w01+1, cs=(&w09); rr!=w01+2; rr+=1) *rr = *cs++;
  /* #25: @11 = @1' */
  casadi_copy(w01, 2, w11);
  /* #26: @12 = input[0][3] */
  w12 = arg[0] ? arg[0][3] : 0;
  /* #27: @13 = input[0][4] */
  w13 = arg[0] ? arg[0][4] : 0;
  /* #28: @14 = input[0][5] */
  w14 = arg[0] ? arg[0][5] : 0;
  /* #29: @15 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w15);
  /* #30: @16 = 9.81 */
  w16 = 9.8100000000000005e+00;
  /* #31: @15 = (@15*@16) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) *= w16;
  /* #32: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) *rr++ = (- *cs++ );
  /* #33: @16 = 0.5 */
  w16 = 5.0000000000000000e-01;
  /* #34: @17 = input[0][7] */
  w17 = arg[0] ? arg[0][7] : 0;
  /* #35: @18 = input[0][10] */
  w18 = arg[0] ? arg[0][10] : 0;
  /* #36: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #37: @19 = (-@19) */
  w19 = (- w19 );
  /* #38: @20 = input[0][8] */
  w20 = arg[0] ? arg[0][8] : 0;
  /* #39: @21 = input[0][11] */
  w21 = arg[0] ? arg[0][11] : 0;
  /* #40: @22 = (@20*@21) */
  w22  = (w20*w21);
  /* #41: @19 = (@19-@22) */
  w19 -= w22;
  /* #42: @22 = input[0][9] */
  w22 = arg[0] ? arg[0][9] : 0;
  /* #43: @23 = input[0][12] */
  w23 = arg[0] ? arg[0][12] : 0;
  /* #44: @24 = (@22*@23) */
  w24  = (w22*w23);
  /* #45: @19 = (@19-@24) */
  w19 -= w24;
  /* #46: @24 = input[0][6] */
  w24 = arg[0] ? arg[0][6] : 0;
  /* #47: @25 = (@24*@18) */
  w25  = (w24*w18);
  /* #48: @26 = (@20*@23) */
  w26  = (w20*w23);
  /* #49: @25 = (@25+@26) */
  w25 += w26;
  /* #50: @26 = (@22*@21) */
  w26  = (w22*w21);
  /* #51: @25 = (@25-@26) */
  w25 -= w26;
  /* #52: @26 = (@24*@21) */
  w26  = (w24*w21);
  /* #53: @27 = (@17*@23) */
  w27  = (w17*w23);
  /* #54: @26 = (@26-@27) */
  w26 -= w27;
  /* #55: @27 = (@22*@18) */
  w27  = (w22*w18);
  /* #56: @26 = (@26+@27) */
  w26 += w27;
  /* #57: @27 = (@24*@23) */
  w27  = (w24*w23);
  /* #58: @28 = (@17*@21) */
  w28  = (w17*w21);
  /* #59: @27 = (@27+@28) */
  w27 += w28;
  /* #60: @28 = (@20*@18) */
  w28  = (w20*w18);
  /* #61: @27 = (@27-@28) */
  w27 -= w28;
  /* #62: @29 = vertcat(@19, @25, @26, @27) */
  rr=w29;
  *rr++ = w19;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  /* #63: @29 = (@16*@29) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w16*(*cs++));
  /* #64: @30 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c1, 3, w30);
  /* #65: @30 = nonzeros(@30) */
  /* #66: @31 = zeros(3x1) */
  casadi_clear(w31, 3);
  /* #67: @32 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  wr32 = casadi_c2;
  /* #68: @33 = vertcat(@18, @21, @23) */
  rr=w33;
  *rr++ = w18;
  *rr++ = w21;
  *rr++ = w23;
  /* #69: @34 = mac(@32,@33,@31) */
  casadi_copy(w31, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr32+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #70: @19 = @34[2] */
  for (rr=(&w19), cs=w34+2; cs!=w34+3; cs+=1) *rr++ = *cs;
  /* #71: @25 = (@21*@19) */
  w25  = (w21*w19);
  /* #72: @26 = @34[1] */
  for (rr=(&w26), cs=w34+1; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #73: @27 = (@23*@26) */
  w27  = (w23*w26);
  /* #74: @25 = (@25-@27) */
  w25 -= w27;
  /* #75: @27 = @34[0] */
  for (rr=(&w27), cs=w34+0; cs!=w34+1; cs+=1) *rr++ = *cs;
  /* #76: @28 = (@23*@27) */
  w28  = (w23*w27);
  /* #77: @19 = (@18*@19) */
  w19  = (w18*w19);
  /* #78: @28 = (@28-@19) */
  w28 -= w19;
  /* #79: @26 = (@18*@26) */
  w26  = (w18*w26);
  /* #80: @27 = (@21*@27) */
  w27  = (w21*w27);
  /* #81: @26 = (@26-@27) */
  w26 -= w27;
  /* #82: @34 = vertcat(@25, @28, @26) */
  rr=w34;
  *rr++ = w25;
  *rr++ = w28;
  *rr++ = w26;
  /* #83: @34 = (@30*@34) */
  for (i=0, rr=w34, cr=w30, cs=w34; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #84: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #85: @35 = vertcat(@12, @13, @14, @15, @29, @34) */
  rr=w35;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #86: @12 = mac(@11,@35,@0) */
  casadi_copy((&w00), 1, (&w12));
  casadi_mtimes(w11, casadi_s2, w35, casadi_s1, (&w12), casadi_s0, w, 0);
  /* #87: @14 = 5 */
  w14 = 5.;
  /* #88: @25 = 0.75 */
  w25 = 7.5000000000000000e-01;
  /* #89: @2 = (@2-@25) */
  w02 -= w25;
  /* #90: @25 = (@14*@2) */
  w25  = (w14*w02);
  /* #91: @25 = (@12+@25) */
  w25  = (w12+w25);
  /* #92: output[0][0] = @25 */
  if (res[0]) res[0][0] = w25;
  /* #93: @29 = zeros(13x1,4nz) */
  casadi_clear(w29, 4);
  /* #94: @6 = (@6/@8) */
  w06 /= w08;
  /* #95: @36 = @35; (@36[1] = @0) */
  casadi_copy(w35, 13, w36);
  for (rr=w36+1, cs=(&w00); rr!=w36+2; rr+=1) *rr = *cs++;
  /* #96: @25 = @36[0] */
  for (rr=(&w25), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #97: @28 = (@6*@25) */
  w28  = (w06*w25);
  /* #98: @28 = (-@28) */
  w28 = (- w28 );
  /* #99: @9 = (@9/@8) */
  w09 /= w08;
  /* #100: @26 = (@9*@13) */
  w26  = (w09*w13);
  /* #101: @28 = (@28-@26) */
  w28 -= w26;
  /* #102: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #103: @28 = (@28/@8) */
  w28 /= w08;
  /* #104: @26 = (@3*@28) */
  w26  = (w03*w28);
  /* #105: @27 = (@25/@8) */
  w27  = (w25/w08);
  /* #106: @19 = (@5*@27) */
  w19  = (w05*w27);
  /* #107: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #108: @26 = (@26+@19) */
  w26 += w19;
  /* #109: (@29[0] = @26) */
  for (rr=w29+0, cs=(&w26); rr!=w29+1; rr+=1) *rr = *cs++;
  /* #110: @26 = (@13/@8) */
  w26  = (w13/w08);
  /* #111: @19 = (@10*@26) */
  w19  = (w10*w26);
  /* #112: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #113: @37 = (@7*@28) */
  w37  = (w07*w28);
  /* #114: @19 = (@19+@37) */
  w19 += w37;
  /* #115: (@29[1] = @19) */
  for (rr=w29+1, cs=(&w19); rr!=w29+2; rr+=1) *rr = *cs++;
  /* #116: @36 = dense(@1) */
  casadi_densify(w01, casadi_s3, w36, 0);
  /* #117: {@19, @37, NULL, NULL, NULL, NULL} = vertsplit(@36) */
  w19 = w36[0];
  w37 = w36[1];
  /* #118: (@29[2] = @19) */
  for (rr=w29+2, cs=(&w19); rr!=w29+3; rr+=1) *rr = *cs++;
  /* #119: (@29[3] = @37) */
  for (rr=w29+3, cs=(&w37); rr!=w29+4; rr+=1) *rr = *cs++;
  /* #120: @38 = @29' */
  casadi_copy(w29, 4, w38);
  /* #121: @37 = mac(@38,@35,@0) */
  casadi_copy((&w00), 1, (&w37));
  casadi_mtimes(w38, casadi_s4, w35, casadi_s1, (&w37), casadi_s0, w, 0);
  /* #122: @19 = zeros(1x4,1nz) */
  w19 = 0.;
  /* #123: @39 = zeros(4x13,6nz) */
  casadi_clear(w39, 6);
  /* #124: @40 = 00 */
  /* #125: @32 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr32 = casadi_c3;
  /* #126: @41 = zeros(3x3) */
  casadi_clear(w41, 9);
  /* #127: @42 = vertcat(@24, @17, @20, @22) */
  rr=w42;
  *rr++ = w24;
  *rr++ = w17;
  *rr++ = w20;
  *rr++ = w22;
  /* #128: @24 = ||@42||_F */
  w24 = casadi_norm_2(4, w42);
  /* #129: @43 = (@42/@24) */
  for (i=0, rr=w43, cr=w42; i<4; ++i) (*rr++)  = ((*cr++)/w24);
  /* #130: @17 = @43[3] */
  for (rr=(&w17), cs=w43+3; cs!=w43+4; cs+=1) *rr++ = *cs;
  /* #131: @20 = (-@17) */
  w20 = (- w17 );
  /* #132: @44 = @41; (@44[3] = @20) */
  casadi_copy(w41, 9, w44);
  for (rr=w44+3, cs=(&w20); rr!=w44+4; rr+=1) *rr = *cs++;
  /* #133: @20 = @43[2] */
  for (rr=(&w20), cs=w43+2; cs!=w43+3; cs+=1) *rr++ = *cs;
  /* #134: (@44[6] = @20) */
  for (rr=w44+6, cs=(&w20); rr!=w44+7; rr+=1) *rr = *cs++;
  /* #135: @22 = @43[1] */
  for (rr=(&w22), cs=w43+1; cs!=w43+2; cs+=1) *rr++ = *cs;
  /* #136: @45 = (-@22) */
  w45 = (- w22 );
  /* #137: (@44[7] = @45) */
  for (rr=w44+7, cs=(&w45); rr!=w44+8; rr+=1) *rr = *cs++;
  /* #138: (@44[1] = @17) */
  for (rr=w44+1, cs=(&w17); rr!=w44+2; rr+=1) *rr = *cs++;
  /* #139: @20 = (-@20) */
  w20 = (- w20 );
  /* #140: (@44[2] = @20) */
  for (rr=w44+2, cs=(&w20); rr!=w44+3; rr+=1) *rr = *cs++;
  /* #141: (@44[5] = @22) */
  for (rr=w44+5, cs=(&w22); rr!=w44+6; rr+=1) *rr = *cs++;
  /* #142: @46 = (2.*@44) */
  for (i=0, rr=w46, cs=w44; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #143: @47 = mac(@46,@44,@41) */
  casadi_copy(w41, 9, w47);
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w46+j, ct=w44+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #144: @32 = (@32+@47) */
  for (i=0, rr=w32, cr=wr32, cs=w47; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #145: @22 = @43[0] */
  for (rr=(&w22), cs=w43+0; cs!=w43+1; cs+=1) *rr++ = *cs;
  /* #146: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #147: @47 = (@22*@44) */
  for (i=0, rr=w47, cs=w44; i<9; ++i) (*rr++)  = (w22*(*cs++));
  /* #148: @32 = (@32+@47) */
  for (i=0, rr=w32, cs=w47; i<9; ++i) (*rr++) += (*cs++);
  /* #149: @48 = ones(4x1) */
  casadi_fill(w48, 4, 1.);
  /* #150: {@20, @17, @45, @49} = vertsplit(@48) */
  w20 = w48[0];
  w17 = w48[1];
  w45 = w48[2];
  w49 = w48[3];
  /* #151: @50 = vertcat(@40, @40, @20) */
  rr=(&w50);
  *rr++ = w20;
  /* #152: @31 = mac(@32,@50,@31) */
  casadi_mtimes(w32, casadi_s7, (&w50), casadi_s6, w31, casadi_s5, w, 0);
  /* #153: @51 = zeros(4x1,0nz) */
  /* #154: @15 = vertcat(@17, @45, @49) */
  rr=w15;
  *rr++ = w17;
  *rr++ = w45;
  *rr++ = w49;
  /* #155: @30 = (@30*@15) */
  for (i=0, rr=w30, cs=w15; i<3; ++i) (*rr++) *= (*cs++);
  /* #156: @52 = vertcat(@40, @40, @40, @31, @51, @30) */
  rr=w52;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #157: @53 = @52[:6] */
  for (rr=w53, cs=w52+0; cs!=w52+6; cs+=1) *rr++ = *cs;
  /* #158: (@39[:6] = @53) */
  for (rr=w39+0, cs=w53; rr!=w39+6; rr+=1) *rr = *cs++;
  /* #159: @53 = @39' */
  casadi_trans(w39,casadi_s9, w53, casadi_s8, iw);
  /* #160: @19 = mac(@38,@53,@19) */
  casadi_mtimes(w38, casadi_s4, w53, casadi_s8, (&w19), casadi_s10, w, 0);
  /* #161: @17 = input[1][0] */
  w17 = arg[1] ? arg[1][0] : 0;
  /* #162: @45 = input[1][1] */
  w45 = arg[1] ? arg[1][1] : 0;
  /* #163: @49 = input[1][2] */
  w49 = arg[1] ? arg[1][2] : 0;
  /* #164: @20 = input[1][3] */
  w20 = arg[1] ? arg[1][3] : 0;
  /* #165: @38 = vertcat(@17, @45, @49, @20) */
  rr=w38;
  *rr++ = w17;
  *rr++ = w45;
  *rr++ = w49;
  *rr++ = w20;
  /* #166: @17 = mac(@19,@38,@0) */
  casadi_copy((&w00), 1, (&w17));
  casadi_mtimes((&w19), casadi_s10, w38, casadi_s11, (&w17), casadi_s0, w, 0);
  /* #167: @37 = (@37+@17) */
  w37 += w17;
  /* #168: @11 = [15, 10] */
  casadi_copy(casadi_c4, 2, w11);
  /* #169: @54 = @11' */
  casadi_copy(w11, 2, w54);
  /* #170: @55 = vertcat(@2, @12) */
  rr=w55;
  *rr++ = w02;
  *rr++ = w12;
  /* #171: @2 = mac(@54,@55,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w54+j, ct=w55+i*2; k<2; ++k) *rr += cs[k*1]**ct++;
  /* #172: @37 = (@37+@2) */
  w37 += w02;
  /* #173: output[0][1] = @37 */
  if (res[0]) res[0][1] = w37;
  /* #174: @36 = zeros(17x2,13nz) */
  casadi_clear(w36, 13);
  /* #175: @37 = ones(2x1,1nz) */
  w37 = 1.;
  /* #176: {@2, NULL} = vertsplit(@37) */
  w02 = w37;
  /* #177: @14 = (@14*@2) */
  w14 *= w02;
  /* #178: @35 = @35' */
  /* #179: @56 = (@2*@35) */
  for (i=0, rr=w56, cs=w35; i<13; ++i) (*rr++)  = (w02*(*cs++));
  /* #180: @56 = @56' */
  /* #181: @57 = @56; (@57[1] = @0) */
  casadi_copy(w56, 13, w57);
  for (rr=w57+1, cs=(&w00); rr!=w57+2; rr+=1) *rr = *cs++;
  /* #182: @37 = @57[0] */
  for (rr=(&w37), cs=w57+0; cs!=w57+1; cs+=1) *rr++ = *cs;
  /* #183: @12 = (@6*@37) */
  w12  = (w06*w37);
  /* #184: @12 = (-@12) */
  w12 = (- w12 );
  /* #185: @17 = @56[1] */
  for (rr=(&w17), cs=w56+1; cs!=w56+2; cs+=1) *rr++ = *cs;
  /* #186: @45 = (@9*@17) */
  w45  = (w09*w17);
  /* #187: @12 = (@12-@45) */
  w12 -= w45;
  /* #188: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #189: @14 = (@14+@12) */
  w14 += w12;
  /* #190: @14 = (@14/@8) */
  w14 /= w08;
  /* #191: @12 = (@3*@14) */
  w12  = (w03*w14);
  /* #192: @37 = (@37/@8) */
  w37 /= w08;
  /* #193: @37 = (@5*@37) */
  w37  = (w05*w37);
  /* #194: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #195: @12 = (@12+@37) */
  w12 += w37;
  /* #196: (@36[0] = @12) */
  for (rr=w36+0, cs=(&w12); rr!=w36+1; rr+=1) *rr = *cs++;
  /* #197: @17 = (@17/@8) */
  w17 /= w08;
  /* #198: @17 = (@10*@17) */
  w17  = (w10*w17);
  /* #199: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #200: @14 = (@7*@14) */
  w14  = (w07*w14);
  /* #201: @17 = (@17+@14) */
  w17 += w14;
  /* #202: (@36[1] = @17) */
  for (rr=w36+1, cs=(&w17); rr!=w36+2; rr+=1) *rr = *cs++;
  /* #203: @54 = (@1*@2) */
  for (i=0, rr=w54, cr=w01; i<2; ++i) (*rr++)  = ((*cr++)*w02);
  /* #204: @56 = dense(@54) */
  casadi_densify(w54, casadi_s3, w56, 0);
  /* #205: {@2, @17, NULL, NULL, NULL, NULL} = vertsplit(@56) */
  w02 = w56[0];
  w17 = w56[1];
  /* #206: (@36[2] = @2) */
  for (rr=w36+2, cs=(&w02); rr!=w36+3; rr+=1) *rr = *cs++;
  /* #207: (@36[3] = @17) */
  for (rr=w36+3, cs=(&w17); rr!=w36+4; rr+=1) *rr = *cs++;
  /* #208: @19 = @19' */
  /* #209: @17 = ones(2x1,1nz) */
  w17 = 1.;
  /* #210: {NULL, @2} = vertsplit(@17) */
  w02 = w17;
  /* #211: @19 = (@19*@2) */
  w19 *= w02;
  /* #212: @48 = dense(@19) */
  casadi_densify((&w19), casadi_s12, w48, 0);
  /* #213: {@19, NULL, NULL, NULL} = vertsplit(@48) */
  w19 = w48[0];
  /* #214: (@36[4] = @19) */
  for (rr=w36+4, cs=(&w19); rr!=w36+5; rr+=1) *rr = *cs++;
  /* #215: @48 = zeros(1x13,4nz) */
  casadi_clear(w48, 4);
  /* #216: @38 = @38' */
  /* #217: @38 = (@2*@38) */
  for (i=0, rr=w38, cs=w38; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #218: @48 = mac(@38,@39,@48) */
  casadi_mtimes(w38, casadi_s13, w39, casadi_s9, w48, casadi_s4, w, 0);
  /* #219: @48 = @48' */
  /* #220: @58 = @48; (@58[3] = @0) */
  casadi_copy(w48, 4, w58);
  for (rr=w58+3, cs=(&w00); rr!=w58+4; rr+=1) *rr = *cs++;
  /* #221: @59 = @58; (@59[2] = @0) */
  casadi_copy(w58, 4, w59);
  for (rr=w59+2, cs=(&w00); rr!=w59+3; rr+=1) *rr = *cs++;
  /* #222: @60 = @59; (@60[1] = @0) */
  casadi_copy(w59, 4, w60);
  for (rr=w60+1, cs=(&w00); rr!=w60+2; rr+=1) *rr = *cs++;
  /* #223: @19 = @60[0] */
  for (rr=(&w19), cs=w60+0; cs!=w60+1; cs+=1) *rr++ = *cs;
  /* #224: @17 = (@28*@19) */
  w17  = (w28*w19);
  /* #225: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #226: @56 = (@2*@35) */
  for (i=0, rr=w56, cs=w35; i<13; ++i) (*rr++)  = (w02*(*cs++));
  /* #227: @56 = @56' */
  /* #228: @57 = @56; (@57[4] = @0) */
  casadi_copy(w56, 13, w57);
  for (rr=w57+4, cs=(&w00); rr!=w57+5; rr+=1) *rr = *cs++;
  /* #229: @61 = @57; (@61[3] = @0) */
  casadi_copy(w57, 13, w61);
  for (rr=w61+3, cs=(&w00); rr!=w61+4; rr+=1) *rr = *cs++;
  /* #230: @62 = @61; (@62[1] = @0) */
  casadi_copy(w61, 13, w62);
  for (rr=w62+1, cs=(&w00); rr!=w62+2; rr+=1) *rr = *cs++;
  /* #231: @14 = @62[0] */
  for (rr=(&w14), cs=w62+0; cs!=w62+1; cs+=1) *rr++ = *cs;
  /* #232: @12 = (@28*@14) */
  w12  = (w28*w14);
  /* #233: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #234: @17 = (@17+@12) */
  w17 += w12;
  /* #235: @12 = (@28/@8) */
  w12  = (w28/w08);
  /* #236: @37 = @59[1] */
  for (rr=(&w37), cs=w59+1; cs!=w59+2; cs+=1) *rr++ = *cs;
  /* #237: @45 = (@7*@37) */
  w45  = (w07*w37);
  /* #238: @49 = (@3*@19) */
  w49  = (w03*w19);
  /* #239: @45 = (@45+@49) */
  w45 += w49;
  /* #240: @49 = (@12*@45) */
  w49  = (w12*w45);
  /* #241: @49 = (-@49) */
  w49 = (- w49 );
  /* #242: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #243: @20 = @61[1] */
  for (rr=(&w20), cs=w61+1; cs!=w61+2; cs+=1) *rr++ = *cs;
  /* #244: @63 = (@7*@20) */
  w63  = (w07*w20);
  /* #245: @64 = (@3*@14) */
  w64  = (w03*w14);
  /* #246: @63 = (@63+@64) */
  w63 += w64;
  /* #247: @12 = (@12*@63) */
  w12 *= w63;
  /* #248: @12 = (-@12) */
  w12 = (- w12 );
  /* #249: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #250: @49 = (@49+@12) */
  w49 += w12;
  /* #251: @11 = (@11*@2) */
  for (i=0, rr=w11; i<2; ++i) (*rr++) *= w02;
  /* #252: {@12, @64} = vertsplit(@11) */
  w12 = w11[0];
  w64 = w11[1];
  /* #253: @49 = (@49+@12) */
  w49 += w12;
  /* #254: @27 = (@27/@8) */
  w27 /= w08;
  /* #255: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #256: @19 = (@5*@19) */
  w19  = (w05*w19);
  /* #257: @12 = (@27*@19) */
  w12  = (w27*w19);
  /* #258: @12 = (-@12) */
  w12 = (- w12 );
  /* #259: @26 = (@26/@8) */
  w26 /= w08;
  /* #260: @65 = (2.*@37) */
  w65 = (2.* w37 );
  /* #261: @65 = (@10*@65) */
  w65  = (w10*w65);
  /* #262: @66 = (@26*@65) */
  w66  = (w26*w65);
  /* #263: @12 = (@12-@66) */
  w12 -= w66;
  /* #264: @66 = (@9/@8) */
  w66  = (w09/w08);
  /* #265: @45 = (@45/@8) */
  w45 /= w08;
  /* #266: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #267: @67 = (@13*@45) */
  w67  = (w13*w45);
  /* #268: @68 = (@66*@67) */
  w68  = (w66*w67);
  /* #269: @12 = (@12+@68) */
  w12 += w68;
  /* #270: @68 = (@6/@8) */
  w68  = (w06/w08);
  /* #271: @69 = (@25*@45) */
  w69  = (w25*w45);
  /* #272: @70 = (@68*@69) */
  w70  = (w68*w69);
  /* #273: @12 = (@12+@70) */
  w12 += w70;
  /* #274: @70 = (2.*@20) */
  w70 = (2.* w20 );
  /* #275: @70 = (@10*@70) */
  w70  = (w10*w70);
  /* #276: @26 = (@26*@70) */
  w26 *= w70;
  /* #277: @12 = (@12-@26) */
  w12 -= w26;
  /* #278: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #279: @14 = (@5*@14) */
  w14  = (w05*w14);
  /* #280: @27 = (@27*@14) */
  w27 *= w14;
  /* #281: @12 = (@12-@27) */
  w12 -= w27;
  /* #282: @63 = (@63/@8) */
  w63 /= w08;
  /* #283: @63 = (2.*@63) */
  w63 = (2.* w63 );
  /* #284: @13 = (@13*@63) */
  w13 *= w63;
  /* #285: @66 = (@66*@13) */
  w66 *= w13;
  /* #286: @12 = (@12+@66) */
  w12 += w66;
  /* #287: @25 = (@25*@63) */
  w25 *= w63;
  /* #288: @68 = (@68*@25) */
  w68 *= w25;
  /* #289: @12 = (@12+@68) */
  w12 += w68;
  /* #290: @13 = (@13/@8) */
  w13 /= w08;
  /* #291: @13 = (-@13) */
  w13 = (- w13 );
  /* #292: @67 = (@67/@8) */
  w67 /= w08;
  /* #293: @13 = (@13-@67) */
  w13 -= w67;
  /* #294: @67 = @58[2] */
  for (rr=(&w67), cs=w58+2; cs!=w58+3; cs+=1) *rr++ = *cs;
  /* #295: @68 = @48[3] */
  for (rr=(&w68), cs=w48+3; cs!=w48+4; cs+=1) *rr++ = *cs;
  /* #296: @71 = zeros(3x1,0nz) */
  /* #297: @11 = vertcat(@67, @68, @40, @71, @51, @71) */
  rr=w11;
  *rr++ = w67;
  *rr++ = w68;
  /* #298: @67 = @57[3] */
  for (rr=(&w67), cs=w57+3; cs!=w57+4; cs+=1) *rr++ = *cs;
  /* #299: @68 = @56[4] */
  for (rr=(&w68), cs=w56+4; cs!=w56+5; cs+=1) *rr++ = *cs;
  /* #300: @54 = vertcat(@67, @68, @40, @71, @51, @71) */
  rr=w54;
  *rr++ = w67;
  *rr++ = w68;
  /* #301: @11 = (@11+@54) */
  for (i=0, rr=w11, cs=w54; i<2; ++i) (*rr++) += (*cs++);
  /* #302: @56 = dense(@11) */
  casadi_densify(w11, casadi_s3, w56, 0);
  /* #303: @35 = (@64*@35) */
  for (i=0, rr=w35, cs=w35; i<13; ++i) (*rr++)  = (w64*(*cs++));
  /* #304: @35 = @35' */
  /* #305: @56 = (@56+@35) */
  for (i=0, rr=w56, cs=w35; i<13; ++i) (*rr++) += (*cs++);
  /* #306: @67 = @56[1] */
  for (rr=(&w67), cs=w56+1; cs!=w56+2; cs+=1) *rr++ = *cs;
  /* #307: @13 = (@13+@67) */
  w13 += w67;
  /* #308: @67 = (@9*@13) */
  w67  = (w09*w13);
  /* #309: @12 = (@12-@67) */
  w12 -= w67;
  /* #310: @25 = (@25/@8) */
  w25 /= w08;
  /* #311: @25 = (-@25) */
  w25 = (- w25 );
  /* #312: @69 = (@69/@8) */
  w69 /= w08;
  /* #313: @25 = (@25-@69) */
  w25 -= w69;
  /* #314: (@56[1] = @0) */
  for (rr=w56+1, cs=(&w00); rr!=w56+2; rr+=1) *rr = *cs++;
  /* #315: @69 = @56[0] */
  for (rr=(&w69), cs=w56+0; cs!=w56+1; cs+=1) *rr++ = *cs;
  /* #316: @25 = (@25+@69) */
  w25 += w69;
  /* #317: @69 = (@6*@25) */
  w69  = (w06*w25);
  /* #318: @12 = (@12-@69) */
  w12 -= w69;
  /* #319: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #320: @49 = (@49+@12) */
  w49 += w12;
  /* #321: @49 = (@49/@8) */
  w49 /= w08;
  /* #322: @3 = (@3*@49) */
  w03 *= w49;
  /* #323: @17 = (@17+@3) */
  w17 += w03;
  /* #324: @25 = (@25/@8) */
  w25 /= w08;
  /* #325: @5 = (@5*@25) */
  w05 *= w25;
  /* #326: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #327: @17 = (@17+@5) */
  w17 += w05;
  /* #328: (@36[5] = @17) */
  for (rr=w36+5, cs=(&w17); rr!=w36+6; rr+=1) *rr = *cs++;
  /* #329: @37 = (@28*@37) */
  w37  = (w28*w37);
  /* #330: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #331: @28 = (@28*@20) */
  w28 *= w20;
  /* #332: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #333: @37 = (@37+@28) */
  w37 += w28;
  /* #334: @13 = (@13/@8) */
  w13 /= w08;
  /* #335: @10 = (@10*@13) */
  w10 *= w13;
  /* #336: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #337: @37 = (@37+@10) */
  w37 += w10;
  /* #338: @7 = (@7*@49) */
  w07 *= w49;
  /* #339: @37 = (@37+@7) */
  w37 += w07;
  /* #340: (@36[6] = @37) */
  for (rr=w36+6, cs=(&w37); rr!=w36+7; rr+=1) *rr = *cs++;
  /* #341: @56 = zeros(13x1) */
  casadi_clear(w56, 13);
  /* #342: @19 = (@19/@8) */
  w19 /= w08;
  /* #343: @37 = (@6*@45) */
  w37  = (w06*w45);
  /* #344: @19 = (@19-@37) */
  w19 -= w37;
  /* #345: @35 = @56; (@35[0] += @19) */
  casadi_copy(w56, 13, w35);
  for (rr=w35+0, cs=(&w19); rr!=w35+1; rr+=1) *rr += *cs++;
  /* #346: (@35[1] = @0) */
  for (rr=w35+1, cs=(&w00); rr!=w35+2; rr+=1) *rr = *cs++;
  /* #347: @48 = (@29*@2) */
  for (i=0, rr=w48, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w02);
  /* #348: @57 = dense(@48) */
  casadi_densify(w48, casadi_s14, w57, 0);
  /* #349: @35 = (@35+@57) */
  for (i=0, rr=w35, cs=w57; i<13; ++i) (*rr++) += (*cs++);
  /* #350: @14 = (@14/@8) */
  w14 /= w08;
  /* #351: @6 = (@6*@63) */
  w06 *= w63;
  /* #352: @14 = (@14-@6) */
  w14 -= w06;
  /* #353: (@56[0] += @14) */
  for (rr=w56+0, cs=(&w14); rr!=w56+1; rr+=1) *rr += *cs++;
  /* #354: (@56[1] = @0) */
  for (rr=w56+1, cs=(&w00); rr!=w56+2; rr+=1) *rr = *cs++;
  /* #355: @35 = (@35+@56) */
  for (i=0, rr=w35, cs=w56; i<13; ++i) (*rr++) += (*cs++);
  /* #356: @1 = (@1*@64) */
  for (i=0, rr=w01; i<2; ++i) (*rr++) *= w64;
  /* #357: @56 = dense(@1) */
  casadi_densify(w01, casadi_s3, w56, 0);
  /* #358: @35 = (@35+@56) */
  for (i=0, rr=w35, cs=w56; i<13; ++i) (*rr++) += (*cs++);
  /* #359: {@64, @14, NULL, NULL, @48, NULL} = vertsplit(@35) */
  w64 = w35[0];
  w14 = w35[1];
  casadi_copy(w35+6, 4, w48);
  /* #360: (@36[7] = @64) */
  for (rr=w36+7, cs=(&w64); rr!=w36+8; rr+=1) *rr = *cs++;
  /* #361: @65 = (@65/@8) */
  w65 /= w08;
  /* #362: @45 = (@9*@45) */
  w45  = (w09*w45);
  /* #363: @65 = (@65-@45) */
  w65 -= w45;
  /* #364: @70 = (@70/@8) */
  w70 /= w08;
  /* #365: @65 = (@65+@70) */
  w65 += w70;
  /* #366: @9 = (@9*@63) */
  w09 *= w63;
  /* #367: @65 = (@65-@9) */
  w65 -= w09;
  /* #368: @65 = (@65+@14) */
  w65 += w14;
  /* #369: (@36[8] = @65) */
  for (rr=w36+8, cs=(&w65); rr!=w36+9; rr+=1) *rr = *cs++;
  /* #370: @58 = zeros(4x1) */
  casadi_clear(w58, 4);
  /* #371: @39 = zeros(13x1,6nz) */
  casadi_clear(w39, 6);
  /* #372: @53 = zeros(13x4,6nz) */
  casadi_clear(w53, 6);
  /* #373: @53 = mac(@29,@38,@53) */
  casadi_mtimes(w29, casadi_s14, w38, casadi_s13, w53, casadi_s8, w, 0);
  /* #374: @52 = @53' */
  casadi_trans(w53,casadi_s8, w52, casadi_s9, iw);
  /* #375: @53 = @52[:6] */
  for (rr=w53, cs=w52+0; cs!=w52+6; cs+=1) *rr++ = *cs;
  /* #376: (@39[:6] += @53) */
  for (rr=w39+0, cs=w53; rr!=w39+6; rr+=1) *rr += *cs++;
  /* #377: {NULL, NULL, NULL, @31, NULL, NULL} = vertsplit(@39) */
  casadi_copy(w39, 3, w31);
  /* #378: @50 = @50' */
  /* #379: @32 = mac(@31,@50,@41) */
  casadi_copy(w41, 9, w32);
  casadi_mtimes(w31, casadi_s5, (&w50), casadi_s15, w32, casadi_s7, w, 0);
  /* #380: @50 = dot(@44, @32) */
  w50 = casadi_dot(9, w44, w32);
  /* #381: @50 = (2.*@50) */
  w50 = (2.* w50 );
  /* #382: (@58[0] += @50) */
  for (rr=w58+0, cs=(&w50); rr!=w58+1; rr+=1) *rr += *cs++;
  /* #383: @47 = (@22*@32) */
  for (i=0, rr=w47, cs=w32; i<9; ++i) (*rr++)  = (w22*(*cs++));
  /* #384: @72 = @46' */
  for (i=0, rr=w72, cs=w46; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #385: @46 = mac(@72,@32,@41) */
  casadi_copy(w41, 9, w46);
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w72+j, ct=w32+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #386: @47 = (@47+@46) */
  for (i=0, rr=w47, cs=w46; i<9; ++i) (*rr++) += (*cs++);
  /* #387: @46 = @44' */
  for (i=0, rr=w46, cs=w44; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #388: @41 = mac(@32,@46,@41) */
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=w46+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #389: @41 = (2.*@41) */
  for (i=0, rr=w41, cs=w41; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #390: @47 = (@47+@41) */
  for (i=0, rr=w47, cs=w41; i<9; ++i) (*rr++) += (*cs++);
  /* #391: @22 = @47[5] */
  for (rr=(&w22), cs=w47+5; cs!=w47+6; cs+=1) *rr++ = *cs;
  /* #392: (@58[1] += @22) */
  for (rr=w58+1, cs=(&w22); rr!=w58+2; rr+=1) *rr += *cs++;
  /* #393: (@47[5] = @0) */
  for (rr=w47+5, cs=(&w00); rr!=w47+6; rr+=1) *rr = *cs++;
  /* #394: @22 = @47[2] */
  for (rr=(&w22), cs=w47+2; cs!=w47+3; cs+=1) *rr++ = *cs;
  /* #395: @22 = (-@22) */
  w22 = (- w22 );
  /* #396: (@58[2] += @22) */
  for (rr=w58+2, cs=(&w22); rr!=w58+3; rr+=1) *rr += *cs++;
  /* #397: (@47[2] = @0) */
  for (rr=w47+2, cs=(&w00); rr!=w47+3; rr+=1) *rr = *cs++;
  /* #398: @22 = @47[1] */
  for (rr=(&w22), cs=w47+1; cs!=w47+2; cs+=1) *rr++ = *cs;
  /* #399: (@58[3] += @22) */
  for (rr=w58+3, cs=(&w22); rr!=w58+4; rr+=1) *rr += *cs++;
  /* #400: (@47[1] = @0) */
  for (rr=w47+1, cs=(&w00); rr!=w47+2; rr+=1) *rr = *cs++;
  /* #401: @22 = @47[7] */
  for (rr=(&w22), cs=w47+7; cs!=w47+8; cs+=1) *rr++ = *cs;
  /* #402: @22 = (-@22) */
  w22 = (- w22 );
  /* #403: (@58[1] += @22) */
  for (rr=w58+1, cs=(&w22); rr!=w58+2; rr+=1) *rr += *cs++;
  /* #404: (@47[7] = @0) */
  for (rr=w47+7, cs=(&w00); rr!=w47+8; rr+=1) *rr = *cs++;
  /* #405: @22 = @47[6] */
  for (rr=(&w22), cs=w47+6; cs!=w47+7; cs+=1) *rr++ = *cs;
  /* #406: (@58[2] += @22) */
  for (rr=w58+2, cs=(&w22); rr!=w58+3; rr+=1) *rr += *cs++;
  /* #407: (@47[6] = @0) */
  for (rr=w47+6, cs=(&w00); rr!=w47+7; rr+=1) *rr = *cs++;
  /* #408: @0 = @47[3] */
  for (rr=(&w00), cs=w47+3; cs!=w47+4; cs+=1) *rr++ = *cs;
  /* #409: @0 = (-@0) */
  w00 = (- w00 );
  /* #410: (@58[3] += @0) */
  for (rr=w58+3, cs=(&w00); rr!=w58+4; rr+=1) *rr += *cs++;
  /* #411: @29 = (@58/@24) */
  for (i=0, rr=w29, cr=w58; i<4; ++i) (*rr++)  = ((*cr++)/w24);
  /* #412: @43 = (@43/@24) */
  for (i=0, rr=w43; i<4; ++i) (*rr++) /= w24;
  /* #413: @43 = (-@43) */
  for (i=0, rr=w43, cs=w43; i<4; ++i) *rr++ = (- *cs++ );
  /* #414: @0 = dot(@43, @58) */
  w00 = casadi_dot(4, w43, w58);
  /* #415: @0 = (@0/@24) */
  w00 /= w24;
  /* #416: @42 = (@0*@42) */
  for (i=0, rr=w42, cs=w42; i<4; ++i) (*rr++)  = (w00*(*cs++));
  /* #417: @29 = (@29+@42) */
  for (i=0, rr=w29, cs=w42; i<4; ++i) (*rr++) += (*cs++);
  /* #418: {@0, @24, @22, @50} = vertsplit(@29) */
  w00 = w29[0];
  w24 = w29[1];
  w22 = w29[2];
  w50 = w29[3];
  /* #419: @48 = (@16*@48) */
  for (i=0, rr=w48, cs=w48; i<4; ++i) (*rr++)  = (w16*(*cs++));
  /* #420: {@16, @65, @14, @9} = vertsplit(@48) */
  w16 = w48[0];
  w65 = w48[1];
  w14 = w48[2];
  w09 = w48[3];
  /* #421: @63 = (@23*@9) */
  w63  = (w23*w09);
  /* #422: @0 = (@0+@63) */
  w00 += w63;
  /* #423: @63 = (@21*@14) */
  w63  = (w21*w14);
  /* #424: @0 = (@0+@63) */
  w00 += w63;
  /* #425: @63 = (@18*@65) */
  w63  = (w18*w65);
  /* #426: @0 = (@0+@63) */
  w00 += w63;
  /* #427: (@36[9] = @0) */
  for (rr=w36+9, cs=(&w00); rr!=w36+10; rr+=1) *rr = *cs++;
  /* #428: @0 = (@21*@9) */
  w00  = (w21*w09);
  /* #429: @24 = (@24+@0) */
  w24 += w00;
  /* #430: @0 = (@23*@14) */
  w00  = (w23*w14);
  /* #431: @24 = (@24-@0) */
  w24 -= w00;
  /* #432: @0 = (@18*@16) */
  w00  = (w18*w16);
  /* #433: @24 = (@24-@0) */
  w24 -= w00;
  /* #434: (@36[10] = @24) */
  for (rr=w36+10, cs=(&w24); rr!=w36+11; rr+=1) *rr = *cs++;
  /* #435: @9 = (@18*@9) */
  w09  = (w18*w09);
  /* #436: @22 = (@22-@9) */
  w22 -= w09;
  /* #437: @9 = (@23*@65) */
  w09  = (w23*w65);
  /* #438: @22 = (@22+@9) */
  w22 += w09;
  /* #439: @9 = (@21*@16) */
  w09  = (w21*w16);
  /* #440: @22 = (@22-@9) */
  w22 -= w09;
  /* #441: (@36[11] = @22) */
  for (rr=w36+11, cs=(&w22); rr!=w36+12; rr+=1) *rr = *cs++;
  /* #442: @18 = (@18*@14) */
  w18 *= w14;
  /* #443: @50 = (@50+@18) */
  w50 += w18;
  /* #444: @21 = (@21*@65) */
  w21 *= w65;
  /* #445: @50 = (@50-@21) */
  w50 -= w21;
  /* #446: @23 = (@23*@16) */
  w23 *= w16;
  /* #447: @50 = (@50-@23) */
  w50 -= w23;
  /* #448: (@36[12] = @50) */
  for (rr=w36+12, cs=(&w50); rr!=w36+13; rr+=1) *rr = *cs++;
  /* #449: output[1][0] = @36 */
  casadi_copy(w36, 13, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s17;
    case 2: return casadi_s18;
    case 3: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    case 1: return casadi_s21;
    case 2: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 267;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 16*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 267*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
