/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {17, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c1[3] = {0., 0., 1.};
static const casadi_real casadi_c2[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c3[9] = 
  {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0.,
  1.5968700000000000e-03};

/* Drone_ode_complete_expl_ode_fun:(i0[13],i1[4],i2[17])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, *w02=w+7, *w03=w+16, w04, w05, w06, *w07=w+28, w08, w09, *w10=w+34;
  casadi_real w11, w12, *w13=w+45, *w14=w+54, *w15=w+57, w16, w17, w18, w19, *w20=w+64;
  const casadi_real *cr, *cs, *ct, *wr02;
  /* #0: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = input[0][4] */
  w00 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #4: @0 = input[0][5] */
  w00 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #6: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #7: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr02 = casadi_c0;
  /* #8: @3 = zeros(3x3) */
  casadi_clear(w03, 9);
  /* #9: @0 = input[0][6] */
  w00 = arg[0] ? arg[0][6] : 0;
  /* #10: @4 = input[0][7] */
  w04 = arg[0] ? arg[0][7] : 0;
  /* #11: @5 = input[0][8] */
  w05 = arg[0] ? arg[0][8] : 0;
  /* #12: @6 = input[0][9] */
  w06 = arg[0] ? arg[0][9] : 0;
  /* #13: @7 = vertcat(@0, @4, @5, @6) */
  rr=w07;
  *rr++ = w00;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #14: @8 = ||@7||_F */
  w08 = casadi_norm_2(4, w07);
  /* #15: @7 = (@7/@8) */
  for (i=0, rr=w07; i<4; ++i) (*rr++) /= w08;
  /* #16: @8 = @7[3] */
  for (rr=(&w08), cs=w07+3; cs!=w07+4; cs+=1) *rr++ = *cs;
  /* #17: @9 = (-@8) */
  w09 = (- w08 );
  /* #18: @10 = @3; (@10[3] = @9) */
  casadi_copy(w03, 9, w10);
  for (rr=w10+3, cs=(&w09); rr!=w10+4; rr+=1) *rr = *cs++;
  /* #19: @9 = @7[2] */
  for (rr=(&w09), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #20: (@10[6] = @9) */
  for (rr=w10+6, cs=(&w09); rr!=w10+7; rr+=1) *rr = *cs++;
  /* #21: @11 = @7[1] */
  for (rr=(&w11), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #22: @12 = (-@11) */
  w12 = (- w11 );
  /* #23: (@10[7] = @12) */
  for (rr=w10+7, cs=(&w12); rr!=w10+8; rr+=1) *rr = *cs++;
  /* #24: (@10[1] = @8) */
  for (rr=w10+1, cs=(&w08); rr!=w10+2; rr+=1) *rr = *cs++;
  /* #25: @9 = (-@9) */
  w09 = (- w09 );
  /* #26: (@10[2] = @9) */
  for (rr=w10+2, cs=(&w09); rr!=w10+3; rr+=1) *rr = *cs++;
  /* #27: (@10[5] = @11) */
  for (rr=w10+5, cs=(&w11); rr!=w10+6; rr+=1) *rr = *cs++;
  /* #28: @13 = (2.*@10) */
  for (i=0, rr=w13, cs=w10; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #29: @3 = mac(@13,@10,@3) */
  for (i=0, rr=w03; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w13+j, ct=w10+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #30: @2 = (@2+@3) */
  for (i=0, rr=w02, cr=wr02, cs=w03; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #31: @11 = @7[0] */
  for (rr=(&w11), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #32: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #33: @10 = (@11*@10) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) (*rr++)  = (w11*(*cs++));
  /* #34: @2 = (@2+@10) */
  for (i=0, rr=w02, cs=w10; i<9; ++i) (*rr++) += (*cs++);
  /* #35: @11 = 0 */
  w11 = 0.;
  /* #36: @9 = input[1][0] */
  w09 = arg[1] ? arg[1][0] : 0;
  /* #37: @14 = vertcat(@11, @11, @9) */
  rr=w14;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w09;
  /* #38: @15 = mac(@2,@14,@1) */
  casadi_copy(w01, 3, w15);
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w02+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #39: @14 = [0, 0, 1] */
  casadi_copy(casadi_c1, 3, w14);
  /* #40: @11 = 9.81 */
  w11 = 9.8100000000000005e+00;
  /* #41: @14 = (@14*@11) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) *= w11;
  /* #42: @15 = (@15-@14) */
  for (i=0, rr=w15, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #43: output[0][3] = @15 */
  if (res[0]) casadi_copy(w15, 3, res[0]+3);
  /* #44: @11 = 0.5 */
  w11 = 5.0000000000000000e-01;
  /* #45: @9 = input[0][10] */
  w09 = arg[0] ? arg[0][10] : 0;
  /* #46: @8 = (@4*@9) */
  w08  = (w04*w09);
  /* #47: @8 = (-@8) */
  w08 = (- w08 );
  /* #48: @12 = input[0][11] */
  w12 = arg[0] ? arg[0][11] : 0;
  /* #49: @16 = (@5*@12) */
  w16  = (w05*w12);
  /* #50: @8 = (@8-@16) */
  w08 -= w16;
  /* #51: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #52: @17 = (@6*@16) */
  w17  = (w06*w16);
  /* #53: @8 = (@8-@17) */
  w08 -= w17;
  /* #54: @17 = (@0*@9) */
  w17  = (w00*w09);
  /* #55: @18 = (@5*@16) */
  w18  = (w05*w16);
  /* #56: @17 = (@17+@18) */
  w17 += w18;
  /* #57: @18 = (@6*@12) */
  w18  = (w06*w12);
  /* #58: @17 = (@17-@18) */
  w17 -= w18;
  /* #59: @18 = (@0*@12) */
  w18  = (w00*w12);
  /* #60: @19 = (@4*@16) */
  w19  = (w04*w16);
  /* #61: @18 = (@18-@19) */
  w18 -= w19;
  /* #62: @6 = (@6*@9) */
  w06 *= w09;
  /* #63: @18 = (@18+@6) */
  w18 += w06;
  /* #64: @0 = (@0*@16) */
  w00 *= w16;
  /* #65: @4 = (@4*@12) */
  w04 *= w12;
  /* #66: @0 = (@0+@4) */
  w00 += w04;
  /* #67: @5 = (@5*@9) */
  w05 *= w09;
  /* #68: @0 = (@0-@5) */
  w00 -= w05;
  /* #69: @7 = vertcat(@8, @17, @18, @0) */
  rr=w07;
  *rr++ = w08;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w00;
  /* #70: @7 = (@11*@7) */
  for (i=0, rr=w07, cs=w07; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #71: output[0][4] = @7 */
  if (res[0]) casadi_copy(w07, 4, res[0]+6);
  /* #72: @15 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c2, 3, w15);
  /* #73: @15 = nonzeros(@15) */
  /* #74: @11 = input[1][1] */
  w11 = arg[1] ? arg[1][1] : 0;
  /* #75: @8 = input[1][2] */
  w08 = arg[1] ? arg[1][2] : 0;
  /* #76: @17 = input[1][3] */
  w17 = arg[1] ? arg[1][3] : 0;
  /* #77: @14 = vertcat(@11, @8, @17) */
  rr=w14;
  *rr++ = w11;
  *rr++ = w08;
  *rr++ = w17;
  /* #78: @2 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  wr02 = casadi_c3;
  /* #79: @20 = vertcat(@9, @12, @16) */
  rr=w20;
  *rr++ = w09;
  *rr++ = w12;
  *rr++ = w16;
  /* #80: @1 = mac(@2,@20,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr02+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #81: @11 = @1[2] */
  for (rr=(&w11), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #82: @8 = (@12*@11) */
  w08  = (w12*w11);
  /* #83: @17 = @1[1] */
  for (rr=(&w17), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #84: @18 = (@16*@17) */
  w18  = (w16*w17);
  /* #85: @8 = (@8-@18) */
  w08 -= w18;
  /* #86: @18 = @1[0] */
  for (rr=(&w18), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #87: @16 = (@16*@18) */
  w16 *= w18;
  /* #88: @11 = (@9*@11) */
  w11  = (w09*w11);
  /* #89: @16 = (@16-@11) */
  w16 -= w11;
  /* #90: @9 = (@9*@17) */
  w09 *= w17;
  /* #91: @12 = (@12*@18) */
  w12 *= w18;
  /* #92: @9 = (@9-@12) */
  w09 -= w12;
  /* #93: @1 = vertcat(@8, @16, @9) */
  rr=w01;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w09;
  /* #94: @14 = (@14-@1) */
  for (i=0, rr=w14, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #95: @15 = (@15*@14) */
  for (i=0, rr=w15, cs=w14; i<3; ++i) (*rr++) *= (*cs++);
  /* #96: output[0][5] = @15 */
  if (res[0]) casadi_copy(w15, 3, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 67;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 67*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
